//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class ACCEnergyConfig, UIImageView, UILabel;

@interface ACCGreenEnergyView : UIView
{
    ACCEnergyConfig *_data;
    UIImageView *_imageIcon;
    UILabel *_labelTitle;
}

@property(retain, nonatomic) UILabel *labelTitle; // @synthesize labelTitle=_labelTitle;
@property(retain, nonatomic) UIImageView *imageIcon; // @synthesize imageIcon=_imageIcon;
@property(retain, nonatomic) ACCEnergyConfig *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (id)greenTitleWithData:(id)arg1;
- (void)createSubviews;
- (id)initWithData:(id)arg1;

@end

