//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ACCPollingConfig, NSMutableArray, NSString, NSTimer;

@interface ACCPollingManager : NSObject
{
    _Bool _rpcRunning;
    ACCPollingConfig *_config;
    NSString *_cardType;
    NSString *_cardNo;
    NSString *_source;
    CDUnknownBlockType _qrResultHandler;
    CDUnknownBlockType _orderResultHandler;
    CDUnknownBlockType _resultHandler;
    NSTimer *_timer;
    long long _startPollingTime;
    NSMutableArray *_rpcArr;
}

@property(retain, nonatomic) NSMutableArray *rpcArr; // @synthesize rpcArr=_rpcArr;
@property(nonatomic) _Bool rpcRunning; // @synthesize rpcRunning=_rpcRunning;
@property(nonatomic) long long startPollingTime; // @synthesize startPollingTime=_startPollingTime;
@property(retain, nonatomic) NSTimer *timer; // @synthesize timer=_timer;
@property(copy, nonatomic) CDUnknownBlockType resultHandler; // @synthesize resultHandler=_resultHandler;
@property(copy, nonatomic) CDUnknownBlockType orderResultHandler; // @synthesize orderResultHandler=_orderResultHandler;
@property(copy, nonatomic) CDUnknownBlockType qrResultHandler; // @synthesize qrResultHandler=_qrResultHandler;
@property(retain, nonatomic) NSString *source; // @synthesize source=_source;
@property(retain, nonatomic) NSString *cardNo; // @synthesize cardNo=_cardNo;
@property(retain, nonatomic) NSString *cardType; // @synthesize cardType=_cardType;
@property(retain, nonatomic) ACCPollingConfig *config; // @synthesize config=_config;
- (void).cxx_destruct;
- (void)doResultQueryRPC;
- (void)doQrQueryRPC;
- (void)doOrderQueryRPC;
- (_Bool)validPollingId:(id)arg1 storeKey:(id)arg2;
- (void)polling;
- (void)tryStop;
- (void)tryStart;
- (void)dealloc;

@end

