//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "CKAnalyzerHandler-Protocol.h"

@class NSString;
@protocol CKAnalyzerHandler;

@interface ACKAnalyzerHandler : NSObject <CKAnalyzerHandler>
{
    id <CKAnalyzerHandler> _handler;
}

+ (id)createWithHandler:(id)arg1;
@property(retain, nonatomic) id <CKAnalyzerHandler> handler; // @synthesize handler=_handler;
- (void).cxx_destruct;
- (void)analyzeWithInfo:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

