//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIImageView, UILabel, UIView, finscbffLiveInfoItemPB;

@interface AFWStockIndexLiveItemCell : UITableViewCell
{
    UILabel *_subTitleLabel;
    UILabel *_titleLabel;
    UILabel *_timeLabel;
    UILabel *_commenLabel;
    UIView *_pointView;
    UIView *_upLineView;
    UIView *_downLineView;
    UIImageView *_arrowImageView;
    finscbffLiveInfoItemPB *_model;
}

@property(retain, nonatomic) finscbffLiveInfoItemPB *model; // @synthesize model=_model;
@property(retain, nonatomic) UIImageView *arrowImageView; // @synthesize arrowImageView=_arrowImageView;
@property(retain, nonatomic) UIView *downLineView; // @synthesize downLineView=_downLineView;
@property(retain, nonatomic) UIView *upLineView; // @synthesize upLineView=_upLineView;
@property(retain, nonatomic) UIView *pointView; // @synthesize pointView=_pointView;
@property(retain, nonatomic) UILabel *commenLabel; // @synthesize commenLabel=_commenLabel;
@property(retain, nonatomic) UILabel *timeLabel; // @synthesize timeLabel=_timeLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *subTitleLabel; // @synthesize subTitleLabel=_subTitleLabel;
- (void).cxx_destruct;
- (void)updateWithModel:(id)arg1;
- (void)setUpView;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

