//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "AFWStockPagingProtocol-Protocol.h"

@class AFWStockPagingItem, AFWStockPagingView, NSString;

@interface AFWStockPagingViewPageView : UIView <AFWStockPagingProtocol>
{
    _Bool _isVisible;
    AFWStockPagingItem *_item;
    long long _pageIndex;
    AFWStockPagingView *_contentSliderView;
}

@property(nonatomic) __weak AFWStockPagingView *contentSliderView; // @synthesize contentSliderView=_contentSliderView;
@property(nonatomic) _Bool isVisible; // @synthesize isVisible=_isVisible;
@property(nonatomic) long long pageIndex; // @synthesize pageIndex=_pageIndex;
@property(readonly, nonatomic) AFWStockPagingItem *item; // @synthesize item=_item;
- (void).cxx_destruct;
- (void)addToSliderView:(id)arg1 frame:(struct CGRect)arg2;
- (void)removeFromSliderView:(id)arg1;
- (void)pageDidDisappear:(_Bool)arg1;
- (void)pageDidAppear:(_Bool)arg1;
- (void)pageDidBecomeVisible;
- (void)pageDidBecomeInvisible;
- (void)loadView;
- (id)initWithFrame:(struct CGRect)arg1 sliderItem:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

