//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class UIButton, UILabel;

@interface AFWStockListItemViewCell : UITableViewCell
{
    CDUnknownBlockType _clickHandler;
    UIButton *_nextActionButton;
    UILabel *_firstRowTitleLabel;
    UILabel *_firstRowContentLabel;
    UILabel *_secondRowTitleLabel;
    UILabel *_secondRowContentLabel;
    UILabel *_thirdRowTitleLabel;
}

+ (id)createCellWithTableView:(id)arg1;
+ (double)cellHeight;
@property(retain, nonatomic) UILabel *thirdRowTitleLabel; // @synthesize thirdRowTitleLabel=_thirdRowTitleLabel;
@property(retain, nonatomic) UILabel *secondRowContentLabel; // @synthesize secondRowContentLabel=_secondRowContentLabel;
@property(retain, nonatomic) UILabel *secondRowTitleLabel; // @synthesize secondRowTitleLabel=_secondRowTitleLabel;
@property(retain, nonatomic) UILabel *firstRowContentLabel; // @synthesize firstRowContentLabel=_firstRowContentLabel;
@property(retain, nonatomic) UILabel *firstRowTitleLabel; // @synthesize firstRowTitleLabel=_firstRowTitleLabel;
@property(retain, nonatomic) UIButton *nextActionButton; // @synthesize nextActionButton=_nextActionButton;
@property(copy, nonatomic) CDUnknownBlockType clickHandler; // @synthesize clickHandler=_clickHandler;
- (void).cxx_destruct;
- (void)nextAction;
- (void)renderWithFundItemModel:(id)arg1;
- (void)layoutPosition;
- (void)setThemeColor;
- (void)setUpView;

@end

