//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol AlipayLifeEventManagerDelegate;

@interface AlipayLifeEventItem : NSObject
{
    id <AlipayLifeEventManagerDelegate> _eventItem;
}

@property(nonatomic) __weak id <AlipayLifeEventManagerDelegate> eventItem; // @synthesize eventItem=_eventItem;
- (void).cxx_destruct;

@end

