//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CBViewController.h"

@class NSArray, UIView;

@interface AlipayLifeCBBaseVC : CBViewController
{
    long long _enterTimeStamp;
    UIView *_loadmoreErrorView;
    NSArray *_pageVCAllCardList;
}

+ (void)replaceMonitorMethod;
@property(retain, nonatomic) NSArray *pageVCAllCardList; // @synthesize pageVCAllCardList=_pageVCAllCardList;
@property(retain, nonatomic) UIView *loadmoreErrorView; // @synthesize loadmoreErrorView=_loadmoreErrorView;
@property(nonatomic) long long enterTimeStamp; // @synthesize enterTimeStamp=_enterTimeStamp;
- (void).cxx_destruct;
- (void)updatePageCardLikeData:(id)arg1 like:(_Bool)arg2;
- (void)cardLikedNotification:(id)arg1;
- (void)nebulaLikedNotification:(id)arg1;
- (void)unregisterLikeNotification;
- (void)registerLikeNotification;
- (void)articleDetailLikedEvent:(id)arg1;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (void)handleMFWidgetEvent:(id)arg1 target:(id)arg2;
- (_Bool)handleNativeEvent:(id)arg1 target:(id)arg2;
- (void)loadCardList:(id)arg1 loadType:(long long)arg2 insertIndex:(long long)arg3 sync:(_Bool)arg4 footer:(id)arg5 callback:(CDUnknownBlockType)arg6;
- (void)onClickErrorViewRetry;
- (id)loadMoreView;
- (void)whenLoadWidgets;
- (double)preloadRate;
- (void)viewDidLoad;
- (void)dealloc;
- (id)monitorImageViews;
- (void)setMonitorImageViews:(id)arg1;
- (void)viewDidDisappear_AlipayLife:(_Bool)arg1;
- (void)viewWillAppear_AlipayLife:(_Bool)arg1;

@end

