//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, UIColor;

@interface ALPABTestMiniAppConfig : NSObject
{
    UIColor *_btnBgColor;
    UIColor *_btnTitleColor;
    UIColor *_splitColor;
    double _btnBgHeight;
    double _splitHeight;
    NSString *_exposureSpmId;
    NSString *_clickSpmId;
}

+ (id)abConfig;
@property(copy, nonatomic) NSString *clickSpmId; // @synthesize clickSpmId=_clickSpmId;
@property(copy, nonatomic) NSString *exposureSpmId; // @synthesize exposureSpmId=_exposureSpmId;
@property(nonatomic) double splitHeight; // @synthesize splitHeight=_splitHeight;
@property(nonatomic) double btnBgHeight; // @synthesize btnBgHeight=_btnBgHeight;
@property(copy, nonatomic) UIColor *splitColor; // @synthesize splitColor=_splitColor;
@property(copy, nonatomic) UIColor *btnTitleColor; // @synthesize btnTitleColor=_btnTitleColor;
@property(copy, nonatomic) UIColor *btnBgColor; // @synthesize btnBgColor=_btnBgColor;
- (void).cxx_destruct;

@end

