//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ALPApplyPassUtils : NSObject
{
}

+ (id)errorResult:(long long)arg1 resultDesc:(id)arg2;
+ (id)makeResult:(_Bool)arg1 errCode:(long long)arg2 resultDesc:(id)arg3;

@end

