//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MultiStandInfo, NSString;

@interface ALPDynamicView : UIView
{
    _Bool _isRead;
    NSString *_traceId;
    MultiStandInfo *_dynamicInfo;
    unsigned long long _dynamicState;
    UIView *_contentView;
    double _timeout;
}

@property(nonatomic) double timeout; // @synthesize timeout=_timeout;
@property(nonatomic) _Bool isRead; // @synthesize isRead=_isRead;
@property(retain, nonatomic) UIView *contentView; // @synthesize contentView=_contentView;
@property(nonatomic) unsigned long long dynamicState; // @synthesize dynamicState=_dynamicState;
@property(retain, nonatomic) MultiStandInfo *dynamicInfo; // @synthesize dynamicInfo=_dynamicInfo;
@property(copy, nonatomic) NSString *traceId; // @synthesize traceId=_traceId;
- (void).cxx_destruct;
- (id)dynamicLogParams;
- (id)readStateTitle;
- (void)onClick;
- (id)makeLogoView:(id)arg1 placeHold:(id)arg2;
- (void)reload;
- (double)timeWithJsonObj:(id)arg1;
- (id)stringWithJsonObj:(id)arg1 key:(id)arg2;
- (void)saveTagAndTime:(_Bool)arg1;
- (void)loadTagAndTime;
- (void)setDynamicInfo:(id)arg1 traceId:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

