//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "ALPPassListModel.h"

@class GroupPassManager, NSString;

@interface ALPPassTicketListModel : ALPPassListModel
{
    _Bool _hasMoreInternal;
    NSString *_groupType;
    NSString *_partnerId;
    NSString *_extInfo;
    double _latitude;
    double _longitude;
    NSString *_cityCode;
    GroupPassManager *_groupPassManager;
    long long _pageNumber;
}

@property(nonatomic) _Bool hasMoreInternal; // @synthesize hasMoreInternal=_hasMoreInternal;
@property(nonatomic) long long pageNumber; // @synthesize pageNumber=_pageNumber;
@property(retain, nonatomic) GroupPassManager *groupPassManager; // @synthesize groupPassManager=_groupPassManager;
@property(copy, nonatomic) NSString *cityCode; // @synthesize cityCode=_cityCode;
@property(nonatomic) double longitude; // @synthesize longitude=_longitude;
@property(nonatomic) double latitude; // @synthesize latitude=_latitude;
@property(copy, nonatomic) NSString *extInfo; // @synthesize extInfo=_extInfo;
@property(copy, nonatomic) NSString *partnerId; // @synthesize partnerId=_partnerId;
@property(copy, nonatomic) NSString *groupType; // @synthesize groupType=_groupType;
- (void).cxx_destruct;
- (void)convertModel;
- (_Bool)parseResponse:(id)arg1 request:(id)arg2 fromCache:(_Bool)arg3;
- (id)doRpcMethod:(id)arg1;
- (id)rpcRequest;

@end

