//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "aluLoginBaseViewController.h"

#import "ALUAccurateLoginDelegate-Protocol.h"

@class ALUAccurateViewTypeModel, NSDictionary, NSString, UIImage, UIImageView, UILabel, UIView, aluInputBox, aluOperationQueue, aluRoundHeadImage;
@protocol ALUAccurateViewDelegate;

@interface ALUAccuratePasswordViewController : aluLoginBaseViewController <ALUAccurateLoginDelegate>
{
    _Bool _hiddenLoginId;
    _Bool _isAutoRecommend;
    _Bool _duringSwitchFace;
    unsigned long long _fromType;
    unsigned long long _targetType;
    NSString *_loginid;
    NSString *_securityPhone;
    NSDictionary *_loginParamDic;
    UIImage *_transitionImage;
    aluInputBox *_loginIdInputBox;
    aluRoundHeadImage *_headImageView;
    UIView<ALUAccurateViewDelegate> *_rootView;
    NSDictionary *_dictStatus;
    ALUAccurateViewTypeModel *_currentTypeModel;
    aluOperationQueue *_operationQueue;
    UILabel *_labelAreaID;
    UILabel *_labelLoginID;
    UIImageView *_backgroundView;
}

@property(retain, nonatomic) UIImageView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) UILabel *labelLoginID; // @synthesize labelLoginID=_labelLoginID;
@property(retain, nonatomic) UILabel *labelAreaID; // @synthesize labelAreaID=_labelAreaID;
@property(nonatomic) _Bool duringSwitchFace; // @synthesize duringSwitchFace=_duringSwitchFace;
@property(retain, nonatomic) aluOperationQueue *operationQueue; // @synthesize operationQueue=_operationQueue;
@property(retain, nonatomic) ALUAccurateViewTypeModel *currentTypeModel; // @synthesize currentTypeModel=_currentTypeModel;
@property(retain, nonatomic) NSDictionary *dictStatus; // @synthesize dictStatus=_dictStatus;
@property(retain, nonatomic) UIView<ALUAccurateViewDelegate> *rootView; // @synthesize rootView=_rootView;
@property(retain, nonatomic) aluRoundHeadImage *headImageView; // @synthesize headImageView=_headImageView;
@property(retain, nonatomic) aluInputBox *loginIdInputBox; // @synthesize loginIdInputBox=_loginIdInputBox;
@property(retain, nonatomic) UIImage *transitionImage; // @synthesize transitionImage=_transitionImage;
@property(nonatomic) _Bool isAutoRecommend; // @synthesize isAutoRecommend=_isAutoRecommend;
@property(nonatomic) _Bool hiddenLoginId; // @synthesize hiddenLoginId=_hiddenLoginId;
@property(retain, nonatomic) NSDictionary *loginParamDic; // @synthesize loginParamDic=_loginParamDic;
@property(copy, nonatomic) NSString *securityPhone; // @synthesize securityPhone=_securityPhone;
@property(copy, nonatomic) NSString *loginid; // @synthesize loginid=_loginid;
@property(nonatomic) unsigned long long targetType; // @synthesize targetType=_targetType;
@property(nonatomic) unsigned long long fromType; // @synthesize fromType=_fromType;
- (void).cxx_destruct;
- (void)moreButtonAction:(id)arg1;
- (void)taobaoLogin;
- (void)cancelExchangeLoginType;
- (void)changeInputTypeButtonAction;
- (void)checkInputPWDCode:(id)arg1;
- (void)checkInputSMSCode:(id)arg1;
- (void)startSendSMS:(id)arg1;
- (void)startLaunchSMS;
- (void)launchFaceService;
- (void)startLaunchFace;
- (void)setLoginId:(id)arg1 hideLoginId:(_Bool)arg2 password:(id)arg3;
- (void)clearPassword;
- (void)changeToSMSStyle:(id)arg1;
- (void)changeToPasswordLogin:(id)arg1;
- (void)changeToPasswordStyle:(id)arg1;
- (void)faceLoginWillAppear;
- (void)hideLoginProgress;
- (void)showLoginProgress;
- (id)currentLoginId;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)createSubviews;
- (id)captureImageFromView:(id)arg1;
- (void)goback;
- (void)popTransitionView:(id)arg1;
- (void)hiddenLoginIdView:(id)arg1 fromLabel:(id)arg2;
- (void)initAnimationView:(id)arg1 targetLabel:(id)arg2;
- (void)popTransitionAnimation;
- (void)pushTransitionView:(id)arg1;
- (void)showLoginIdView:(id)arg1 targetLabel:(id)arg2;
- (void)pushTransitionAnimation;
- (void)zoomOutTransitionAnimation;
- (void)zoomInTransitionAnimation;
- (void)hideSwitchFaceView;
- (void)showSwitchFaceView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)rootViewAppear;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setupViewWithLoginType:(unsigned long long)arg1;
- (void)showAlert:(unsigned long long)arg1;
- (void)loginWithLoginType:(unsigned long long)arg1;
- (void)modifyModelData;
- (void)initModelData;
- (void)popPageAnimation:(_Bool)arg1 complete:(CDUnknownBlockType)arg2;
- (void)pushPageAnimation;
- (void)onBack;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

