//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class APMLock, CMDeviceMotion, CMMotionManager, NSOperationQueue, NSPointerArray;
@protocol OS_dispatch_queue;

@interface Ant3DIMUCenter : NSObject
{
    _Bool _gyroStarted;
    _Bool _accelerometerStarted;
    _Bool _deviceMotionStarted;
    CMDeviceMotion *_deviceMotion;
    CMMotionManager *_motionManager;
    NSOperationQueue *_queue;
    NSPointerArray *_gyroObjectArray;
    NSPointerArray *_accelerometerObjectArray;
    NSPointerArray *_deviceMotionObjectArray;
    APMLock *_imuLock;
    NSObject<OS_dispatch_queue> *_dataQueue;
}

+ (id)sharedInstance;
@property(nonatomic) _Bool deviceMotionStarted; // @synthesize deviceMotionStarted=_deviceMotionStarted;
@property(nonatomic) _Bool accelerometerStarted; // @synthesize accelerometerStarted=_accelerometerStarted;
@property(nonatomic) _Bool gyroStarted; // @synthesize gyroStarted=_gyroStarted;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *dataQueue; // @synthesize dataQueue=_dataQueue;
@property(retain, nonatomic) APMLock *imuLock; // @synthesize imuLock=_imuLock;
@property(retain, nonatomic) NSPointerArray *deviceMotionObjectArray; // @synthesize deviceMotionObjectArray=_deviceMotionObjectArray;
@property(retain, nonatomic) NSPointerArray *accelerometerObjectArray; // @synthesize accelerometerObjectArray=_accelerometerObjectArray;
@property(retain, nonatomic) NSPointerArray *gyroObjectArray; // @synthesize gyroObjectArray=_gyroObjectArray;
@property(retain, nonatomic) NSOperationQueue *queue; // @synthesize queue=_queue;
@property(retain, nonatomic) CMMotionManager *motionManager; // @synthesize motionManager=_motionManager;
@property(readonly) CMDeviceMotion *deviceMotion; // @synthesize deviceMotion=_deviceMotion;
- (void).cxx_destruct;
- (long long)indexInArray:(id)arg1 withObject:(id)arg2;
- (void)stopDeviceMotionUpdatesWithObject:(id)arg1;
- (void)startDeviceMotionUpdatesWithObject:(id)arg1;
- (void)stopAccelerometerUpdatesWithObject:(id)arg1;
- (void)startAccelerometerUpdatesWithObject:(id)arg1;
- (void)stopGyroUpdatesWithObject:(id)arg1;
- (void)startGyroUpdatesWithObject:(id)arg1;
- (id)init;

@end

