//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ATUploadRequest, NSArray, NSString;

@interface AntRealtimeLogItem : NSObject
{
    NSString *_bizType;
    NSArray *_logs;
}

@property(retain, nonatomic) NSArray *logs; // @synthesize logs=_logs;
@property(retain, nonatomic) NSString *bizType; // @synthesize bizType=_bizType;
- (void).cxx_destruct;
@property(retain, nonatomic) ATUploadRequest *uploadRequest;

@end

