//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSDictionary, NSString;

@interface ANXAccountEntity : NSObject
{
    _Bool _isLogin;
    _Bool _isNormalLockScreen;
    NSString *_userId;
    NSString *_utdid;
    NSArray *_cookies;
    NSDictionary *_autoLogin;
}

@property(retain, nonatomic) NSDictionary *autoLogin; // @synthesize autoLogin=_autoLogin;
@property(retain, nonatomic) NSArray *cookies; // @synthesize cookies=_cookies;
@property(retain, nonatomic) NSString *utdid; // @synthesize utdid=_utdid;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(nonatomic) _Bool isNormalLockScreen; // @synthesize isNormalLockScreen=_isNormalLockScreen;
@property(nonatomic) _Bool isLogin; // @synthesize isLogin=_isLogin;
- (void).cxx_destruct;
- (id)accountStoreParams;

@end

