//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ANXH5SchemeAuthModel, ANXNeedUpdateSchemeModel;

@interface ANXH5SchemeHandler : NSObject
{
    ANXH5SchemeAuthModel *_authModel;
    ANXNeedUpdateSchemeModel *_updateModel;
}

@property(retain, nonatomic) ANXNeedUpdateSchemeModel *updateModel; // @synthesize updateModel=_updateModel;
@property(retain, nonatomic) ANXH5SchemeAuthModel *authModel; // @synthesize authModel=_authModel;
- (void).cxx_destruct;
- (void)handle;
- (id)initWithLaunchOptions:(id)arg1;

@end

