//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ANXWidgetSchemeBarcodeModel, ANXWidgetSchemeBuscodeModel;

@interface ANXWidgetSchemeHandler : NSObject
{
    ANXWidgetSchemeBarcodeModel *_barcodeModel;
    ANXWidgetSchemeBuscodeModel *_buscodeModel;
}

@property(retain, nonatomic) ANXWidgetSchemeBuscodeModel *buscodeModel; // @synthesize buscodeModel=_buscodeModel;
@property(retain, nonatomic) ANXWidgetSchemeBarcodeModel *barcodeModel; // @synthesize barcodeModel=_barcodeModel;
- (void).cxx_destruct;
- (void)handle;
- (id)initWithLaunchOptions:(id)arg1;

@end

