//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSLock, NSString;

@interface APAICodeFinder : NSObject
{
    _Bool _isQRFinderSwitchOpen;
    _Bool _isQRFinderUIImgSwitchOpen;
    _Bool _isONEDFinderSwitchOpen;
    _Bool _isQRFinderAlReady;
    _Bool _isONEDFinderAlReady;
    _Bool _shouldRelease;
    NSString *_xNNQRModelId;
    NSString *_xNNQRModelMd5;
    NSString *_xnnQRConfig;
    NSString *_qr_modelURL;
    NSString *_xNNONEDModelId;
    NSString *_xNNONEDModelMd5;
    NSString *_xnnONEDConfig;
    NSString *_oned_modelURL;
    NSLock *_mLock;
    long long _frameCount;
    long long _memThreold;
}

+ (id)sharedInstance;
@property(nonatomic) long long memThreold; // @synthesize memThreold=_memThreold;
@property(nonatomic) long long frameCount; // @synthesize frameCount=_frameCount;
@property _Bool shouldRelease; // @synthesize shouldRelease=_shouldRelease;
@property(retain, nonatomic) NSLock *mLock; // @synthesize mLock=_mLock;
@property(retain, nonatomic) NSString *oned_modelURL; // @synthesize oned_modelURL=_oned_modelURL;
@property(retain, nonatomic) NSString *xnnONEDConfig; // @synthesize xnnONEDConfig=_xnnONEDConfig;
@property(retain, nonatomic) NSString *xNNONEDModelMd5; // @synthesize xNNONEDModelMd5=_xNNONEDModelMd5;
@property(retain, nonatomic) NSString *xNNONEDModelId; // @synthesize xNNONEDModelId=_xNNONEDModelId;
@property(retain, nonatomic) NSString *qr_modelURL; // @synthesize qr_modelURL=_qr_modelURL;
@property(retain, nonatomic) NSString *xnnQRConfig; // @synthesize xnnQRConfig=_xnnQRConfig;
@property(retain, nonatomic) NSString *xNNQRModelMd5; // @synthesize xNNQRModelMd5=_xNNQRModelMd5;
@property(retain, nonatomic) NSString *xNNQRModelId; // @synthesize xNNQRModelId=_xNNQRModelId;
@property _Bool isONEDFinderAlReady; // @synthesize isONEDFinderAlReady=_isONEDFinderAlReady;
@property _Bool isQRFinderAlReady; // @synthesize isQRFinderAlReady=_isQRFinderAlReady;
@property(nonatomic) _Bool isONEDFinderSwitchOpen; // @synthesize isONEDFinderSwitchOpen=_isONEDFinderSwitchOpen;
@property(nonatomic) _Bool isQRFinderUIImgSwitchOpen; // @synthesize isQRFinderUIImgSwitchOpen=_isQRFinderUIImgSwitchOpen;
@property(nonatomic) _Bool isQRFinderSwitchOpen; // @synthesize isQRFinderSwitchOpen=_isQRFinderSwitchOpen;
- (void).cxx_destruct;
- (void)aiCodeFinderWrapperInit:(int)arg1;
- (int)checkAndDownloadXNNModel:(id)arg1 modelMd5:(id)arg2 type:(id)arg3;
- (_Bool)local_loadDylibInNativeWithName:(id)arg1;
- (_Bool)hasEnoughMemory;
- (void)releaseResource;
- (struct _AIFinderResult *)findCodeWithAI:(CDStruct_b0c48cec *)arg1 mode:(int)arg2;
- (void)loadConfig;
- (id)init;

@end

