//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APCombinedMultiSelectViewController.h"

#import "APTopHintViewDelegate-Protocol.h"

@class APTopHintView, AUNetErrorView, NSArray, NSMutableDictionary, NSString, UIView;

@interface APContactTagMultiSelectViewController : APCombinedMultiSelectViewController <APTopHintViewDelegate>
{
    _Bool _didClickBtn;
    double _topHintViewHeight;
    NSMutableDictionary *_userTagDict;
    NSString *_queryID;
    NSString *_adviseText;
    AUNetErrorView *_netErrorView;
    UIView *_emptyPageLoadingView;
    NSString *_preFriendText;
}

@property(retain, nonatomic) NSString *preFriendText; // @synthesize preFriendText=_preFriendText;
@property(retain, nonatomic) UIView *emptyPageLoadingView; // @synthesize emptyPageLoadingView=_emptyPageLoadingView;
@property(retain, nonatomic) AUNetErrorView *netErrorView; // @synthesize netErrorView=_netErrorView;
@property(retain, nonatomic) NSString *adviseText; // @synthesize adviseText=_adviseText;
@property(retain, nonatomic) NSString *queryID; // @synthesize queryID=_queryID;
@property(nonatomic) _Bool didClickBtn; // @synthesize didClickBtn=_didClickBtn;
@property(retain, nonatomic) NSMutableDictionary *userTagDict; // @synthesize userTagDict=_userTagDict;
@property(nonatomic) double topHintViewHeight; // @synthesize topHintViewHeight=_topHintViewHeight;
- (void).cxx_destruct;
- (void)didReceiveMemoryWarning;
- (id)getSelectSPMID;
- (id)getSPMID;
- (id)secondaryDataIndexLeftIconNamesInCommonView:(id)arg1;
- (id)secondaryDataIndexIconNamesInCommonView:(id)arg1;
- (id)secondaryDataTitlesInCommonView:(id)arg1;
- (id)secondaryDataInCommonView:(id)arg1;
- (id)commonView:(id)arg1 globelSearchName:(id)arg2 globeSearchMatchResult:(id)arg3;
- (void)commonView:(id)arg1 configCell:(id)arg2 item:(id)arg3;
- (id)cellClassNameInCommonView:(id)arg1 item:(id)arg2;
- (void)reloadUI;
- (_Bool)shouldShowTopHintView;
- (id)customIntroViewInCommonView:(id)arg1;
- (void)tapRightBtn:(id)arg1;
- (void)didFinishLoadContactDict;
- (id)makeUserTagInfoListWithUserInfo:(id)arg1 userIdTagList:(id)arg2;
- (void)mergeUserTagInfoWithContactDict:(id)arg1;
- (void)pressedNetErrorView;
- (void)showNetErrorView:(_Bool)arg1;
- (void)showLoadingView:(_Bool)arg1;
- (void)fetchTagInfoAsync;
- (void)viewDidLoad;
- (void)adjustFrames;
- (void)configWithDict:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) int friendSelectionType;
@property(readonly) unsigned long long hash;
@property(retain, nonatomic) NSArray *preFriend;
@property(readonly) Class superclass;
@property(retain, nonatomic) APTopHintView *topHintView;

@end

