//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface APConfigDataManager : NSObject
{
}

+ (_Bool)saveConfigDictionaryToDB:(id)arg1 forKey:(id)arg2 business:(id)arg3;
+ (id)getConfigDictionaryFromDBForKey:(id)arg1 business:(id)arg2;
+ (void)saveFlagForKey:(id)arg1;
+ (_Bool)hasFlagForKey:(id)arg1;
+ (id)getConfig;
+ (_Bool)saveConfig:(id)arg1;

@end

