//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface APEdgeUnicodeTransLogObject : NSObject
{
    NSString *_length;
    NSString *_expend;
}

@property(retain, nonatomic) NSString *expend; // @synthesize expend=_expend;
@property(retain, nonatomic) NSString *length; // @synthesize length=_length;
- (void).cxx_destruct;
- (id)getMap;

@end

