//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSMutableArray, NSString;

@protocol APGSuggestViewControllerProtocol <NSObject>
@property(nonatomic) _Bool canSearchSuggest;
@property(retain, nonatomic) NSString *currentSearchKeyword;
@property(retain) NSMutableArray *dataSource;
- (void)clearDataSource;
- (void)querySuggestionWithText:(NSString *)arg1 actionSrc:(NSString *)arg2;
@end

