//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface APLogAdditions : NSObject
{
    NSString *_deviceModel;
    NSString *_language;
    NSString *_userID;
    NSString *_clientVersion;
    long long _maximumSizeOfLog;
    long long _maximumNumberOfLogFiles;
    long long _maximumLengthOfLine;
}

+ (id)sharedInstance;
@property(nonatomic) long long maximumLengthOfLine; // @synthesize maximumLengthOfLine=_maximumLengthOfLine;
@property(nonatomic) long long maximumNumberOfLogFiles; // @synthesize maximumNumberOfLogFiles=_maximumNumberOfLogFiles;
@property(nonatomic) long long maximumSizeOfLog; // @synthesize maximumSizeOfLog=_maximumSizeOfLog;
@property(retain, nonatomic) NSString *clientVersion; // @synthesize clientVersion=_clientVersion;
@property(retain, nonatomic) NSString *userID; // @synthesize userID=_userID;
@property(retain, nonatomic) NSString *language; // @synthesize language=_language;
@property(retain, nonatomic) NSString *deviceModel; // @synthesize deviceModel=_deviceModel;
- (void).cxx_destruct;
- (_Bool)privacyAuthed;
- (id)idfa;
- (id)getBrandNewUUID;
- (void)logToFile:(id)arg1;
- (id)defaultUploadLogTypes;
@property(retain, nonatomic) NSString *platformID;
@property(retain, nonatomic) NSString *configServerURL;
@property(retain, nonatomic) NSString *logServerURL;
@property(readonly, nonatomic) NSString *clientID;
@property(readonly, nonatomic) NSString *UTDID;
@property(readonly, nonatomic) NSString *UUID;
- (_Bool)privacyAuthed;
- (id)idfa;
- (void)logToFile:(id)arg1;
- (id)defaultUploadLogTypes;

@end

