//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ALPMemoryInfo, NSMutableArray, NSRecursiveLock, NSTimer;

@interface APMemoryMonitor : NSObject
{
    NSMutableArray *_trackList;
    ALPMemoryInfo *_latestMemoryInfo;
    NSRecursiveLock *_memoryOpLock;
    NSRecursiveLock *_actionOpLock;
    NSRecursiveLock *_reportOpLock;
    NSTimer *_indicatorTimer;
    id _memIndicator;
}

+ (id)memoryTrackerLogArray;
+ (id)memoryTrackerLog;
+ (id)sharedInstance;
+ (void)load;
@property(retain, nonatomic) id memIndicator; // @synthesize memIndicator=_memIndicator;
@property(retain, nonatomic) NSTimer *indicatorTimer; // @synthesize indicatorTimer=_indicatorTimer;
@property(retain, nonatomic) NSRecursiveLock *reportOpLock; // @synthesize reportOpLock=_reportOpLock;
@property(retain, nonatomic) NSRecursiveLock *actionOpLock; // @synthesize actionOpLock=_actionOpLock;
@property(retain, nonatomic) NSRecursiveLock *memoryOpLock; // @synthesize memoryOpLock=_memoryOpLock;
@property(retain, nonatomic) ALPMemoryInfo *latestMemoryInfo; // @synthesize latestMemoryInfo=_latestMemoryInfo;
@property(retain, nonatomic) NSMutableArray *trackList; // @synthesize trackList=_trackList;
- (void).cxx_destruct;
- (_Bool)shouldUpLog:(id)arg1 interval:(long long)arg2;
- (void)reportThreadInfo:(unsigned long long)arg1 stackFrames:(id)arg2;
- (id)latestMemoryEvaluation;
- (void)report:(id)arg1;
- (void)stopMonitor;
- (void)trackVCByNotification:(id)arg1 action:(unsigned long long)arg2;
- (void)trackAppByNotification:(id)arg1 action:(unsigned long long)arg2;
- (void)setUpIndicator;
- (void)startBigMallocMonitor;
- (void)startOOMMonitor;
- (id)init;

@end

