//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "APMConfigUpdateProtocol-Protocol.h"

@class NSArray, NSDictionary, NSString;

@interface APMH5Config : NSObject <APMConfigUpdateProtocol>
{
    _Bool _enableAYUV;
    _Bool _enableAYUVCrop;
    _Bool _enableConvergence;
    _Bool _enableOptimize;
    NSArray *_h5UncompatibleHttpHeaders;
    NSArray *_h5UncompatibleContentTypes;
    NSArray *_h5BlackFeaturePoints;
    NSDictionary *_urlAftsCdnConfig;
    NSArray *_urlAftsCdnBlackDomainList;
    NSArray *_urlAftsCdnImageSuffixList;
}

+ (id)shareInstance;
@property(copy, nonatomic) NSArray *urlAftsCdnImageSuffixList; // @synthesize urlAftsCdnImageSuffixList=_urlAftsCdnImageSuffixList;
@property(copy, nonatomic) NSArray *urlAftsCdnBlackDomainList; // @synthesize urlAftsCdnBlackDomainList=_urlAftsCdnBlackDomainList;
@property(copy, nonatomic) NSDictionary *urlAftsCdnConfig; // @synthesize urlAftsCdnConfig=_urlAftsCdnConfig;
@property(copy, nonatomic) NSArray *h5BlackFeaturePoints; // @synthesize h5BlackFeaturePoints=_h5BlackFeaturePoints;
@property(copy, nonatomic) NSArray *h5UncompatibleContentTypes; // @synthesize h5UncompatibleContentTypes=_h5UncompatibleContentTypes;
@property(copy, nonatomic) NSArray *h5UncompatibleHttpHeaders; // @synthesize h5UncompatibleHttpHeaders=_h5UncompatibleHttpHeaders;
@property(nonatomic) _Bool enableOptimize; // @synthesize enableOptimize=_enableOptimize;
@property(nonatomic) _Bool enableConvergence; // @synthesize enableConvergence=_enableConvergence;
@property(nonatomic) _Bool enableAYUVCrop; // @synthesize enableAYUVCrop=_enableAYUVCrop;
@property(nonatomic) _Bool enableAYUV; // @synthesize enableAYUV=_enableAYUV;
- (void).cxx_destruct;
- (_Bool)bizType:(id)arg1 inList:(id)arg2;
- (_Bool)enableAftsCDNWithUrl:(id)arg1 bizType:(id)arg2;
- (void)parseConfig:(id)arg1;
- (void)configDidUpdate:(id)arg1 key:(id)arg2;
- (void)doInit;
- (void)dealloc;
- (id)initPrivate;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

