//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@interface APMOCRMaskView : UIView
{
    double _maksAlpha;
    struct CGRect _transparentFrame;
}

@property(nonatomic) double maksAlpha; // @synthesize maksAlpha=_maksAlpha;
@property(nonatomic) struct CGRect transparentFrame; // @synthesize transparentFrame=_transparentFrame;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1 transparentFrame:(struct CGRect)arg2 maksAlpha:(double)arg3;

@end

