//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APBaseMapViewController.h"

#import "AMapSearchDelegate-Protocol.h"
#import "UIActionSheetDelegate-Protocol.h"

@class AMapSearchAPI, NSArray, NSString;
@protocol MAAnnotation;

@interface APNaviViewController : APBaseMapViewController <UIActionSheetDelegate, AMapSearchDelegate>
{
    NSArray *config;
    id <MAAnnotation> currentAnnotation;
    NSString *_currentAddress;
    _Bool _firstUpdateLocation;
    id <MAAnnotation> _originAnnotation;
    id <MAAnnotation> _destinationAnnotation;
    NSArray *_buttonHiddenList;
    AMapSearchAPI *_search;
}

@property(retain, nonatomic) AMapSearchAPI *search; // @synthesize search=_search;
@property(retain, nonatomic) NSArray *buttonHiddenList; // @synthesize buttonHiddenList=_buttonHiddenList;
@property(retain, nonatomic) id <MAAnnotation> destinationAnnotation; // @synthesize destinationAnnotation=_destinationAnnotation;
@property(retain, nonatomic) id <MAAnnotation> originAnnotation; // @synthesize originAnnotation=_originAnnotation;
@property(nonatomic) _Bool firstUpdateLocation; // @synthesize firstUpdateLocation=_firstUpdateLocation;
- (void).cxx_destruct;
- (void)showUserLocation;
- (id)appID;
- (void)getCurrentAddress;
- (void)showAuthorizationTip;
- (void)setMapViewForShowAnnotations:(id)arg1;
- (void)mapView:(id)arg1 didFailToLocateUserWithError:(id)arg2;
- (id)buildSchemeUrl:(id)arg1;
- (void)actionSheet:(id)arg1 didDismissWithButtonIndex:(long long)arg2;
- (void)mapView:(id)arg1 annotationView:(id)arg2 calloutAccessoryControlTapped:(id)arg3;
- (void)viewDidLoad;
- (void)moveToLocation;
- (void)onReGeocodeSearchDone:(id)arg1 response:(id)arg2;
- (void)mapView:(id)arg1 didUpdateUserLocation:(id)arg2 updatingLocation:(_Bool)arg3;
- (void)mapView:(id)arg1 didAddAnnotationViews:(id)arg2;
- (id)mapView:(id)arg1 viewForAnnotation:(id)arg2;
- (_Bool)isZoomLevelValid:(double)arg1;
- (void)startSearching;
- (void)setLaunchOptions:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

