//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APAlertView.h"

#import "UIAlertViewDelegate-Protocol.h"

@class NSString;

@interface APPassAlertView : APAlertView <UIAlertViewDelegate>
{
    CDUnknownBlockType _cancelBlock;
    CDUnknownBlockType _confirmBlock;
}

+ (id)showAlertViewWithTitle:(id)arg1 message:(id)arg2 cancelButtonTitle:(id)arg3 cancelBlock:(CDUnknownBlockType)arg4 confirmButtonTitle:(id)arg5 confirmBlock:(CDUnknownBlockType)arg6;
@property(copy, nonatomic) CDUnknownBlockType confirmBlock; // @synthesize confirmBlock=_confirmBlock;
@property(copy, nonatomic) CDUnknownBlockType cancelBlock; // @synthesize cancelBlock=_cancelBlock;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

