//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "APProfileService-Protocol.h"

@class NSString;

@interface APProfileServiceIml : NSObject <APProfileService>
{
}

- (void)getSelfProfileForPrivacyScene;
- (void)dealRPCSuccess:(id)arg1 data:(id)arg2;
- (void)sendingStatusChanged:(id)arg1;
- (void)shareCardNotification:(id)arg1;
- (id)getFriendsConfigController;
- (void)setContactRemark:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (id)getPersonalSloganWithCallback:(CDUnknownBlockType)arg1;
- (id)getCachedPersonalSlogan;
- (void)setPersonalSloganWithCallback:(CDUnknownBlockType)arg1;
- (void)dealloc;
- (void)start;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

