//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AUTableView.h"

@interface APRecentTableView : AUTableView
{
    _Bool _didScroll;
    _Bool _enableEXHALL;
}

@property(nonatomic) _Bool enableEXHALL; // @synthesize enableEXHALL=_enableEXHALL;
@property(nonatomic) _Bool didScroll; // @synthesize didScroll=_didScroll;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;

@end

