//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSArray, NSMutableArray, NSString, UIButton, UICollectionView, UIImageView, UILabel;
@protocol APRecentFoldLifeAccountsSelectDelegate;

@interface APRecentFoldLifeAccountsView : UIView <UICollectionViewDataSource, UICollectionViewDelegate>
{
    id <APRecentFoldLifeAccountsSelectDelegate> _foldLifeDelegate;
    UILabel *_lifeTitleLabel;
    UILabel *_lifeSubTitleLabel;
    UICollectionView *_lifeAccountsView;
    NSArray *_lifeAccountsArr;
    NSMutableArray *_selectedItems;
    NSMutableArray *_defaultSelectedItems;
    UIImageView *_guideView;
    UIView *_selectAllView;
    UIButton *_selectAllBtn;
}

@property(retain, nonatomic) UIButton *selectAllBtn; // @synthesize selectAllBtn=_selectAllBtn;
@property(retain, nonatomic) UIView *selectAllView; // @synthesize selectAllView=_selectAllView;
@property(retain, nonatomic) UIImageView *guideView; // @synthesize guideView=_guideView;
@property(retain, nonatomic) NSMutableArray *defaultSelectedItems; // @synthesize defaultSelectedItems=_defaultSelectedItems;
@property(retain, nonatomic) NSMutableArray *selectedItems; // @synthesize selectedItems=_selectedItems;
@property(retain, nonatomic) NSArray *lifeAccountsArr; // @synthesize lifeAccountsArr=_lifeAccountsArr;
@property(retain, nonatomic) UICollectionView *lifeAccountsView; // @synthesize lifeAccountsView=_lifeAccountsView;
@property(retain, nonatomic) UILabel *lifeSubTitleLabel; // @synthesize lifeSubTitleLabel=_lifeSubTitleLabel;
@property(retain, nonatomic) UILabel *lifeTitleLabel; // @synthesize lifeTitleLabel=_lifeTitleLabel;
@property(nonatomic) __weak id <APRecentFoldLifeAccountsSelectDelegate> foldLifeDelegate; // @synthesize foldLifeDelegate=_foldLifeDelegate;
- (void).cxx_destruct;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)selectAllDidClicked:(id)arg1;
- (void)setupFoldAccountsView:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1 withParameters:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

