//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class APShortcutsPhoneViewModel, UIImageView, UILabel;

@interface APShortcutsPhoneView : UIView
{
    _Bool _showAnimating;
    APShortcutsPhoneViewModel *_phoneMode;
    UIImageView *_appIcon;
    UILabel *_appName;
    UIImageView *_scanIcon;
    UILabel *_scanName;
    UIImageView *_payIcon;
    UILabel *_payName;
    UIImageView *_collectIcon;
    UILabel *_collectName;
    UIImageView *_pressTip;
    UIImageView *_paycode;
    UIImageView *_paycodeTab;
    UIImageView *_widgetTab;
    UIView *_tapCircle;
    struct CGRect _screenshotRect;
}

@property(retain, nonatomic) UIView *tapCircle; // @synthesize tapCircle=_tapCircle;
@property(nonatomic) struct CGRect screenshotRect; // @synthesize screenshotRect=_screenshotRect;
@property(retain, nonatomic) UIImageView *widgetTab; // @synthesize widgetTab=_widgetTab;
@property(retain, nonatomic) UIImageView *paycodeTab; // @synthesize paycodeTab=_paycodeTab;
@property(retain, nonatomic) UIImageView *paycode; // @synthesize paycode=_paycode;
@property(retain, nonatomic) UIImageView *pressTip; // @synthesize pressTip=_pressTip;
@property(retain, nonatomic) UILabel *collectName; // @synthesize collectName=_collectName;
@property(retain, nonatomic) UIImageView *collectIcon; // @synthesize collectIcon=_collectIcon;
@property(retain, nonatomic) UILabel *payName; // @synthesize payName=_payName;
@property(retain, nonatomic) UIImageView *payIcon; // @synthesize payIcon=_payIcon;
@property(retain, nonatomic) UILabel *scanName; // @synthesize scanName=_scanName;
@property(retain, nonatomic) UIImageView *scanIcon; // @synthesize scanIcon=_scanIcon;
@property(retain, nonatomic) UILabel *appName; // @synthesize appName=_appName;
@property(retain, nonatomic) UIImageView *appIcon; // @synthesize appIcon=_appIcon;
@property(nonatomic) _Bool showAnimating; // @synthesize showAnimating=_showAnimating;
@property(retain, nonatomic) APShortcutsPhoneViewModel *phoneMode; // @synthesize phoneMode=_phoneMode;
- (void).cxx_destruct;
- (void)runDesktopAnimation;
- (void)runForceTouchAnimation;
- (void)runWidgetAnimation;
- (void)highlightBorder:(_Bool)arg1;
- (void)cancelAllAnimations;
- (id)creatCircleShapWithPostion:(struct CGPoint)arg1 radius:(double)arg2;
- (void)layoutDesktop;
- (void)layoutForceTouchView;
- (void)layoutWidgetView;
- (void)initialSubView;
- (void)drawRect:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

