//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewCell.h>

@class APSocialGTDCardDetailView, AUButton, AULabel, AUView, NSDictionary;
@protocol APSocialGTDCardCellDelegate;

@interface APSocialGTDCardCell : UITableViewCell
{
    id <APSocialGTDCardCellDelegate> _delegate;
    AULabel *_titleLabel;
    APSocialGTDCardDetailView *_detailView1;
    APSocialGTDCardDetailView *_detailView2;
    APSocialGTDCardDetailView *_detailView3;
    AUButton *_secondaryButton;
    AUButton *_mainButton;
    AUView *_btnSeperator;
    AUView *_seperatorLine;
    AUView *_placeholderView;
    NSDictionary *_cardInfo;
}

+ (double)placeholderHeight;
+ (double)heightOfData:(id)arg1;
+ (double)defaultHeight;
+ (struct CGSize)sizeForTitleLabel:(id)arg1;
@property(retain, nonatomic) NSDictionary *cardInfo; // @synthesize cardInfo=_cardInfo;
@property(retain, nonatomic) AUView *placeholderView; // @synthesize placeholderView=_placeholderView;
@property(retain, nonatomic) AUView *seperatorLine; // @synthesize seperatorLine=_seperatorLine;
@property(retain, nonatomic) AUView *btnSeperator; // @synthesize btnSeperator=_btnSeperator;
@property(retain, nonatomic) AUButton *mainButton; // @synthesize mainButton=_mainButton;
@property(retain, nonatomic) AUButton *secondaryButton; // @synthesize secondaryButton=_secondaryButton;
@property(retain, nonatomic) APSocialGTDCardDetailView *detailView3; // @synthesize detailView3=_detailView3;
@property(retain, nonatomic) APSocialGTDCardDetailView *detailView2; // @synthesize detailView2=_detailView2;
@property(retain, nonatomic) APSocialGTDCardDetailView *detailView1; // @synthesize detailView1=_detailView1;
@property(retain, nonatomic) AULabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(nonatomic) __weak id <APSocialGTDCardCellDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)onClickSecondaryButton:(id)arg1;
- (void)onClickMainButton:(id)arg1;
- (void)configGtdData:(id)arg1;
- (id)extInfos;
- (void)setPlaceholderHidden:(_Bool)arg1;
- (void)layoutSubviews;
- (void)setupSubviews;
- (void)awakeFromNib;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

