//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface APStepStorage : NSObject
{
}

+ (void)setTipControlShowDate:(id)arg1 clickData:(id)arg2 appId:(id)arg3 type:(id)arg4;
+ (void)setTipControlClickData:(id)arg1 appId:(id)arg2 type:(id)arg3;
+ (void)setTipControlShowDate:(id)arg1 appId:(id)arg2 type:(id)arg3;
+ (id)tipControl:(id)arg1 type:(id)arg2;
+ (id)lastTimezone;
+ (long long)lastUploadSteps;
+ (id)lastUploadDate;
+ (id)lastUploadData;
+ (_Bool)isCMAuthAlertPrompted;
+ (_Bool)isWalkingUser;

@end

