//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;

@interface APTransNoticeBarView : UIView
{
    UILabel *_marqueeLabel;
    UIImageView *_icon;
}

@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) UILabel *marqueeLabel; // @synthesize marqueeLabel=_marqueeLabel;
- (void).cxx_destruct;
- (void)startMarqueeAnimation;
- (void)setupViews:(id)arg1;
- (id)initWithSuperView:(id)arg1 y:(long long)arg2 title:(id)arg3;

@end

