//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class APTSDBConfig, APTSDBConnectPool, APTSDBOptions, APTSDatabase, NSDateFormatter, NSOperationQueue, NSTimeZone;
@protocol OS_dispatch_semaphore;

@interface APTSDBBizManager : NSObject
{
    NSObject<OS_dispatch_semaphore> *proxy_signal;
    NSObject<OS_dispatch_semaphore> *db_update_signal;
    unsigned long long maxOffset;
    unsigned long long minOffset;
    _Bool _inBlackList;
    int _proxyCount;
    APTSDBConfig *_config;
    NSTimeZone *_timeZone;
    APTSDBOptions *_opts;
    NSOperationQueue *_serial_queue;
    APTSDatabase *_appendDB;
    NSDateFormatter *_dateFormatter;
    APTSDBConnectPool *_connectPool;
}

@property(retain, nonatomic) APTSDBConnectPool *connectPool; // @synthesize connectPool=_connectPool;
@property(nonatomic) _Bool inBlackList; // @synthesize inBlackList=_inBlackList;
@property(retain, nonatomic) NSDateFormatter *dateFormatter; // @synthesize dateFormatter=_dateFormatter;
@property(retain, nonatomic) APTSDatabase *appendDB; // @synthesize appendDB=_appendDB;
@property(nonatomic) int proxyCount; // @synthesize proxyCount=_proxyCount;
@property(retain, nonatomic) NSOperationQueue *serial_queue; // @synthesize serial_queue=_serial_queue;
@property(retain, nonatomic) APTSDBOptions *opts; // @synthesize opts=_opts;
@property(readonly, nonatomic) NSTimeZone *timeZone; // @synthesize timeZone=_timeZone;
@property(retain, nonatomic) APTSDBConfig *config; // @synthesize config=_config;
- (void).cxx_destruct;
- (void)dbUnlock;
- (void)dbLock;
- (void)proxyUnlock;
- (void)proxyLock;
- (_Bool)appendPoint:(id)arg1 viaMissTimeStamp:(double)arg2;
- (id)getTimeFromTimeStamp:(double)arg1;
- (_Bool)appendPoint:(id)arg1 timeStamp:(double)arg2;
- (id)getDatabaseListFrom:(double)arg1 to:(double)arg2 ascend:(_Bool)arg3;
- (id)queryWithFilter:(id)arg1 processor:(CDUnknownBlockType)arg2;
- (id)queryRecordsViaFilter:(id)arg1;
- (_Bool)appendPoint:(id)arg1;
- (void)queryRecordsViaFilter:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)appendPoint:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)tryClose;
- (id)getAgent;
- (void)delete;
- (void)close;
- (void)dealloc;
- (id)initWithConfig:(id)arg1 options:(id)arg2;

@end

