//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface APWaspSettingModel : NSObject
{
    NSString *_introduceDetailURL;
    NSString *_rankingListURL;
    NSString *_privacyPolicyURL;
    NSString *_rainkingListTitle;
    NSString *_privacyPolicyTitle;
}

@property(retain, nonatomic) NSString *privacyPolicyTitle; // @synthesize privacyPolicyTitle=_privacyPolicyTitle;
@property(retain, nonatomic) NSString *rainkingListTitle; // @synthesize rainkingListTitle=_rainkingListTitle;
@property(retain, nonatomic) NSString *privacyPolicyURL; // @synthesize privacyPolicyURL=_privacyPolicyURL;
@property(retain, nonatomic) NSString *rankingListURL; // @synthesize rankingListURL=_rankingListURL;
@property(retain, nonatomic) NSString *introduceDetailURL; // @synthesize introduceDetailURL=_introduceDetailURL;
- (void).cxx_destruct;
- (id)init;

@end

