//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface APWaspCaseResult : NSObject
{
    _Bool _totalResult;
    _Bool _hasCrash;
    _Bool _hasPerfIssue;
    NSString *_totalReason;
    NSString *_crashDetail;
    NSString *_perfIssueDetail;
    NSString *_otherResult;
}

@property(retain, nonatomic) NSString *otherResult; // @synthesize otherResult=_otherResult;
@property(retain, nonatomic) NSString *perfIssueDetail; // @synthesize perfIssueDetail=_perfIssueDetail;
@property(retain, nonatomic) NSString *crashDetail; // @synthesize crashDetail=_crashDetail;
@property(retain, nonatomic) NSString *totalReason; // @synthesize totalReason=_totalReason;
@property(nonatomic) _Bool hasPerfIssue; // @synthesize hasPerfIssue=_hasPerfIssue;
@property(nonatomic) _Bool hasCrash; // @synthesize hasCrash=_hasCrash;
@property(nonatomic) _Bool totalResult; // @synthesize totalResult=_totalResult;
- (void).cxx_destruct;
- (id)init;

@end

