//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ARScanSpCodeManager : NSObject
{
    NSString *_cfgStr;
    NSString *_cfgMd5;
    _Bool _engineReady;
    _Bool _engineEnabled;
    _Bool _userEmbedCfg;
    double _clipRatio;
}

+ (void)mainLinkLog:(id)arg1 extra:(id)arg2;
- (void).cxx_destruct;
- (void)destory;
- (void)tryInitEngine;
- (id)decodeSpCode:(struct __CVBuffer *)arg1;
- (void)setDecodeEnabled:(_Bool)arg1;
- (void)initScanEngine:(id)arg1 md5:(id)arg2;
- (id)loadEmbedConfig;
- (void)loadRemoteConfig:(id)arg1;
- (void)startLoadConfig;
- (void)resetCfg;
- (id)fileStorePath:(id)arg1 key:(id)arg2;
- (_Bool)fileExist:(id)arg1;
- (id)downloadPath;
- (id)MD5:(id)arg1;

@end

