//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "ARTVCRealtimeStatsProtocol-Protocol.h"

@class NSMutableDictionary, NSString;
@protocol ARTVCRealtimeStatsProtocol, ARTVCStatsSenderProtocol;

@interface ARTVCStatsManager : NSObject <ARTVCRealtimeStatsProtocol>
{
    id <ARTVCStatsSenderProtocol> _statsSender;
    id <ARTVCRealtimeStatsProtocol> _delegate;
    NSMutableDictionary *_statsProcessors;
}

@property(retain, nonatomic) NSMutableDictionary *statsProcessors; // @synthesize statsProcessors=_statsProcessors;
@property(nonatomic) __weak id <ARTVCRealtimeStatsProtocol> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <ARTVCStatsSenderProtocol> statsSender; // @synthesize statsSender=_statsSender;
- (void).cxx_destruct;
- (void)sendRealtimeStatsWithIdentifier:(id)arg1 report:(id)arg2;
- (void)queryRealtimeStatsWithIdentifier:(id)arg1 complete:(CDUnknownBlockType)arg2;
- (void)sendStatisticReportMessage:(id)arg1 identifier:(id)arg2;
- (void)uploadStatsAfterHangupWithIdentifier:(id)arg1 stats:(id)arg2;
- (void)stopRealtimeStatsWithIdentifier:(id)arg1;
- (void)startRealtimeStatsWithIdentifier:(id)arg1 configuration:(id)arg2;
- (void)createRealtimeProcessorWithIdentifier:(id)arg1;
- (void)dealloc;
- (id)initWithDelegate:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

