//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary, NSRecursiveLock;

@interface ATAppenderMgr : NSObject
{
    double _lastPeriodCheckTime;
    NSMutableDictionary *_fileCreateTimes;
    NSMutableDictionary *_aps;
    NSRecursiveLock *_lock;
}

@property(retain, nonatomic) NSRecursiveLock *lock; // @synthesize lock=_lock;
@property(retain, nonatomic) NSMutableDictionary *aps; // @synthesize aps=_aps;
@property(retain, nonatomic) NSMutableDictionary *fileCreateTimes; // @synthesize fileCreateTimes=_fileCreateTimes;
@property(nonatomic) double lastPeriodCheckTime; // @synthesize lastPeriodCheckTime=_lastPeriodCheckTime;
- (void).cxx_destruct;
- (void)triggerUploadByBizGroup:(id)arg1 bizs:(id)arg2;
- (void)triggerPeriodUpload:(id)arg1 config:(id)arg2;
- (void)periodUploadCheck;
- (id)appenders;
- (void)notifyAfterLaunch:(id)arg1;
- (id)appenderForBizId:(id)arg1 createIfNotExist:(_Bool)arg2;
- (id)init;

@end

