//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, UIImage;

@interface AUSegmentItemModel : NSObject
{
    _Bool _badgeReserved;
    NSString *_title;
    UIImage *_img;
    NSString *_imgId;
    NSString *_badgeNumber;
    NSDictionary *_extendInfo;
}

@property(retain, nonatomic) NSDictionary *extendInfo; // @synthesize extendInfo=_extendInfo;
@property(nonatomic) _Bool badgeReserved; // @synthesize badgeReserved=_badgeReserved;
@property(copy, nonatomic) NSString *badgeNumber; // @synthesize badgeNumber=_badgeNumber;
@property(copy, nonatomic) NSString *imgId; // @synthesize imgId=_imgId;
@property(copy, nonatomic) UIImage *img; // @synthesize img=_img;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
- (void).cxx_destruct;

@end

