//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AUSearchBarDelegate-Protocol.h"

@class AUSearchBar, NSString, UITableView, UITapGestureRecognizer, UIView, UIViewController;
@protocol AUSearchBarDelegate, AUSearchControllerDelegate;

@interface AUSearchController : NSObject <AUSearchBarDelegate>
{
    CDStruct_5a3e4123 _searchFlags;
    UITapGestureRecognizer *_tapRecognizer;
    UIView *_statusBarCoverView;
    _Bool _isSilenceMode;
    _Bool _disableKVO;
    _Bool _active;
    float _width;
    float _animationDuration;
    UITableView *_searchResultsTableView;
    id <AUSearchControllerDelegate> _delegate;
    AUSearchBar *_searchBar;
    UIViewController *_searchResultsController;
    UIView *_customSearchContentView;
    UIView *_customContView;
    UIView *_containerView;
    UIView *_dimmingView;
    UIView *_searchBarSuperView;
    id <AUSearchBarDelegate> _originDelegate;
}

@property(nonatomic) __weak id <AUSearchBarDelegate> originDelegate; // @synthesize originDelegate=_originDelegate;
@property(nonatomic) float animationDuration; // @synthesize animationDuration=_animationDuration;
@property(nonatomic) float width; // @synthesize width=_width;
@property(retain, nonatomic) UIView *searchBarSuperView; // @synthesize searchBarSuperView=_searchBarSuperView;
@property(retain, nonatomic) UIView *dimmingView; // @synthesize dimmingView=_dimmingView;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIView *customContView; // @synthesize customContView=_customContView;
@property(retain, nonatomic) UIView *customSearchContentView; // @synthesize customSearchContentView=_customSearchContentView;
@property(readonly, nonatomic) __weak UIViewController *searchResultsController; // @synthesize searchResultsController=_searchResultsController;
@property(readonly, nonatomic) AUSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(nonatomic) __weak id <AUSearchControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)autoResizeSubViewsSlienceModeActive:(_Bool)arg1 animated:(_Bool)arg2;
- (void)setActiveInSilenceMode:(_Bool)arg1;
- (void)handleTap;
@property(nonatomic, getter=isActive) _Bool active; // @synthesize active=_active;
- (void)setActive:(_Bool)arg1 animated:(_Bool)arg2 isSilence:(_Bool)arg3;
- (void)setActive:(_Bool)arg1 animated:(_Bool)arg2;
@property(readonly, nonatomic) UITableView *searchResultsTableView; // @synthesize searchResultsTableView=_searchResultsTableView;
- (_Bool)searchBarShouldClear:(id)arg1;
- (_Bool)searchBar:(id)arg1 shouldChangeTextInRange:(struct _NSRange)arg2 replacementText:(id)arg3;
- (void)searchBar:(id)arg1 textDidChangeWithoutTrim:(id)arg2;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarSearchButtonClicked:(id)arg1;
- (void)resetSearchBar;
- (void)searchBarCancelButtonClicked:(id)arg1;
- (void)searchBarTextDidEndEditing:(id)arg1;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (_Bool)searchBarTextShouldEndEditing:(id)arg1;
- (_Bool)searchBarTextShouldBeginEditing:(id)arg1;
- (void)createResultTableView;
- (void)createDimmingView;
- (void)createContainerView;
- (void)showView:(int)arg1;
- (void)autoResizeSubViewsActive:(_Bool)arg1 animated:(_Bool)arg2;
- (_Bool)isoOnTableHeaderView:(id)arg1;
- (void)dealloc;
- (id)initWithSearchBar:(id)arg1 searchResultsController:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

