//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString, PBMapStringString;

@interface AUSRsaKeyReqPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) PBMapStringString *extParams; // @dynamic extParams;
@property(readonly) _Bool hasExtParams; // @dynamic hasExtParams;
@property(readonly) _Bool hasProductId; // @dynamic hasProductId;
@property(readonly) _Bool hasProductVersion; // @dynamic hasProductVersion;
@property(readonly) _Bool hasSdkVersion; // @dynamic hasSdkVersion;
@property(retain, nonatomic) NSString *productId; // @dynamic productId;
@property(retain, nonatomic) NSString *productVersion; // @dynamic productVersion;
@property(retain, nonatomic) NSString *sdkVersion; // @dynamic sdkVersion;

@end

