//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "AUThirdPartyAdapter-Protocol.h"

@class NSString;

@interface AUTPWrapper : NSObject <AUThirdPartyAdapter>
{
}

+ (id)wrapper;
- (void)thirdParty_openURL:(id)arg1;
- (id)thirdParty_md5String:(id)arg1;
- (id)thirdParty_configForKey:(id)arg1;
- (id)thirdParty_localizedStringForKey:(id)arg1 defaultValue:(id)arg2 inBundle:(id)arg3;
- (void)thirdPartyAPLogInfo:(id)arg1 params:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

