//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol-Protocol.h"
#import "NSCoding-Protocol.h"

@class NSString;

@interface BannerInfoItem : APPBGeneratedMessage <NSCoding, GeneratedMessageProtocol>
{
    _Bool _hasImgUrl;
    _Bool _hasLinkUrl;
    _Bool _hasBannerId;
    _Bool _hasType;
    _Bool _hasBizExt;
    NSString *_imgUrl;
    NSString *_linkUrl;
    NSString *_bannerId;
    long long _type;
    NSString *_bizExt;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *bizExt; // @synthesize bizExt=_bizExt;
@property(nonatomic) long long type; // @synthesize type=_type;
@property(retain, nonatomic) NSString *bannerId; // @synthesize bannerId=_bannerId;
@property(retain, nonatomic) NSString *linkUrl; // @synthesize linkUrl=_linkUrl;
@property(retain, nonatomic) NSString *imgUrl; // @synthesize imgUrl=_imgUrl;
@property(readonly) _Bool hasBizExt; // @synthesize hasBizExt=_hasBizExt;
@property(readonly) _Bool hasType; // @synthesize hasType=_hasType;
@property(readonly) _Bool hasBannerId; // @synthesize hasBannerId=_hasBannerId;
@property(readonly) _Bool hasLinkUrl; // @synthesize hasLinkUrl=_hasLinkUrl;
@property(readonly) _Bool hasImgUrl; // @synthesize hasImgUrl=_hasImgUrl;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;
@property(nonatomic) _Bool hadSendLog;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

