//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSDictionary, NSMutableArray, SUImageView, UIImageView, UILabel;

@interface BCCardView : UIView
{
    SUImageView *_imageView;
    UILabel *_mainTitleLab;
    UILabel *_mainDescLab;
    NSMutableArray *_subLabsArray;
    NSDictionary *_dataRes;
    UIView *_line;
    UIImageView *_arrow;
}

@property(retain, nonatomic) UIImageView *arrow; // @synthesize arrow=_arrow;
@property(retain, nonatomic) UIView *line; // @synthesize line=_line;
@property(retain, nonatomic) NSDictionary *dataRes; // @synthesize dataRes=_dataRes;
@property(retain, nonatomic) NSMutableArray *subLabsArray; // @synthesize subLabsArray=_subLabsArray;
@property(retain, nonatomic) UILabel *mainDescLab; // @synthesize mainDescLab=_mainDescLab;
@property(retain, nonatomic) UILabel *mainTitleLab; // @synthesize mainTitleLab=_mainTitleLab;
@property(retain, nonatomic) SUImageView *imageView; // @synthesize imageView=_imageView;
- (void).cxx_destruct;
- (void)layoutSubviews;
- (void)refreshDisplay;
- (void)refreshWithData:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

