//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "BEECityLBSCell.h"

@class BeeCityVOModel;

@interface BeeCityVOLBSCell : BEECityLBSCell
{
    BeeCityVOModel *_lbsCityVO;
    long long _lineCount;
}

@property(nonatomic) long long lineCount; // @synthesize lineCount=_lineCount;
@property(retain, nonatomic) BeeCityVOModel *lbsCityVO; // @synthesize lbsCityVO=_lbsCityVO;
- (void).cxx_destruct;
- (void)clickButton:(id)arg1;
- (id)getBEECityName;
- (void)setBEECityName:(id)arg1;
- (void)layoutSubviews;
- (void)updateLayoutByCityName:(id)arg1;
- (void)setCityVO:(id)arg1;

@end

