//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class BeeDetectPornComponent;

@interface BeeContentSecurityManager : NSObject
{
    BeeDetectPornComponent *_detectPornComponent;
}

+ (id)getDetectPornImageInfo:(id)arg1;
+ (id)getDetectAudioSource:(id)arg1;
+ (id)getDetectPornVideoSource:(id)arg1;
+ (id)getDetectPornConfig:(id)arg1;
@property(retain, nonatomic) BeeDetectPornComponent *detectPornComponent; // @synthesize detectPornComponent=_detectPornComponent;
- (void).cxx_destruct;
- (void)detectImageInfo:(id)arg1;
- (void)resumeDetect;
- (void)puaseDetect;
- (void)deInit;
- (void)startDetectWithSourceItem:(id)arg1;
- (void)setDetectPornDelegate:(id)arg1;
- (void)initDetectPornWithConfigItem:(id)arg1;

@end

