//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

#import "AUBladeViewDelegate-Protocol.h"
#import "AUSearchBarDelegate-Protocol.h"
#import "AUSearchControllerDelegate-Protocol.h"
#import "BEECityGridCellDelegate-Protocol.h"
#import "BEECityLBSCellDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class AUBladeView, AULabel, AUSearchBar, AUSearchController, AUTitleBarSegment, BEECityLocator, BEECityManager, BEECitySearchHandler, BeeCityPageModel, BeeCityStorage, BeeCityVOModel, BeePageContainerView, NSArray, NSMutableArray, NSMutableDictionary, NSString, UIViewController;
@protocol BeeCityPickerVCDelegate;

@interface BeeCityPickerViewController : DTViewController <UITableViewDelegate, UITableViewDataSource, AUSearchBarDelegate, AUSearchControllerDelegate, AUBladeViewDelegate, BEECityGridCellDelegate, BEECityLBSCellDelegate>
{
    AUSearchBar *_searchBar;
    _Bool _useDefaultData;
    _Bool _isLocating;
    _Bool _isBack;
    _Bool _isSubPickerVC;
    _Bool _showIndexBar;
    id <BeeCityPickerVCDelegate> _citySelDelegate;
    NSArray *_citiesModels;
    BEECitySearchHandler *_searchHandler;
    NSArray *_cachCities;
    NSMutableArray *_indexArray;
    NSMutableDictionary *_sortedDic;
    BEECityLocator *_locator;
    AUSearchController *_searchController;
    NSArray *_searchResults;
    BEECityManager *_cityManager;
    BeeCityPageModel *_pageModel;
    BeeCityVOModel *_locateCity;
    AUBladeView *_bladeView;
    BeePageContainerView *_mainlandContainer;
    BeePageContainerView *_overseasContainer;
    AUTitleBarSegment *_titleSegment;
    UIViewController *_backToVC;
    CDUnknownBlockType _completion;
    AULabel *_seachNoneLabel;
    BeeCityStorage *_storage;
}

+ (id)getCityDataWithArray:(id)arg1 title:(id)arg2;
+ (void)buildIndexSortedList:(id)arg1;
+ (id)getIndexCharByPinyin:(id)arg1 cityName:(id)arg2;
+ (void)insertIndexChar:(id)arg1 obj:(id)arg2 toDic:(id)arg3 toList:(id)arg4;
+ (id)sortedIndexList:(id)arg1;
+ (id)buildDefaultLbsTabModel;
+ (id)dataModelConvert:(id)arg1;
@property(retain, nonatomic) BeeCityStorage *storage; // @synthesize storage=_storage;
@property(retain, nonatomic) AULabel *seachNoneLabel; // @synthesize seachNoneLabel=_seachNoneLabel;
@property(nonatomic) _Bool showIndexBar; // @synthesize showIndexBar=_showIndexBar;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) __weak UIViewController *backToVC; // @synthesize backToVC=_backToVC;
@property(retain, nonatomic) AUTitleBarSegment *titleSegment; // @synthesize titleSegment=_titleSegment;
@property(retain, nonatomic) BeePageContainerView *overseasContainer; // @synthesize overseasContainer=_overseasContainer;
@property(retain, nonatomic) BeePageContainerView *mainlandContainer; // @synthesize mainlandContainer=_mainlandContainer;
@property(retain, nonatomic) AUBladeView *bladeView; // @synthesize bladeView=_bladeView;
@property(retain, nonatomic) BeeCityVOModel *locateCity; // @synthesize locateCity=_locateCity;
@property(retain, nonatomic) BeeCityPageModel *pageModel; // @synthesize pageModel=_pageModel;
@property(retain, nonatomic) BEECityManager *cityManager; // @synthesize cityManager=_cityManager;
@property(retain, nonatomic) NSArray *searchResults; // @synthesize searchResults=_searchResults;
@property(retain, nonatomic) AUSearchController *searchController; // @synthesize searchController=_searchController;
@property(nonatomic) _Bool isSubPickerVC; // @synthesize isSubPickerVC=_isSubPickerVC;
@property(nonatomic) _Bool isBack; // @synthesize isBack=_isBack;
@property(nonatomic) _Bool isLocating; // @synthesize isLocating=_isLocating;
@property(retain, nonatomic) BEECityLocator *locator; // @synthesize locator=_locator;
@property(retain, nonatomic) NSMutableDictionary *sortedDic; // @synthesize sortedDic=_sortedDic;
@property(retain, nonatomic) NSMutableArray *indexArray; // @synthesize indexArray=_indexArray;
@property(retain, nonatomic) NSArray *cachCities; // @synthesize cachCities=_cachCities;
@property(retain, nonatomic) BEECitySearchHandler *searchHandler; // @synthesize searchHandler=_searchHandler;
@property(nonatomic) _Bool useDefaultData; // @synthesize useDefaultData=_useDefaultData;
@property(retain, nonatomic) NSArray *citiesModels; // @synthesize citiesModels=_citiesModels;
@property(nonatomic) __weak id <BeeCityPickerVCDelegate> citySelDelegate; // @synthesize citySelDelegate=_citySelDelegate;
- (void).cxx_destruct;
- (void)back;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBarTextDidBeginEditing:(id)arg1;
- (_Bool)searchBarTextShouldBeginEditing:(id)arg1;
- (void)indexSelectionDidChange:(id)arg1 index:(long long)arg2 title:(id)arg3;
- (id)sectionLabel;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (void)gotoSubViewController:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)calculaterealRowAtSection:(long long)arg1;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (double)maxWidthForCurrentPage;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (id)getCurCityPageModel;
- (id)cityTabModelListAtIndexPath:(id)arg1;
- (void)updateOverseaDataWithRPC;
- (void)loadData;
- (void)segmentControlDidChanged:(id)arg1;
- (void)checkShowSearchBarByIndex:(long long)arg1;
- (void)buildBladeIndexList;
- (void)setupUILoadDataComplete;
- (id)generateIndexBar;
- (void)setupIndexBar;
- (void)viewWillLayoutSubviews;
- (void)setupSubViews;
- (void)applicationDidActive;
- (void)dealloc;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setupSearchIndex;
- (void)reloadWithDataList:(id)arg1;
- (_Bool)checkNeedLoadLocalData;
- (void)viewDidLoad;
- (id)initWithCityDatas:(id)arg1 backToVC:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (id)initWithBacktoVC:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (double)getExpiredTime;
- (id)getCityModelWithData:(id)arg1;
- (id)getOverseasDataModelWithArray:(id)arg1;
- (void)loadOverseaDataFromRPC:(CDUnknownBlockType)arg1;
- (id)loadLocalOverseasData;
- (_Bool)fallbackCrashFix;
- (id)getAppId;
- (_Bool)isHomePagePicker;
- (void)fillLocalDataByCustom:(id)arg1;
- (void)shouldScrollToTop:(id)arg1;
- (void)loadLocalCitiesInResource:(CDUnknownBlockType)arg1;
- (id)loadLocalMainLandData;
- (void)unregisterDelegate;
- (id)getDefaultBackToVC;
- (void)didFinishSelectCityVOModel:(id)arg1;
- (_Bool)locatedSuccess;
- (void)didClickLBSCityVO:(id)arg1;
- (id)findIndexCharByModel:(id)arg1;
- (void)filterCurLocatedCityBlock;
- (void)reloadContainerView;
- (void)startLocating;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

