//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "BeeRtcRoomDelegate-Protocol.h"

@class BeeRtcRoomView, NSMutableDictionary, NSString;

@interface BeeRtcRoomRemoteLogPlugin : NSObject <BeeRtcRoomDelegate>
{
    _Bool _needReprotLog;
    BeeRtcRoomView *_mainView;
    NSString *_serviceId;
    NSMutableDictionary *_firstPlayCost;
    long long _videoStuckCount;
    long long _audioStuckCount;
    long long _audioStuckCountReceive;
    long long _videoStuckCountReceive;
    double _roomStartTime;
}

@property(nonatomic) double roomStartTime; // @synthesize roomStartTime=_roomStartTime;
@property(nonatomic) long long videoStuckCountReceive; // @synthesize videoStuckCountReceive=_videoStuckCountReceive;
@property(nonatomic) long long audioStuckCountReceive; // @synthesize audioStuckCountReceive=_audioStuckCountReceive;
@property(nonatomic) long long audioStuckCount; // @synthesize audioStuckCount=_audioStuckCount;
@property(nonatomic) long long videoStuckCount; // @synthesize videoStuckCount=_videoStuckCount;
@property(retain, nonatomic) NSMutableDictionary *firstPlayCost; // @synthesize firstPlayCost=_firstPlayCost;
@property(nonatomic) _Bool needReprotLog; // @synthesize needReprotLog=_needReprotLog;
@property(copy, nonatomic) NSString *serviceId; // @synthesize serviceId=_serviceId;
@property(nonatomic) __weak BeeRtcRoomView *mainView; // @synthesize mainView=_mainView;
- (void).cxx_destruct;
- (void)reportLogWithRtcRoom:(id)arg1 monitor:(long long)arg2 success:(_Bool)arg3 andError:(id)arg4;
- (void)BeeRtcRoomStatistic:(id)arg1 userId:(id)arg2;
- (void)BeeRtcRoomNetWorkQuality:(long long)arg1 bandwidth:(double)arg2 isLocal:(_Bool)arg3;
- (void)BeeRtcRoomConnectionStatueChange:(long long)arg1 isLocal:(_Bool)arg2 userId:(id)arg3;
- (void)BeeRtcRoomPlayViewChage:(id)arg1 feedType:(long long)arg2;
- (void)BeeRtcRoomDidChangeParticipant:(id)arg1 type:(long long)arg2;
- (void)BeeRtcRoomErrorState:(long long)arg1 error:(id)arg2;
- (void)BeeRtcRoomAudioPlayModeChange:(long long)arg1;
- (void)BeeRtcRoomStart;
- (void)BeeRtcRoomLeaveRoom;
- (void)BeeRtcRoomDidStopPlay;
- (void)BeeRtcRoomDidReadyPlay;
- (void)BeeRtcRoomJoinRoom:(_Bool)arg1 error:(id)arg2;
- (void)BeeRtcRoomCreateRoom:(id)arg1 error:(id)arg2;
- (void)pluginItemDidUninstall:(id)arg1;
- (void)pluginItemDidInstall:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

