//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface BRZDeviceData : NSObject
{
    unsigned char _protocolId;
    unsigned char _subType;
    unsigned char _funcitonMask;
    unsigned char _bleVersion;
    _Bool _supportOta;
    _Bool _supportEncrypt;
    unsigned short _companyId;
    unsigned int _internelModelId;
    NSString *_modelId;
    NSString *_mac;
    NSString *_secret;
    long long _encryptType;
}

@property(nonatomic) unsigned int internelModelId; // @synthesize internelModelId=_internelModelId;
@property(nonatomic) _Bool supportEncrypt; // @synthesize supportEncrypt=_supportEncrypt;
@property(nonatomic) _Bool supportOta; // @synthesize supportOta=_supportOta;
@property(nonatomic) long long encryptType; // @synthesize encryptType=_encryptType;
@property(copy, nonatomic) NSString *secret; // @synthesize secret=_secret;
@property(copy, nonatomic) NSString *mac; // @synthesize mac=_mac;
@property(copy, nonatomic) NSString *modelId; // @synthesize modelId=_modelId;
@property(nonatomic) unsigned char bleVersion; // @synthesize bleVersion=_bleVersion;
@property(nonatomic) unsigned char funcitonMask; // @synthesize funcitonMask=_funcitonMask;
@property(nonatomic) unsigned char subType; // @synthesize subType=_subType;
@property(nonatomic) unsigned char protocolId; // @synthesize protocolId=_protocolId;
@property(nonatomic) unsigned short companyId; // @synthesize companyId=_companyId;
- (void).cxx_destruct;
- (id)toDictionary;
- (_Bool)isVaild;

@end

