//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ButtonInfo : NSObject
{
    NSString *_btnDesc;
    NSString *_btnStatus;
    NSString *_btnUrl;
    NSString *_btnType;
    NSString *_useBtnText;
    NSString *_confirmText;
}

+ (id)instanceForData:(id)arg1;
@property(retain, nonatomic) NSString *confirmText; // @synthesize confirmText=_confirmText;
@property(retain, nonatomic) NSString *useBtnText; // @synthesize useBtnText=_useBtnText;
@property(retain, nonatomic) NSString *btnType; // @synthesize btnType=_btnType;
@property(retain, nonatomic) NSString *btnUrl; // @synthesize btnUrl=_btnUrl;
@property(retain, nonatomic) NSString *btnStatus; // @synthesize btnStatus=_btnStatus;
@property(retain, nonatomic) NSString *btnDesc; // @synthesize btnDesc=_btnDesc;
- (void).cxx_destruct;

@end

