//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AURefreshView.h"

#import "AURefreshViewDelegate-Protocol.h"
#import "CBPullStageView-Protocol.h"
#import "CBRefreshView-Protocol.h"

@class NSString, UIScrollView;
@protocol CBRefreshViewDelegate;

@interface CBCommonRefreshView : AURefreshView <AURefreshViewDelegate, CBRefreshView, CBPullStageView>
{
    id <CBRefreshViewDelegate> _cubeBizDelegate;
    UIScrollView *_cbScrollView;
}

@property(nonatomic) __weak UIScrollView *cbScrollView; // @synthesize cbScrollView=_cbScrollView;
@property(nonatomic) __weak id <CBRefreshViewDelegate> cubeBizDelegate; // @synthesize cubeBizDelegate=_cubeBizDelegate;
- (void).cxx_destruct;
- (void)auRefreshViewDidFinishAnimation:(id)arg1;
- (void)auRefreshViewDidTriggerloading:(id)arg1;
- (void)closeStageAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)openStageAnimated:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewWillEndDragging:(id)arg1 withVelocity:(struct CGPoint)arg2 targetContentOffset:(inout struct CGPoint *)arg3;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)applicationDidBecomeActive;
- (void)applicationDidEnterBackground;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillDisappear;
- (void)viewWillAppear;
- (_Bool)isStateReady;
- (void)show:(_Bool)arg1 animated:(_Bool)arg2;
- (id)initWithSuperView:(id)arg1 type:(unsigned long long)arg2 bizType:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

