//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CDPDiagnosisMgr : NSObject
{
    _Bool _paramsWatchOpened;
    _Bool _inDevEnvironment;
    _Bool _userSetOpened;
}

+ (id)adIdStrForSpaceCodes:(id)arg1 spaceInfos:(id)arg2;
+ (id)adIdStrForSpaceInfo:(id)arg1;
+ (id)instance;
@property _Bool userSetOpened; // @synthesize userSetOpened=_userSetOpened;
@property(nonatomic) _Bool inDevEnvironment; // @synthesize inDevEnvironment=_inDevEnvironment;
- (void)appWillEnterForeground:(id)arg1;
- (void)doLoginUserChanged:(id)arg1;
- (void)beginDiagnose:(CDUnknownBlockType)arg1;
- (void)setParamsWatchSetting:(_Bool)arg1;
- (_Bool)paramsWatchOpened;
- (_Bool)userSettingOpened;
- (void)setUserSetting:(_Bool)arg1;
- (_Bool)diagnoseOpened;
- (void)resetUserSeting;
- (void)dealloc;
- (id)init;

@end

