//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray;

@interface CKExternalInvocation : NSObject
{
    id _target;
    unsigned long long _methodID;
    NSArray *_args;
    SEL _selector;
    id _object1;
    id _object2;
}

+ (id)monitorNameForMethodID:(unsigned long long)arg1;
+ (id)target:(id)arg1 selector:(SEL)arg2 arg:(id)arg3 arg:(id)arg4;
+ (id)target:(id)arg1 selector:(SEL)arg2 arg:(id)arg3;
+ (id)target:(id)arg1 selector:(SEL)arg2;
+ (id)target:(id)arg1 methodID:(unsigned long long)arg2 args:(id)arg3;
@property(retain, nonatomic) id object2; // @synthesize object2=_object2;
@property(retain, nonatomic) id object1; // @synthesize object1=_object1;
@property(nonatomic) SEL selector; // @synthesize selector=_selector;
@property(copy, nonatomic) NSArray *args; // @synthesize args=_args;
@property(nonatomic) unsigned long long methodID; // @synthesize methodID=_methodID;
@property(retain, nonatomic) id target; // @synthesize target=_target;
- (void).cxx_destruct;
- (double)externalCallCost;
- (_Bool)invokeWithPerformCall:(id *)arg1;
- (_Bool)invokeWithDirectlyCall:(id *)arg1;
- (_Bool)invoke:(id *)arg1;
- (_Bool)invoke;
- (id)initWithTarget:(id)arg1;

@end

