//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString;

@protocol CKListInterface <NSObject>

@optional
- (struct CGPoint)scrollOffset;
- (_Bool)scrollToElment:(NSString *)arg1 section:(long long)arg2 row:(long long)arg3;
- (_Bool)isViewScrolling;
- (void)reload:(NSArray *)arg1;
- (void)removeFooter:(int)arg1 immediately:(_Bool)arg2;
- (void)updateFooter:(int)arg1 immediately:(_Bool)arg2;
- (void)insertFooter:(int)arg1 immediately:(_Bool)arg2;
- (void)removeHeader:(int)arg1 immediately:(_Bool)arg2;
- (void)updateHeader:(int)arg1 immediately:(_Bool)arg2;
- (void)insertHeader:(int)arg1 immediately:(_Bool)arg2;
- (void)removeSection:(int)arg1 immediately:(_Bool)arg2;
- (void)updateSection:(int)arg1 immediately:(_Bool)arg2;
- (void)insertSection:(int)arg1 immediately:(_Bool)arg2;
- (void)removeItem:(int)arg1 rowIndex:(int)arg2 immediately:(_Bool)arg3;
- (void)updateItem:(int)arg1 rowIndex:(int)arg2 immediately:(_Bool)arg3;
- (void)insertItem:(int)arg1 rowIndex:(int)arg2 immediately:(_Bool)arg3;
@end

