//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CLBarrageBaseView.h"

@class UIImageView;

@interface CLFloatBubbleView : CLBarrageBaseView
{
    UIImageView *_floatImageView;
    struct CGPoint pointOffset;
}

+ (double)unavailableWidthForModel:(id)arg1;
+ (double)fontSize;
- (void).cxx_destruct;
- (double)visualWidth;
- (double)rightMargin;
- (double)leftMargin;
- (double)fontSize;
- (double)roundCornerRadius;
- (struct CGSize)iconSize;
- (void)refreshWithModel:(id)arg1;
- (void)refreshWithTotalUser:(unsigned long long)arg1;
- (void)panGestureAction:(id)arg1;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

