//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWBaseResponse.h"

@class GoldQuotation, NSString;

@interface CreateResponse : GWBaseResponse
{
    NSString *_crowdNo;
    NSString *_prodCode;
    NSString *_verifyId;
    NSString *_securityId;
    NSString *_orderNo;
    NSString *_bizNo;
    long long _lackShare;
    NSString *_lackShareAmount;
    long long _availableShare;
    NSString *_dingShareLink;
    NSString *_goldenRecord;
    NSString *_mockCard;
    GoldQuotation *_goldQuotation;
    NSString *_bizType;
    NSString *_bizSubType;
    NSString *_tradeNo;
    NSString *_enough;
    NSString *_refundHour;
}

@property(retain, nonatomic) NSString *refundHour; // @synthesize refundHour=_refundHour;
@property(retain, nonatomic) NSString *enough; // @synthesize enough=_enough;
@property(retain, nonatomic) NSString *tradeNo; // @synthesize tradeNo=_tradeNo;
@property(retain, nonatomic) NSString *bizSubType; // @synthesize bizSubType=_bizSubType;
@property(retain, nonatomic) NSString *bizType; // @synthesize bizType=_bizType;
@property(retain, nonatomic) GoldQuotation *goldQuotation; // @synthesize goldQuotation=_goldQuotation;
@property(retain, nonatomic) NSString *mockCard; // @synthesize mockCard=_mockCard;
@property(retain, nonatomic) NSString *goldenRecord; // @synthesize goldenRecord=_goldenRecord;
@property(retain, nonatomic) NSString *dingShareLink; // @synthesize dingShareLink=_dingShareLink;
@property(nonatomic) long long availableShare; // @synthesize availableShare=_availableShare;
@property(retain, nonatomic) NSString *lackShareAmount; // @synthesize lackShareAmount=_lackShareAmount;
@property(nonatomic) long long lackShare; // @synthesize lackShare=_lackShare;
@property(retain, nonatomic) NSString *bizNo; // @synthesize bizNo=_bizNo;
@property(retain, nonatomic) NSString *orderNo; // @synthesize orderNo=_orderNo;
@property(retain, nonatomic) NSString *securityId; // @synthesize securityId=_securityId;
@property(retain, nonatomic) NSString *verifyId; // @synthesize verifyId=_verifyId;
@property(retain, nonatomic) NSString *prodCode; // @synthesize prodCode=_prodCode;
@property(retain, nonatomic) NSString *crowdNo; // @synthesize crowdNo=_crowdNo;
- (void).cxx_destruct;

@end

