//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class ACApp, NSString;

@interface CTAppModel : NSObject
{
    int _type;
    ACApp *_appItem;
    NSString *_cdpObjectId;
    NSString *_angleContent;
    long long _recommendStatus;
}

@property(nonatomic) long long recommendStatus; // @synthesize recommendStatus=_recommendStatus;
@property(retain, nonatomic) NSString *angleContent; // @synthesize angleContent=_angleContent;
@property(retain, nonatomic) NSString *cdpObjectId; // @synthesize cdpObjectId=_cdpObjectId;
@property(nonatomic) int type; // @synthesize type=_type;
@property(retain, nonatomic) ACApp *appItem; // @synthesize appItem=_appItem;
- (void).cxx_destruct;

@end

