//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "CTInputViewGroupActionDelegate-Protocol.h"

@protocol CTInputViewGeneralProtocol;

@protocol CTInputViewSnapChatGroupActionDelegate <CTInputViewGroupActionDelegate>

@optional
- (void)inputView:(id <CTInputViewGeneralProtocol>)arg1 exitSnapChatButtonTapped:(id)arg2;
- (void)inputView:(id <CTInputViewGeneralProtocol>)arg1 picVideoEntryButtonTapped:(id)arg2;
@end

