//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface CubeBridge : NSObject
{
}

+ (void)registerModules:(id)arg1;
+ (void)registerWidgetsToJS:(id)arg1;
+ (void)registerWidgets:(id)arg1 widgetProps:(id)arg2 engine:(id)arg3;
+ (void)registerWidgets:(id)arg1 engine:(id)arg2;
+ (void)registerDefaultHandlers:(id)arg1;
+ (void)regDefaultModules;
+ (id)getRealWidgetsJSInfo:(id)arg1;
+ (void)regDefaultWidgets:(id)arg1;
+ (void)registerBridgeRouters;
+ (void)createGlobalJSContext:(id)arg1 jsFramework:(id)arg2;
+ (void)initWithJSFM:(id)arg1 version:(id)arg2 engine:(id)arg3;

@end

