//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface custlifeCardPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *backupData; // @dynamic backupData;
@property(retain, nonatomic) NSString *bizType; // @dynamic bizType;
@property(retain, nonatomic) NSString *clientId; // @dynamic clientId;
@property(retain, nonatomic) NSString *ext; // @dynamic ext;
@property(retain, nonatomic) NSString *feedId; // @dynamic feedId;
@property(readonly) _Bool hasBackupData; // @dynamic hasBackupData;
@property(readonly) _Bool hasBizType; // @dynamic hasBizType;
@property(readonly) _Bool hasClientId; // @dynamic hasClientId;
@property(readonly) _Bool hasExt; // @dynamic hasExt;
@property(readonly) _Bool hasFeedId; // @dynamic hasFeedId;
@property(readonly) _Bool hasTemplateData; // @dynamic hasTemplateData;
@property(readonly) _Bool hasTemplateId; // @dynamic hasTemplateId;
@property(retain, nonatomic) NSString *templateData; // @dynamic templateData;
@property(retain, nonatomic) NSString *templateId; // @dynamic templateId;

@end

