//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableString;
@protocol OS_dispatch_queue, OS_dispatch_semaphore;

@interface DAIndependentLogger : NSObject
{
    NSMutableString *_logBuffer;
    long long _logCount;
    NSObject<OS_dispatch_semaphore> *_lock;
    NSObject<OS_dispatch_queue> *_logQueue;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)appendLogEndSymbolForLogBuffer:(id)arg1;
- (id)appendLogBuffer:(id)arg1 withBizId:(id)arg2 ucId:(id)arg3 extParams:(id)arg4;
- (id)createLogHeadWithBizId:(id)arg1;
- (long long)maxLogNum;
- (void)saveAllMemoryLogToLocal;
- (void)handlerLogWithBizId:(id)arg1 ucId:(id)arg2 extParams:(id)arg3 upload:(_Bool)arg4;
- (void)recordLogWithType:(id)arg1 bizId:(id)arg2 ucId:(id)arg3 extParams:(id)arg4;
- (void)crashLogHandler:(id)arg1;
- (id)init;

@end

