//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSArray, NSString, distinguishprodBorderCoordinatesModelPB, distinguishprodColorModelPB;

@interface distinguishprodParagraphModelPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) distinguishprodBorderCoordinatesModelPB *borderCoordinates; // @dynamic borderCoordinates;
@property(retain, nonatomic) distinguishprodColorModelPB *color; // @dynamic color;
@property(retain, nonatomic) NSString *desc; // @dynamic desc;
@property(readonly) _Bool hasBorderCoordinates; // @dynamic hasBorderCoordinates;
@property(readonly) _Bool hasColor; // @dynamic hasColor;
@property(readonly) _Bool hasDesc; // @dynamic hasDesc;
@property(readonly) _Bool hasOcrDesc; // @dynamic hasOcrDesc;
@property(retain, nonatomic) NSArray *lines; // @dynamic lines;
@property(retain, nonatomic) NSString *ocrDesc; // @dynamic ocrDesc;
@property(retain, nonatomic) NSArray *tags; // @dynamic tags;

@end

