//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface distinguishprodIdentifyRouteManager : NSObject
{
}

- (id)route:(id)arg1;
- (id)routeForPreview:(id)arg1;
- (id)routeV10_0_18:(id)arg1;

@end

