//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APPBGeneratedMessage.h"

#import "GeneratedMessageProtocol-Protocol.h"
#import "NSCoding-Protocol.h"

@class NSString;

@interface EleMerchant : APPBGeneratedMessage <NSCoding, GeneratedMessageProtocol>
{
    _Bool _hasScore;
    _Bool _hasSaleCnt;
    _Bool _hasReceiveTime;
    _Bool _hasExt;
    NSString *_score;
    NSString *_saleCnt;
    NSString *_receiveTime;
    NSString *_ext;
}

+ (id)parseFromData:(id)arg1;
@property(retain, nonatomic) NSString *ext; // @synthesize ext=_ext;
@property(retain, nonatomic) NSString *receiveTime; // @synthesize receiveTime=_receiveTime;
@property(retain, nonatomic) NSString *saleCnt; // @synthesize saleCnt=_saleCnt;
@property(retain, nonatomic) NSString *score; // @synthesize score=_score;
@property(readonly) _Bool hasExt; // @synthesize hasExt=_hasExt;
@property(readonly) _Bool hasReceiveTime; // @synthesize hasReceiveTime=_hasReceiveTime;
@property(readonly) _Bool hasSaleCnt; // @synthesize hasSaleCnt=_hasSaleCnt;
@property(readonly) _Bool hasScore; // @synthesize hasScore=_hasScore;
- (void).cxx_destruct;
- (void)mergeFromCodedInputStream:(id)arg1 extensionRegistry:(id)arg2;
- (int)serializedSize;
- (void)writeToCodedOutputStream:(id)arg1;
- (id)init;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

