//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FHCellBaseModel.h"

@class FHCellNewsBattleInteract, FHCellNewsBattleItemModelExt, FHCellNewsBattleUser, NSString;

@interface FHCellNewsBattleItemModel : FHCellBaseModel
{
    NSString *_obId;
    NSString *_obType;
    NSString *_followAction;
    NSString *_feature;
    NSString *_reason;
    long long _featureType;
    NSString *_title;
    NSString *_column;
    NSString *_contentPic;
    NSString *_publishTime;
    NSString *_forumName;
    FHCellNewsBattleUser *_contentUser;
    FHCellNewsBattleItemModelExt *_ext;
    FHCellNewsBattleInteract *_interactInfo;
    NSString *_cardTypeId;
    NSString *_resourceId;
}

+ (id)parseBattleItemModelWithDataModel:(id)arg1 card:(id)arg2 obFloor:(id)arg3 index:(unsigned long long)arg4 fagId:(id)arg5;
+ (id)parseHeadModelWithDataModel:(id)arg1 card:(id)arg2 obFloor:(id)arg3 index:(unsigned long long)arg4 fagId:(id)arg5;
@property(retain, nonatomic) NSString *resourceId; // @synthesize resourceId=_resourceId;
@property(retain, nonatomic) NSString *cardTypeId; // @synthesize cardTypeId=_cardTypeId;
@property(retain, nonatomic) FHCellNewsBattleInteract *interactInfo; // @synthesize interactInfo=_interactInfo;
@property(retain, nonatomic) FHCellNewsBattleItemModelExt *ext; // @synthesize ext=_ext;
@property(retain, nonatomic) FHCellNewsBattleUser *contentUser; // @synthesize contentUser=_contentUser;
@property(retain, nonatomic) NSString *forumName; // @synthesize forumName=_forumName;
@property(retain, nonatomic) NSString *publishTime; // @synthesize publishTime=_publishTime;
@property(retain, nonatomic) NSString *contentPic; // @synthesize contentPic=_contentPic;
@property(retain, nonatomic) NSString *column; // @synthesize column=_column;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(nonatomic) long long featureType; // @synthesize featureType=_featureType;
@property(retain, nonatomic) NSString *reason; // @synthesize reason=_reason;
@property(retain, nonatomic) NSString *feature; // @synthesize feature=_feature;
@property(retain, nonatomic) NSString *followAction; // @synthesize followAction=_followAction;
@property(retain, nonatomic) NSString *obType; // @synthesize obType=_obType;
@property(retain, nonatomic) NSString *obId; // @synthesize obId=_obId;
- (void).cxx_destruct;
- (id)classIdentifier;
- (id)prefix_dSpmId;
- (id)prefix_spmId;
- (_Bool)isEqual:(id)arg1;
- (id)initWithDataModel:(id)arg1 card:(id)arg2 obFloor:(id)arg3 index:(unsigned long long)arg4 fagId:(id)arg5;

@end

