//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface FHCollectionViewDiffableDataSourceCallback : NSObject
{
    CDUnknownBlockType _insertCallback;
    CDUnknownBlockType _deleteCallback;
    CDUnknownBlockType _moveCallback;
    CDUnknownBlockType _reloadCallback;
}

@property(copy, nonatomic) CDUnknownBlockType reloadCallback; // @synthesize reloadCallback=_reloadCallback;
@property(copy, nonatomic) CDUnknownBlockType moveCallback; // @synthesize moveCallback=_moveCallback;
@property(copy, nonatomic) CDUnknownBlockType deleteCallback; // @synthesize deleteCallback=_deleteCallback;
@property(copy, nonatomic) CDUnknownBlockType insertCallback; // @synthesize insertCallback=_insertCallback;
- (void).cxx_destruct;

@end

