//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, UIImageView, UILabel;

@interface FHScrollWidgetAwardView : UIView
{
    NSString *_awardText;
    UIImageView *_awardBgView;
    UILabel *_awardLabel;
}

@property(retain, nonatomic) UILabel *awardLabel; // @synthesize awardLabel=_awardLabel;
@property(retain, nonatomic) UIImageView *awardBgView; // @synthesize awardBgView=_awardBgView;
@property(copy, nonatomic) NSString *awardText; // @synthesize awardText=_awardText;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

