//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FHTemplateStockScrollViewCellModel.h"

@class NSString, UIColor;

@interface FHTemplateStockInfoDataModel : FHTemplateStockScrollViewCellModel
{
    _Bool _hasItsData;
    _Bool _needsHideChangeAmount;
    UIColor *_textColor;
    NSString *_symbol;
    NSString *_market;
    NSString *_name;
    NSString *_formatPrice;
    NSString *_formatPriceChangeAmount;
    NSString *_formatPriceChangePercent;
    NSString *_formatCurrentTradingStatusNotice;
    UIColor *_currentTradingStatusNoticeBgColor;
    UIColor *_currentTradingStatusNoticeFgColor;
    long long _itsStartTime;
    long long _itsEndTime;
    NSString *_itsName;
    long long _itsDirection;
    NSString *_currentTradingStatusText;
    NSString *_originFollowAction;
}

+ (id)defaultData;
+ (_Bool)isItsDisable;
+ (id)createWithOriginData:(id)arg1 extInfo:(id)arg2;
@property(copy, nonatomic) NSString *originFollowAction; // @synthesize originFollowAction=_originFollowAction;
@property(copy, nonatomic) NSString *currentTradingStatusText; // @synthesize currentTradingStatusText=_currentTradingStatusText;
@property(nonatomic) long long itsDirection; // @synthesize itsDirection=_itsDirection;
@property(copy, nonatomic) NSString *itsName; // @synthesize itsName=_itsName;
@property(nonatomic) long long itsEndTime; // @synthesize itsEndTime=_itsEndTime;
@property(nonatomic) long long itsStartTime; // @synthesize itsStartTime=_itsStartTime;
@property(nonatomic) _Bool needsHideChangeAmount; // @synthesize needsHideChangeAmount=_needsHideChangeAmount;
@property(nonatomic) _Bool hasItsData; // @synthesize hasItsData=_hasItsData;
@property(retain, nonatomic) UIColor *currentTradingStatusNoticeFgColor; // @synthesize currentTradingStatusNoticeFgColor=_currentTradingStatusNoticeFgColor;
@property(retain, nonatomic) UIColor *currentTradingStatusNoticeBgColor; // @synthesize currentTradingStatusNoticeBgColor=_currentTradingStatusNoticeBgColor;
@property(copy, nonatomic) NSString *formatCurrentTradingStatusNotice; // @synthesize formatCurrentTradingStatusNotice=_formatCurrentTradingStatusNotice;
@property(copy, nonatomic) NSString *formatPriceChangePercent; // @synthesize formatPriceChangePercent=_formatPriceChangePercent;
@property(copy, nonatomic) NSString *formatPriceChangeAmount; // @synthesize formatPriceChangeAmount=_formatPriceChangeAmount;
@property(copy, nonatomic) NSString *formatPrice; // @synthesize formatPrice=_formatPrice;
@property(copy, nonatomic) NSString *name; // @synthesize name=_name;
@property(copy, nonatomic) NSString *market; // @synthesize market=_market;
@property(copy, nonatomic) NSString *symbol; // @synthesize symbol=_symbol;
@property(retain, nonatomic) UIColor *textColor; // @synthesize textColor=_textColor;
- (void).cxx_destruct;
- (id)description;
- (_Bool)isEqual:(id)arg1;
- (id)accessibilityText;
- (void)reload;

@end

