//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FHTemplateBaseCell.h"

@class CDPSpaceView, UIView;

@interface FHTemplatePromotionCell : FHTemplateBaseCell
{
    CDPSpaceView *_promotionView;
    UIView *_animationMaskView;
}

@property(retain, nonatomic) UIView *animationMaskView; // @synthesize animationMaskView=_animationMaskView;
@property(retain, nonatomic) CDPSpaceView *promotionView; // @synthesize promotionView=_promotionView;
- (void).cxx_destruct;
- (id)viewsNeedExposure;
- (void)dealloc;
- (void)layoutSubviews;
- (void)stopAnimation;
- (void)startAnimation;
- (void)clearAnimationWithSpaceView:(id)arg1;
- (void)animationWithSpaceView:(id)arg1;
- (void)setSpaceView:(id)arg1 cellModel:(id)arg2;
- (void)prepareForReuse;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

