//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class FHAssetsHeaderMarkModel, UIImageView;

@interface FHWeeklyProfitControl : UIControl
{
    UIImageView *_icon;
    FHAssetsHeaderMarkModel *_mark;
}

@property(retain, nonatomic) FHAssetsHeaderMarkModel *mark; // @synthesize mark=_mark;
@property(retain, nonatomic) UIImageView *icon; // @synthesize icon=_icon;
- (void).cxx_destruct;
- (void)setHighlighted:(_Bool)arg1;
- (void)layoutSubviews;
- (void)updateWithImageUrl:(id)arg1 cardTypeId:(id)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

