//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface finscbffMarketChartFlagItemPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *expId; // @dynamic expId;
@property(readonly) _Bool hasExpId; // @dynamic hasExpId;
@property(readonly) _Bool hasName; // @dynamic hasName;
@property(readonly) _Bool hasSymbol; // @dynamic hasSymbol;
@property(readonly) _Bool hasYiDongTime; // @dynamic hasYiDongTime;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) NSString *symbol; // @dynamic symbol;
@property(nonatomic) long long yiDongTime; // @dynamic yiDongTime;

@end

