//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "FMLTwoLevelIndex.h"

@interface FMLNotificationCenterObserverModelNameIndex : FMLTwoLevelIndex
{
}

- (id)indexValueForObserverKey:(id)arg1;
- (id)blockKeyArrayForObserverKey:(id)arg1 modelName:(id)arg2;
- (id)blockKeysWithObserverKey:(id)arg1 modelName:(id)arg2;
- (id)blockKeysWithObserverKey:(id)arg1;
- (void)removeBlockKeyInfo:(id)arg1;
- (void)addBlockKeyInfo:(id)arg1;

@end

