//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIButton, UIImageView, UILabel;
@protocol GO2OPayViewDelegate;

@interface GO2OPayView : UIView
{
    id <GO2OPayViewDelegate> _delegate;
    UIImageView *_iconImageView;
    UIImageView *_iconDescImageView;
    UILabel *_descLabel;
    UIButton *_payButton;
    UIView *_containerView;
}

@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UIButton *payButton; // @synthesize payButton=_payButton;
@property(retain, nonatomic) UILabel *descLabel; // @synthesize descLabel=_descLabel;
@property(retain, nonatomic) UIImageView *iconDescImageView; // @synthesize iconDescImageView=_iconDescImageView;
@property(retain, nonatomic) UIImageView *iconImageView; // @synthesize iconImageView=_iconImageView;
@property(nonatomic) __weak id <GO2OPayViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)updateWithRecommendDesc:(id)arg1 payInfo:(id)arg2;
- (void)pay;
- (void)initPayView;
- (id)init;

@end

