//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GO2OBaseViewController.h"

#import "GO2OFilterMenuDelegate-Protocol.h"
#import "GO2OStackedGridHeaderProtocol-Protocol.h"
#import "GO2OStackedGridLayoutDelegate-Protocol.h"
#import "GO2OTabbarHeaderProtocol-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"
#import "UITableViewDataSource-Protocol.h"
#import "UITableViewDelegate-Protocol.h"

@class GO2OCommonTabbar, GO2OFilterMenuHeaderView, GO2ORefreshFooter, GO2OStackedGridHeaderView, GO2OTabbarFooterView, NSArray, NSDictionary, NSMutableArray, NSMutableDictionary, NSString, O2OTemplateDownloadResult, UICollectionView, UITableView, UIView;

@interface GO2OMistBaseViewController : GO2OBaseViewController <GO2OTabbarHeaderProtocol, UITableViewDataSource, UITableViewDelegate, GO2OFilterMenuDelegate, UICollectionViewDelegate, UICollectionViewDataSource, GO2OStackedGridLayoutDelegate, GO2OStackedGridHeaderProtocol>
{
    NSMutableDictionary *_allHeaders;
    NSMutableDictionary *_allTabStates;
    _Bool _pagingForNoTab;
    _Bool _lockOuterScrollView;
    _Bool _stackedGridPaging;
    UITableView *_tableView;
    NSString *_templatePage;
    NSArray *_blocksArray;
    NSMutableArray *_sections;
    NSMutableDictionary *_customData;
    double _scrollOffset;
    GO2OCommonTabbar *_pagingTabbar;
    long long _pagingTabbarSection;
    NSMutableDictionary *_headers;
    NSMutableDictionary *_tabStates;
    NSMutableArray *_refreshViewModels;
    GO2OTabbarFooterView *_finishLoadingAllView;
    GO2ORefreshFooter *_refreshFooter;
    GO2ORefreshFooter *_stackedGridRefreshFooter;
    NSDictionary *_spmDict;
    NSString *_infoType;
    long long _pageIndexForNoTab;
    NSString *_pagingItemTemplateId;
    NSString *_menuBizType;
    NSDictionary *_selectedMenus;
    GO2OFilterMenuHeaderView *_filterHeader;
    UIView *_menuEmptyView;
    long long _filterMenuSection;
    NSString *_stackedGridBizType;
    GO2OStackedGridHeaderView *_stackedGridHeader;
    long long _stackedGridSection;
    UICollectionView *_collectionView;
    double _lastOffsetY;
    O2OTemplateDownloadResult *_templateInfo;
    NSArray *_denylistForCachedBlock;
}

@property(readonly, copy, nonatomic) NSArray *denylistForCachedBlock; // @synthesize denylistForCachedBlock=_denylistForCachedBlock;
@property(retain, nonatomic) O2OTemplateDownloadResult *templateInfo; // @synthesize templateInfo=_templateInfo;
@property(nonatomic) _Bool stackedGridPaging; // @synthesize stackedGridPaging=_stackedGridPaging;
@property(nonatomic) _Bool lockOuterScrollView; // @synthesize lockOuterScrollView=_lockOuterScrollView;
@property(nonatomic) double lastOffsetY; // @synthesize lastOffsetY=_lastOffsetY;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) long long stackedGridSection; // @synthesize stackedGridSection=_stackedGridSection;
@property(retain, nonatomic) GO2OStackedGridHeaderView *stackedGridHeader; // @synthesize stackedGridHeader=_stackedGridHeader;
@property(copy, nonatomic) NSString *stackedGridBizType; // @synthesize stackedGridBizType=_stackedGridBizType;
@property(nonatomic) long long filterMenuSection; // @synthesize filterMenuSection=_filterMenuSection;
@property(retain, nonatomic) UIView *menuEmptyView; // @synthesize menuEmptyView=_menuEmptyView;
@property(retain, nonatomic) GO2OFilterMenuHeaderView *filterHeader; // @synthesize filterHeader=_filterHeader;
@property(copy, nonatomic) NSDictionary *selectedMenus; // @synthesize selectedMenus=_selectedMenus;
@property(copy, nonatomic) NSString *menuBizType; // @synthesize menuBizType=_menuBizType;
@property(copy, nonatomic) NSString *pagingItemTemplateId; // @synthesize pagingItemTemplateId=_pagingItemTemplateId;
@property(nonatomic) long long pageIndexForNoTab; // @synthesize pageIndexForNoTab=_pageIndexForNoTab;
@property(copy, nonatomic) NSString *infoType; // @synthesize infoType=_infoType;
@property(nonatomic) _Bool pagingForNoTab; // @synthesize pagingForNoTab=_pagingForNoTab;
@property(retain, nonatomic) NSDictionary *spmDict; // @synthesize spmDict=_spmDict;
@property(nonatomic) __weak GO2ORefreshFooter *stackedGridRefreshFooter; // @synthesize stackedGridRefreshFooter=_stackedGridRefreshFooter;
@property(nonatomic) __weak GO2ORefreshFooter *refreshFooter; // @synthesize refreshFooter=_refreshFooter;
@property(retain, nonatomic) GO2OTabbarFooterView *finishLoadingAllView; // @synthesize finishLoadingAllView=_finishLoadingAllView;
@property(retain, nonatomic) NSMutableArray *refreshViewModels; // @synthesize refreshViewModels=_refreshViewModels;
@property(retain, nonatomic) NSMutableDictionary *tabStates; // @synthesize tabStates=_tabStates;
@property(retain, nonatomic) NSMutableDictionary *headers; // @synthesize headers=_headers;
@property(nonatomic) long long pagingTabbarSection; // @synthesize pagingTabbarSection=_pagingTabbarSection;
@property(retain, nonatomic) GO2OCommonTabbar *pagingTabbar; // @synthesize pagingTabbar=_pagingTabbar;
@property(nonatomic) double scrollOffset; // @synthesize scrollOffset=_scrollOffset;
@property(retain, nonatomic) NSMutableDictionary *customData; // @synthesize customData=_customData;
@property(retain, nonatomic) NSMutableArray *sections; // @synthesize sections=_sections;
@property(retain, nonatomic) NSArray *blocksArray; // @synthesize blocksArray=_blocksArray;
@property(retain, nonatomic) NSString *templatePage; // @synthesize templatePage=_templatePage;
@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
- (void).cxx_destruct;
- (void)resetTableViewAndCollectionViewBoundsAnimated:(_Bool)arg1;
- (id)spmExtraInfo;
- (id)menuRequestInfo;
- (id)pagingRequestInfo;
- (id)tabRequestInfo;
- (void)queryStackedGridItemsFinishWithTabbar:(id)arg1 tabSelectedIndex:(long long)arg2 originTabSelectedIndex:(long long)arg3 tagbar:(id)arg4 tagSelectedIndex:(long long)arg5 items:(id)arg6 hasMore:(_Bool)arg7 error:(id)arg8;
- (void)prepareForQueryStackedGridItems;
- (void)stackedGridHeader:(id)arg1 tabbar:(id)arg2 didSelectItemAtIndex:(long long)arg3 originIndex:(long long)arg4;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 itemInsetForSection:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3 sectionWidth:(double)arg4;
- (double)collectionView:(id)arg1 layout:(id)arg2 headerHeightForSection:(long long)arg3;
- (long long)collectionView:(id)arg1 layout:(id)arg2 numberOfColumnsInSection:(long long)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (void)scrollMenuToTop;
- (void)didMenuToggled:(id)arg1;
- (void)didMenuSelected:(id)arg1;
- (void)didMenuExpanded:(id)arg1;
- (void)menuViewPopupWillHide;
- (void)menuViewPopupWillShow:(id)arg1;
- (void)dismissMenuView;
- (void)updateMenuItems:(_Bool)arg1;
- (void)tabbar:(id)arg1 didSelectItemAtIndex:(long long)arg2 originIndex:(long long)arg3;
- (void)loadMoreDataForStackedGridLayout;
- (void)loadMoreDataWithInfoType:(id)arg1 index:(long long)arg2;
- (void)loadMoreDataWithTabbar:(id)arg1 section:(long long)arg2 index:(long long)arg3;
- (void)setupStackedGridLayoutRefreshFooter;
- (void)setupRefreshFooter;
- (_Bool)hasRefreshFooter;
- (_Bool)stackedGridLayoutHasRefreshFooter;
- (void)scrollViewDidScroll:(id)arg1;
- (double)tableView:(id)arg1 heightForFooterInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForFooterInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)renderStackedLayoutWithSections:(id)arg1 item:(id)arg2 formerItems:(id)arg3 blockDict:(id)arg4;
- (void)renderFilterMenuWithSections:(id)arg1 item:(id)arg2 formerItems:(id)arg3;
- (_Bool)renderTabWithSections:(id)arg1 item:(id)arg2 formerItems:(id)arg3 blockDict:(id)arg4;
- (void)renderBlock:(id)arg1 fromCache:(_Bool)arg2 customData:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (id)filterBlockInfo:(id)arg1;
- (void)createView;
- (void)viewDidLoad;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

