//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class ACCElderData, UILabel;

@interface GreenWalletElderVerifyView : UIView
{
    CDUnknownBlockType _blockVerify;
    ACCElderData *_data;
    UILabel *_labelTitle;
}

@property(retain, nonatomic) UILabel *labelTitle; // @synthesize labelTitle=_labelTitle;
@property(retain, nonatomic) ACCElderData *data; // @synthesize data=_data;
@property(copy, nonatomic) CDUnknownBlockType blockVerify; // @synthesize blockVerify=_blockVerify;
- (void).cxx_destruct;
- (void)actionTap:(id)arg1;
- (void)createSubviews;
- (id)initWithFrame:(struct CGRect)arg1 data:(id)arg2;

@end

