//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "APCommonItemProtocol-Protocol.h"
#import "NSCopying-Protocol.h"

@class GTDMessage, NSString;

@interface GTDRecentContact : NSObject <APCommonItemProtocol, NSCopying>
{
    NSString *_groupId;
    NSString *_title;
    NSString *_multiMemo;
    NSString *_singleMemo;
    NSString *_afterClickConfig;
    NSString *_actionText;
    NSString *_actionLink;
    NSString *_icon;
    NSString *_bizLink;
    long long _msgCount;
    GTDMessage *_recentWillExpireMsg;
    GTDMessage *_latestMsg;
}

@property(copy, nonatomic) GTDMessage *latestMsg; // @synthesize latestMsg=_latestMsg;
@property(copy, nonatomic) GTDMessage *recentWillExpireMsg; // @synthesize recentWillExpireMsg=_recentWillExpireMsg;
@property(nonatomic) long long msgCount; // @synthesize msgCount=_msgCount;
@property(copy, nonatomic) NSString *bizLink; // @synthesize bizLink=_bizLink;
@property(copy, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(copy, nonatomic) NSString *actionLink; // @synthesize actionLink=_actionLink;
@property(copy, nonatomic) NSString *actionText; // @synthesize actionText=_actionText;
@property(copy, nonatomic) NSString *afterClickConfig; // @synthesize afterClickConfig=_afterClickConfig;
@property(copy, nonatomic) NSString *singleMemo; // @synthesize singleMemo=_singleMemo;
@property(copy, nonatomic) NSString *multiMemo; // @synthesize multiMemo=_multiMemo;
@property(copy, nonatomic) NSString *title; // @synthesize title=_title;
@property(copy, nonatomic) NSString *groupId; // @synthesize groupId=_groupId;
- (void).cxx_destruct;
- (void)updateFieldsWithLatestMsg;
- (id)iconUrl;
- (id)commonSubTitle;
- (id)commonTitle;
- (id)commonID;
- (id)copyWithZone:(struct _NSZone *)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

