//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class H5MainLink;

@protocol H5MainLinkDelegate
- (void)mainLinkDidFinish:(H5MainLink *)arg1;
- (void)mainLinkTimeout:(H5MainLink *)arg1;
- (void)mainLinkCancelledByUser:(H5MainLink *)arg1;
@end

