//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface H5UseManager : NSObject
{
}

+ (void)swizzleClassName:(id)arg1 origSelectorName:(id)arg2 newSelector:(SEL)arg3;
+ (void)useful_RequestsetHTTPHeader;
+ (void)useful_RequestallHTTPHeaderFields;
+ (void)allUseful;
+ (void)load;
- (void)h5_setValue:(id)arg1 forHTTPHeaderField:(id)arg2;
- (id)h5_allHTTPHeaderFields;

@end

