//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface HCFetchIndexReq : NSObject
{
    _Bool _duringLaunch;
    _Bool _useDBCache;
    _Bool _scrollToTopWhenLoad;
    _Bool _silentWhenBackground;
    _Bool _donotFetchIndexRpc;
    _Bool _showLoadingView;
    _Bool _refreshAdBanner;
}

@property(nonatomic) _Bool refreshAdBanner; // @synthesize refreshAdBanner=_refreshAdBanner;
@property(nonatomic) _Bool showLoadingView; // @synthesize showLoadingView=_showLoadingView;
@property(nonatomic) _Bool donotFetchIndexRpc; // @synthesize donotFetchIndexRpc=_donotFetchIndexRpc;
@property(nonatomic) _Bool silentWhenBackground; // @synthesize silentWhenBackground=_silentWhenBackground;
@property(nonatomic) _Bool scrollToTopWhenLoad; // @synthesize scrollToTopWhenLoad=_scrollToTopWhenLoad;
@property(nonatomic) _Bool useDBCache; // @synthesize useDBCache=_useDBCache;
@property(nonatomic) _Bool duringLaunch; // @synthesize duringLaunch=_duringLaunch;
- (id)init;

@end

