//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface HCHomeRPCManager : NSObject
{
}

+ (id)fetchMoreHomeDataWithLastFeedID:(id)arg1 viewController:(id)arg2 onComplete:(CDUnknownBlockType)arg3;
+ (id)fetchHomeDataWithLocation:(id)arg1 lastQueryTime:(id)arg2 refreshMode:(id)arg3 viewController:(id)arg4 onComplete:(CDUnknownBlockType)arg5;

@end

