//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class HomeCardDeviceAI, HomeCardLBSManager, HomeCardWifiInfo, NSMutableDictionary;

@interface HCRpcReqExtMaker : NSObject
{
    NSMutableDictionary *_extMap;
    HomeCardDeviceAI *_deviceAI;
    HomeCardLBSManager *_lbsManager;
    HomeCardWifiInfo *_wifiInfo;
}

@property(retain, nonatomic) HomeCardWifiInfo *wifiInfo; // @synthesize wifiInfo=_wifiInfo;
@property(retain, nonatomic) HomeCardLBSManager *lbsManager; // @synthesize lbsManager=_lbsManager;
- (void).cxx_destruct;
- (void)addAsyncTask:(CDUnknownBlockType)arg1;
- (id)getSSIDInfo:(id)arg1;
- (id)ssidInfoReadStrategy;
- (_Bool)ssidInfoEnable;
- (id)getPhoneLevel;
- (void)reqestRpcExtSource:(id)arg1 worker:(id)arg2 params:(id)arg3 onFinish:(CDUnknownBlockType)arg4 onGeoFinish:(CDUnknownBlockType)arg5;
- (void)setDeviceAI:(id)arg1;
- (id)init;

@end

