//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class AUActionSheet, CTChatPlaceholderTextView, HiChatItem, HiChatSession, MBProgressHUD, NSArray, NSDictionary, NSIndexPath, NSString, UIScrollView, UITableViewCell, UIView, UIViewController;
@protocol CTInputViewGeneralProtocol;

@protocol HiChatEngineContainerDelegate <NSObject>
@property(nonatomic) _Bool hasMore;
@property(readonly, nonatomic) struct CGSize tableContentSize;
@property(readonly, nonatomic) struct CGPoint tableContentOffset;
- (void)callPhoneActionWithPhoneNo:(NSString *)arg1;
- (double)getTopInset;
- (void)didDismissToastView:(UIView *)arg1 withIdentifier:(NSString *)arg2;
- (void)dismissAllToastView;
- (void)dismissToastViewWithIdentifier:(NSString *)arg1;
- (void)showCoverAlertViewInView:(void (^)(UIView *))arg1;
- (_Bool)showToastView:(UIView *)arg1 identifier:(NSString *)arg2 origin:(struct CGPoint)arg3 duration:(double)arg4 appearAnimation:(void (^)(void (^)(void)))arg5 dismissAnimation:(void (^)(void (^)(void)))arg6 dismissBlock:(void (^)(void))arg7;
- (_Bool)showToastView:(UIView *)arg1 identifier:(NSString *)arg2 origin:(struct CGPoint)arg3 duration:(double)arg4 dismissBlock:(void (^)(void))arg5;
- (NSString *)vcIdentifer;
- (void)presentViewController:(UIViewController *)arg1 animated:(_Bool)arg2;
- (_Bool)presentedViewControllerExists;
- (_Bool)isCellVisible:(UITableViewCell *)arg1;
- (struct CGRect)changedOrigFrameInPhotoBrowserAtIndex:(long long)arg1;
- (NSArray *)imageCellsInfoWithVisiableCells;
- (UIView *)findActiveWidgetInCellWithIndex:(long long)arg1;
- (struct CGRect)multimediaOrigFrameWithIdentifier:(NSString *)arg1 clientMsgId:(NSString *)arg2 index:(long long)arg3;
- (void)noticeEmojiViewHaveText:(_Bool)arg1;
- (void)refreshToolBoxAppCenterData:(NSArray *)arg1 stageCode:(NSString *)arg2;
- (void)reloadToolBoxAppWithAppId:(NSString *)arg1;
- (void)updateToolBoxAppWithAppId:(NSString *)arg1 progress:(double)arg2;
- (void)refreshRedDotStatus:(_Bool)arg1;
- (_Bool)canOpenTopBanner;
- (void)topBannerFullScreenMode;
- (void)topBannerHalfScreenMode;
- (void)chatEngineContainerCloseTopBannerWithAnimation:(_Bool)arg1;
- (_Bool)topBannerOpened;
- (void)setupQuickMenuBarContainer;
- (void)setupTopBannerContainer;
- (void)refreshTopBannerWithData:(NSArray *)arg1;
- (void)refreshQuickMenuBarActionItem:(NSArray *)arg1;
- (void)refreshToolBoxAppCenterData:(NSArray *)arg1;
- (void)hideToolbox:(id <CTInputViewGeneralProtocol>)arg1 animation:(_Bool)arg2;
- (void)generalToolBoxWillWakeupWithCategory:(NSString *)arg1 inputView:(id <CTInputViewGeneralProtocol>)arg2;
- (void)showLinkCardPopView:(UIView *)arg1 withShowDuration:(NSString *)arg2;
- (void)hideLinkCardAnimate:(_Bool)arg1;
- (void)closeMoviePicker:(_Bool)arg1;
- (void)showMoviePikcer:(_Bool)arg1;
- (_Bool)matchingOfflineCellTemplate:(NSString *)arg1;
- (_Bool)matchingCellTemplate:(NSString *)arg1 messageMinVersion:(NSString *)arg2;
- (void)pushViewController:(UIViewController *)arg1 animated:(_Bool)arg2;
- (void)openUrl:(NSDictionary *)arg1 urlStr:(NSString *)arg2;
- (void)popBack;
- (void)presentModalTagToastWithIcon:(int)arg1 text:(NSString *)arg2 duration:(double)arg3 delay:(double)arg4 logTag:(NSString *)arg5 completion:(void (^)(void))arg6;
- (void)dismissHUDAnimated:(_Bool)arg1;
- (MBProgressHUD *)showHUDAnimated:(_Bool)arg1;
- (void)presentToastWithIcon:(int)arg1 text:(NSString *)arg2 duration:(double)arg3;
- (void)dismissVoiceToastView:(UIView *)arg1;
- (void)showVoiceToastView:(UIView *)arg1;
- (void)showMailComposerWithMailAddr:(NSString *)arg1;
- (void)showActionSheet:(AUActionSheet *)arg1;
- (void)clearTextInput;
- (void)showOrHideUnreadCount:(_Bool)arg1;
- (void)endEditInputView;
- (void)closeInputBox;
- (void)closeToolsView;
- (void)showToolsView;
- (void)toolBoxEmojiComponenEmojiWillDelete;
- (void)toolBoxEmojiComponenEmojiWillSend;
- (void)toolBoxEmojiComponenEmojiTaped:(id)arg1;
- (CTChatPlaceholderTextView *)internalInputTextView;
- (_Bool)isTextInputFirstResponder;
- (void)enterTextInputMode;
- (NSString *)currentInputText;
- (void)configInputText:(NSString *)arg1;
- (void)saveDraft:(NSString *)arg1 command:(NSString *)arg2;
- (NSString *)inputStyleOfInputContainer;
- (void)configInputContainerInputStyle:(NSString *)arg1;
- (void)configInputContainerInputMode:(int)arg1;
- (void)closeFollowView;
- (void)showRecentPhoto;
- (void)showImagePicker;
- (void)addRefreshTaskWithBlock:(void (^)(void))arg1 taskID:(NSString *)arg2;
- (void)createRefreshTaskWithTaskID:(NSString *)arg1;
- (unsigned long long)numberOfSections;
- (NSIndexPath *)indexPathForCell:(UITableViewCell *)arg1;
- (void)removeAndUpdateTableCellWithIndexs:(NSArray *)arg1;
- (_Bool)checkShouldHideUnreadPickerByIndexPath:(NSIndexPath *)arg1;
- (_Bool)mfScrolling;
- (_Bool)isCurrentTableView:(UIScrollView *)arg1;
- (NSString *)draftOfInputView;
- (_Bool)shouldLoadNewPage;
- (_Bool)shoulLoadBefore;
- (_Bool)isTableViewShowBottom:(long long)arg1;
- (void)loadingViewShow:(_Bool)arg1;
- (void)reloadTableView;
- (void)refreshTitle;
- (void)socialItemInfoDidUpdate:(HiChatItem *)arg1;
- (void)socialSessionInfoDidUpdate:(HiChatSession *)arg1;
- (void)modifyLayoutInformationAtIndex:(unsigned long long)arg1 dimIndex:(unsigned long long)arg2;
- (void)configTableContentOffset:(struct CGPoint)arg1 animated:(_Bool)arg2;
- (void)removeShareSourceWithSeed:(NSString *)arg1;
- (void)removeTranslateContentWithIndex:(long long)arg1;
- (void)removeShareSourceWithIndex:(long long)arg1;
- (void)removeLayoutInformationWithIndex:(long long)arg1;
- (void)autoScrollWithDataItems:(NSArray *)arg1 callback:(void (^)(long long))arg2;
- (void)scrollToRowAtIndexPath:(NSIndexPath *)arg1 atScrollPosition:(long long)arg2 animated:(_Bool)arg3;
- (void)scrollTableViewToBottomWithAnimation:(_Bool)arg1 scorllCondition:(_Bool)arg2;
@end

