//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface HomeCardConfig : NSObject
{
}

+ (id)cardidsForceRenderWithNativeEngine;
+ (id)HCLbsInfo;
+ (_Bool)enableMessageCardForInternationalRegion;
+ (_Bool)enableMessageCard;
+ (_Bool)needShowHideMenu;
+ (_Bool)needClearHomeCardSnap;
+ (_Bool)isAppStageViewPlanNew;
+ (_Bool)isAppInReview;
+ (long long)HC_PULL_STAGE_GUIDE_SHOWNED_DURATION;
+ (id)OPT_HOMECARD_REFRESH_TYPE;
+ (_Bool)H5VC_TOP_SHOULD_NOT_DO_SNAP;
+ (_Bool)elevatorScrollAnimated;
+ (id)widgetPageStyle;
+ (long long)hc_snap_timeout;
+ (long long)hc_snap_delay;
+ (_Bool)hc_lanuchPic;
+ (long long)hc_delay_rmlanuchPic;
+ (id)homeTemplateSpace;
+ (long long)homeLocationTimeout;
+ (long long)homeLocationCacheTime;
+ (_Bool)needConfirmOnDeleteCategory;
+ (_Bool)isHighDevice;
+ (_Bool)cacheCardAsyncDisplay;
+ (long long)syncDelayDuration;
+ (long long)getAutoRefeshDuration;
+ (long long)getAutoRefreshDurationV2;
+ (id)getConfigs;

@end

