//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class ACApp, UIImageView, UILabel;

@interface HReplaceAppCustomView : UIView
{
    UILabel *_noticeLabel;
    UILabel *_noticeLabelGray;
    UIImageView *_backgroundImageView;
    UILabel *_replaceLabel;
    ACApp *_replacingApp;
    ACApp *_replacedApp;
    UIView *_replacingAppView;
    UIView *_replacedAppView;
    UILabel *_replacingAppLabel;
    UILabel *_replacedAppLabel;
    UILabel *_rarelyUsedLabel;
}

@property(retain, nonatomic) UILabel *rarelyUsedLabel; // @synthesize rarelyUsedLabel=_rarelyUsedLabel;
@property(retain, nonatomic) UILabel *replacedAppLabel; // @synthesize replacedAppLabel=_replacedAppLabel;
@property(retain, nonatomic) UILabel *replacingAppLabel; // @synthesize replacingAppLabel=_replacingAppLabel;
@property(retain, nonatomic) UIView *replacedAppView; // @synthesize replacedAppView=_replacedAppView;
@property(retain, nonatomic) UIView *replacingAppView; // @synthesize replacingAppView=_replacingAppView;
@property(retain, nonatomic) ACApp *replacedApp; // @synthesize replacedApp=_replacedApp;
@property(retain, nonatomic) ACApp *replacingApp; // @synthesize replacingApp=_replacingApp;
@property(retain, nonatomic) UILabel *replaceLabel; // @synthesize replaceLabel=_replaceLabel;
@property(retain, nonatomic) UIImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(retain, nonatomic) UILabel *noticeLabelGray; // @synthesize noticeLabelGray=_noticeLabelGray;
@property(retain, nonatomic) UILabel *noticeLabel; // @synthesize noticeLabel=_noticeLabel;
- (void).cxx_destruct;
- (id)appViewWithApp:(id)arg1;
- (void)layoutSubviews;
- (id)initWithReplacedApp:(id)arg1 replacingApp:(id)arg2;

@end

