//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface HUtils : NSObject
{
}

+ (long long)homePageColumnNumber;
+ (long long)homePageAppsCount;
+ (_Bool)isDynamicAnimationRollback;
+ (_Bool)isNewAddedTagPositionRollback;
+ (_Bool)isGridViewNeedLayoutRollback;
+ (_Bool)isRecoverMenuGroundViewRollback;
+ (_Bool)isHomeNewVersion;
+ (_Bool)isNewDecoration;
+ (_Bool)isSocrates;
+ (_Bool)isAddShowBottomUp;
+ (void)gotoAllAppWithParams:(id)arg1;
+ (double)scaleFromTextFontSizeLevel:(long long)arg1;
+ (double)floatByScaleFloatUsingTextFontSizeLevel:(double)arg1;
+ (double)currentTextFontSizeScale;
+ (long long)currentTextFontSizeLevel;
+ (_Bool)canScaleFontSize;
+ (long long)newAllAppsPageType;
+ (void)setHighlight:(id)arg1 highlight:(_Bool)arg2 animated:(_Bool)arg3;
+ (void)playTapAnimation:(id)arg1 complete:(CDUnknownBlockType)arg2;
+ (id)badgeExtInfoQueryString:(id)arg1;
+ (id)queryParamsStringFromQueryParams:(id)arg1;
+ (id)stageScheme:(id)arg1 withBadgeExtInfo:(id)arg2;
+ (void)openAppItem:(id)arg1 bizExtInfo:(id)arg2 markString:(id)arg3 badgeExtInfo:(id)arg4 chInfo:(id)arg5 reportMarkClick:(_Bool)arg6;
+ (void)openAppItem:(id)arg1 bizExtInfo:(id)arg2 markString:(id)arg3 badgeExtInfo:(id)arg4 chInfo:(id)arg5;
+ (void)openAppItem:(id)arg1 bizExtInfo:(id)arg2 markString:(id)arg3;
+ (id)timeLimitDescConfiged;
+ (id)getLogAppIds:(id)arg1;
+ (double)screenWidth;
+ (long long)rowCount:(long long)arg1 columnCount:(long long)arg2;
+ (_Bool)isBlankString:(id)arg1;
+ (double)getScaledPxWithPx:(double)arg1 isScale:(unsigned char)arg2;
+ (double)getLargerPxWithPx:(double)arg1;
+ (id)getDefaultAppIcon;
+ (id)getBadgeManager;
+ (id)getAppManagerService;
+ (id)getAppManager;
+ (id)fromHexValue:(unsigned long long)arg1 alpha:(double)arg2;

@end

