//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSArray, NSString;

@interface infosecContentDetailOutputResultPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSArray *checkServiceResponseOutputs; // @dynamic checkServiceResponseOutputs;
@property(retain, nonatomic) NSString *content; // @dynamic content;
@property(retain, nonatomic) NSString *dataType; // @dynamic dataType;
@property(readonly) _Bool hasContent; // @dynamic hasContent;
@property(readonly) _Bool hasDataType; // @dynamic hasDataType;
@property(readonly) _Bool hasMd5; // @dynamic hasMd5;
@property(readonly) _Bool hasResultCode; // @dynamic hasResultCode;
@property(retain, nonatomic) NSString *md5; // @dynamic md5;
@property(retain, nonatomic) NSString *resultCode; // @dynamic resultCode;
@property(retain, nonatomic) NSArray *riskLabels; // @dynamic riskLabels;

@end

