//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface ISampleControl : NSObject
{
    _Bool _shouldSample;
    _Bool _shouldSampleLevel1;
    _Bool _shouldSampleLevel2;
    _Bool _shouldSampleLevel3;
    unsigned long long _rate;
    unsigned long long _level1Rate;
    unsigned long long _level2Rate;
    unsigned long long _level3Rate;
}

@property(nonatomic) _Bool shouldSampleLevel3; // @synthesize shouldSampleLevel3=_shouldSampleLevel3;
@property(nonatomic) _Bool shouldSampleLevel2; // @synthesize shouldSampleLevel2=_shouldSampleLevel2;
@property(nonatomic) _Bool shouldSampleLevel1; // @synthesize shouldSampleLevel1=_shouldSampleLevel1;
@property(nonatomic) unsigned long long level3Rate; // @synthesize level3Rate=_level3Rate;
@property(nonatomic) unsigned long long level2Rate; // @synthesize level2Rate=_level2Rate;
@property(nonatomic) unsigned long long level1Rate; // @synthesize level1Rate=_level1Rate;
@property(nonatomic) unsigned long long rate; // @synthesize rate=_rate;
@property(nonatomic) _Bool shouldSample; // @synthesize shouldSample=_shouldSample;
- (unsigned long long)rateForLevel:(long long)arg1;
- (_Bool)shouldSampleForLevel:(long long)arg1;
- (id)init;

@end

