//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KBCONSUMEBaseRpcResponse.h"

@class KBCONSUMEOrderInfo, NSString;

@interface KBCONSUMEOrderRefreshResponseEx : KBCONSUMEBaseRpcResponse
{
    NSString *_needRemove;
    KBCONSUMEOrderInfo *_orderInfo;
}

@property(retain, nonatomic) KBCONSUMEOrderInfo *orderInfo; // @synthesize orderInfo=_orderInfo;
@property(retain, nonatomic) NSString *needRemove; // @synthesize needRemove=_needRemove;
- (void).cxx_destruct;

@end

