//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KBCONTENTPRODBaseRpcReq.h"

@class KBCONTENTPRODCollectSubject, NSDictionary, NSString;

@interface KBCONTENTPRODCollectAdminRpcReq : KBCONTENTPRODBaseRpcReq
{
    _Bool _saveObjectData;
    _Bool _countByObject;
    NSString *_action;
    KBCONTENTPRODCollectSubject *_collectSubject;
    NSDictionary *_ext;
}

+ (Class)extElementClass;
@property(retain, nonatomic) NSDictionary *ext; // @synthesize ext=_ext;
@property(nonatomic) _Bool countByObject; // @synthesize countByObject=_countByObject;
@property(nonatomic) _Bool saveObjectData; // @synthesize saveObjectData=_saveObjectData;
@property(retain, nonatomic) KBCONTENTPRODCollectSubject *collectSubject; // @synthesize collectSubject=_collectSubject;
@property(retain, nonatomic) NSString *action; // @synthesize action=_action;
- (void).cxx_destruct;

@end

