//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KBCONTENTPRODBaseResult.h"

@class NSArray;

@interface KBCONTENTPRODRecommendAuthorResp : KBCONTENTPRODBaseResult
{
    NSArray *_authorList;
}

+ (Class)authorListElementClass;
@property(retain, nonatomic) NSArray *authorList; // @synthesize authorList=_authorList;
- (void).cxx_destruct;

@end

