//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KBCOMMENTBaseRpcReq.h"

@class NSString;

@interface KBCOMMENTCommentReplyQueryRpcReq : KBCOMMENTBaseRpcReq
{
    int _pageSie;
    NSString *_subjectId;
    NSString *_subjectType;
    NSString *_sceneCode;
    NSString *_lastReplyId;
}

@property(nonatomic) int pageSie; // @synthesize pageSie=_pageSie;
@property(retain, nonatomic) NSString *lastReplyId; // @synthesize lastReplyId=_lastReplyId;
@property(retain, nonatomic) NSString *sceneCode; // @synthesize sceneCode=_sceneCode;
@property(retain, nonatomic) NSString *subjectType; // @synthesize subjectType=_subjectType;
@property(retain, nonatomic) NSString *subjectId; // @synthesize subjectId=_subjectId;
- (void).cxx_destruct;

@end

