//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "KBRETAILPRODToString.h"

@class DTBoolean, NSArray, NSDate, NSString;

@interface KBRETAILPRODRetailMarketingInfo : KBRETAILPRODToString
{
    _Bool _autoObtain;
    _Bool _hasUnused;
    _Bool _canUse;
    _Bool _oversold;
    _Bool _enableOnlineDeposit;
    _Bool _isNewMemberVoucher;
    int _needStrikethrough;
    NSString *_mid;
    NSString *_icon;
    NSString *_iconUrl;
    NSString *_image;
    NSString *_title;
    NSString *_subTitle;
    NSString *_slogan;
    NSArray *_descList;
    NSString *_url;
    NSString *_current;
    NSString *_original;
    KBRETAILPRODRetailMarketingInfo *_discountReduce;
    NSString *_itemUnit;
    NSString *_itemType;
    NSString *_useDesc;
    NSString *_mainDesc;
    NSString *_useLimitDesc;
    NSDate *_gmtStart;
    NSDate *_gmtEnd;
    NSArray *_activityList;
    NSString *_customTag;
    NSString *_activityLogo;
    NSString *_couponPromo;
    NSString *_giftDesc;
    NSString *_voucherType;
    NSString *_campId;
    DTBoolean *_singleItem;
    NSString *_brandName;
    NSString *_templateType;
}

+ (Class)activityListElementClass;
+ (Class)descListElementClass;
@property(retain, nonatomic) NSString *templateType; // @synthesize templateType=_templateType;
@property(nonatomic) _Bool isNewMemberVoucher; // @synthesize isNewMemberVoucher=_isNewMemberVoucher;
@property(retain, nonatomic) NSString *brandName; // @synthesize brandName=_brandName;
@property(nonatomic) _Bool enableOnlineDeposit; // @synthesize enableOnlineDeposit=_enableOnlineDeposit;
@property(retain, nonatomic) DTBoolean *singleItem; // @synthesize singleItem=_singleItem;
@property(retain, nonatomic) NSString *campId; // @synthesize campId=_campId;
@property(retain, nonatomic) NSString *voucherType; // @synthesize voucherType=_voucherType;
@property(retain, nonatomic) NSString *giftDesc; // @synthesize giftDesc=_giftDesc;
@property(nonatomic) _Bool oversold; // @synthesize oversold=_oversold;
@property(retain, nonatomic) NSString *couponPromo; // @synthesize couponPromo=_couponPromo;
@property(nonatomic) int needStrikethrough; // @synthesize needStrikethrough=_needStrikethrough;
@property(retain, nonatomic) NSString *activityLogo; // @synthesize activityLogo=_activityLogo;
@property(retain, nonatomic) NSString *customTag; // @synthesize customTag=_customTag;
@property(retain, nonatomic) NSArray *activityList; // @synthesize activityList=_activityList;
@property(retain, nonatomic) NSDate *gmtEnd; // @synthesize gmtEnd=_gmtEnd;
@property(retain, nonatomic) NSDate *gmtStart; // @synthesize gmtStart=_gmtStart;
@property(retain, nonatomic) NSString *useLimitDesc; // @synthesize useLimitDesc=_useLimitDesc;
@property(retain, nonatomic) NSString *mainDesc; // @synthesize mainDesc=_mainDesc;
@property(retain, nonatomic) NSString *useDesc; // @synthesize useDesc=_useDesc;
@property(retain, nonatomic) NSString *itemType; // @synthesize itemType=_itemType;
@property(retain, nonatomic) NSString *itemUnit; // @synthesize itemUnit=_itemUnit;
@property(retain, nonatomic) KBRETAILPRODRetailMarketingInfo *discountReduce; // @synthesize discountReduce=_discountReduce;
@property(nonatomic) _Bool canUse; // @synthesize canUse=_canUse;
@property(nonatomic) _Bool hasUnused; // @synthesize hasUnused=_hasUnused;
@property(nonatomic) _Bool autoObtain; // @synthesize autoObtain=_autoObtain;
@property(retain, nonatomic) NSString *original; // @synthesize original=_original;
@property(retain, nonatomic) NSString *current; // @synthesize current=_current;
@property(retain, nonatomic) NSString *url; // @synthesize url=_url;
@property(retain, nonatomic) NSArray *descList; // @synthesize descList=_descList;
@property(retain, nonatomic) NSString *slogan; // @synthesize slogan=_slogan;
@property(retain, nonatomic) NSString *subTitle; // @synthesize subTitle=_subTitle;
@property(retain, nonatomic) NSString *title; // @synthesize title=_title;
@property(retain, nonatomic) NSString *image; // @synthesize image=_image;
@property(retain, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(retain, nonatomic) NSString *icon; // @synthesize icon=_icon;
@property(retain, nonatomic) NSString *mid; // @synthesize mid=_mid;
- (void).cxx_destruct;

@end

