//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIImageView, UILabel;
@protocol LFBaseInfoNewStyleViewDelegate;

@interface LFNewBaseInfoStyleView : UIView
{
    id <LFBaseInfoNewStyleViewDelegate> _delegate;
    UIImageView *_avatarImageView;
    UIView *_avatarStrokeView;
    UILabel *_titleLabel;
    UIView *_containerView;
    long long _style;
    UIView *_externServicesView;
}

@property(retain, nonatomic) UIView *externServicesView; // @synthesize externServicesView=_externServicesView;
@property(nonatomic) long long style; // @synthesize style=_style;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UIView *avatarStrokeView; // @synthesize avatarStrokeView=_avatarStrokeView;
@property(retain, nonatomic) UIImageView *avatarImageView; // @synthesize avatarImageView=_avatarImageView;
@property(nonatomic) __weak id <LFBaseInfoNewStyleViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)dealloc;
- (void)downloadImages:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)loadImagesForExternServicesView:(id)arg1;
- (void)updateConstraints;
- (void)setAvatar:(id)arg1 title:(id)arg2 isCertified:(id)arg3 cateString:(id)arg4 countyUrl:(id)arg5 externIconUrlList:(id)arg6;
- (void)initUI;
- (void)refreshPublicLifeInfo:(id)arg1 style:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1 style:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

