//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class UIScrollView;
@protocol LFCoverViewDelegate;

@protocol LFOldAndNewCoverViewCommonMethodsProtocol <NSObject>
@property(nonatomic) __weak id <LFCoverViewDelegate> delegate;
- (void)forceFollow;
- (void)scrollViewDidEndDragging:(UIScrollView *)arg1;
- (void)scrollDidScroll:(UIScrollView *)arg1;
- (void)stopLoading;
- (void)stopIndicatorViewForFollowedView;
- (void)loadIndicatorViewForFollowedView;
- (void)refreshFollowedNewStyleView:(_Bool)arg1;
@end

