//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface LifeBoxSourceModel : NSObject
{
    _Bool _quite;
    long long _unreadCount;
    NSString *_memoForNewTab;
    NSString *_hint;
    long long _showTime;
    long long _opTime;
    NSString *_headUrl;
}

@property(retain, nonatomic) NSString *headUrl; // @synthesize headUrl=_headUrl;
@property(nonatomic) long long opTime; // @synthesize opTime=_opTime;
@property(nonatomic) long long showTime; // @synthesize showTime=_showTime;
@property(retain, nonatomic) NSString *hint; // @synthesize hint=_hint;
@property(retain, nonatomic) NSString *memoForNewTab; // @synthesize memoForNewTab=_memoForNewTab;
@property(nonatomic) _Bool quite; // @synthesize quite=_quite;
@property(nonatomic) long long unreadCount; // @synthesize unreadCount=_unreadCount;
- (void).cxx_destruct;
- (id)description;
- (id)init;

@end

