//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LottieBaseLogger.h"

@interface LottieLogger : LottieBaseLogger
{
}

+ (void)localLogging:(id)arg1;
+ (void)lottieBizExceptionEventLog:(id)arg1 actionName:(id)arg2 params:(id)arg3;
+ (void)MTBIZReportName:(id)arg1 failCode:(long long)arg2 params:(id)arg3;
+ (void)remoteLogging:(id)arg1 exInfo:(id)arg2;

@end

