//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "LSCardDataProcessor.h"

@class NSDateFormatter;

@interface LSMarketTrendNewsCardDataProcessor : LSCardDataProcessor
{
    NSDateFormatter *_formatter;
}

@property(retain, nonatomic) NSDateFormatter *formatter; // @synthesize formatter=_formatter;
- (void).cxx_destruct;
- (id)mapToShare:(id)arg1;
- (id)handleCardData:(id)arg1;

@end

