//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MBAssistInfoDAO, NSLock, NSMutableDictionary, NSString;

@interface MBAssistInfoDataManager : NSObject
{
    NSString *_currentUserId;
    NSLock *_cacheLock;
    NSMutableDictionary *_dataCache;
    MBAssistInfoDAO *_assistInfoDAO;
}

+ (id)sharedInstance;
@property(retain, nonatomic) MBAssistInfoDAO *assistInfoDAO; // @synthesize assistInfoDAO=_assistInfoDAO;
@property(retain, nonatomic) NSMutableDictionary *dataCache; // @synthesize dataCache=_dataCache;
- (void).cxx_destruct;
- (void)showLog:(id)arg1;
- (void)p_loadAllAssistInfo;
- (_Bool)deleteAssistInfoWithAssistId:(id)arg1;
- (_Bool)updateAssistInfos:(id)arg1;
- (_Bool)update:(id)arg1;
- (id)queryAllAssists;
- (id)queryWithAssistId:(id)arg1;
- (id)queryWithAssistIds:(id)arg1;
- (id)init;

@end

