//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class MBSubscribeAlertViewV2, NSLock, NSMutableArray;

@interface MBUISubscribeServiceV2 : NSObject
{
    NSMutableArray *_messages;
    NSLock *_messagesLock;
    NSLock *_handMessageLock;
    MBSubscribeAlertViewV2 *_alertView;
}

@property(retain, nonatomic) MBSubscribeAlertViewV2 *alertView; // @synthesize alertView=_alertView;
- (void).cxx_destruct;
- (void)requestUIComponentFinished:(id)arg1 message:(id)arg2;
- (void)cancelCallBack:(id)arg1;
- (void)callBack:(id)arg1 success:(_Bool)arg2 resultCode:(id)arg3 resultDesc:(id)arg4;
- (void)handleMessage:(id)arg1;
- (void)tryHandleMessage;
- (_Bool)subscribe:(id)arg1 silent:(_Bool)arg2 complateHandler:(CDUnknownBlockType)arg3 cancelHandler:(CDUnknownBlockType)arg4;
- (id)init;

@end

