//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

#import "MFWidgetPluginProtocol-Protocol.h"
#import "UICollectionViewDataSource-Protocol.h"
#import "UICollectionViewDelegate-Protocol.h"

@class NSArray, NSShadow, NSString, UICollectionView, UICollectionViewFlowLayout, UIColor;
@protocol MFWidgetPluginProtocol;

@interface MFBannerView : UIView <UICollectionViewDataSource, UICollectionViewDelegate, MFWidgetPluginProtocol>
{
    _Bool _autoPlay;
    long long _scrollDirection;
    double _interval;
    double _itemWidth;
    double _itemHeight;
    long long _computedColumnCount;
    double _computedColumnWidth;
    double _columnGap;
    double _cornerRadius;
    double _borderWidth;
    UIColor *_borderColor;
    NSShadow *_boxShadow;
    id <MFWidgetPluginProtocol> _delegate;
    UICollectionView *_collectionView;
    UICollectionViewFlowLayout *_layout;
    struct __CFRunLoopTimer *_autoTimer;
    NSArray *_dataSource;
    long long _previousPageIndex;
    long long _currentPageIndex;
}

+ (id)subType;
+ (id)tagType;
+ (struct CGSize)sizeOfWidgetWithData:(id)arg1 cssItem:(id)arg2 superFrame:(struct CGRect)arg3 extendInfo:(id)arg4;
@property(nonatomic) long long currentPageIndex; // @synthesize currentPageIndex=_currentPageIndex;
@property(nonatomic) long long previousPageIndex; // @synthesize previousPageIndex=_previousPageIndex;
@property(retain, nonatomic) NSArray *dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) struct __CFRunLoopTimer *autoTimer; // @synthesize autoTimer=_autoTimer;
@property(retain, nonatomic) UICollectionViewFlowLayout *layout; // @synthesize layout=_layout;
@property(retain, nonatomic) UICollectionView *collectionView; // @synthesize collectionView=_collectionView;
@property(nonatomic) __weak id <MFWidgetPluginProtocol> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSShadow *boxShadow; // @synthesize boxShadow=_boxShadow;
@property(retain, nonatomic) UIColor *borderColor; // @synthesize borderColor=_borderColor;
@property(nonatomic) double borderWidth; // @synthesize borderWidth=_borderWidth;
@property(nonatomic) double cornerRadius; // @synthesize cornerRadius=_cornerRadius;
@property(nonatomic) double columnGap; // @synthesize columnGap=_columnGap;
@property(nonatomic) double computedColumnWidth; // @synthesize computedColumnWidth=_computedColumnWidth;
@property(nonatomic) long long computedColumnCount; // @synthesize computedColumnCount=_computedColumnCount;
@property(nonatomic) double itemHeight; // @synthesize itemHeight=_itemHeight;
@property(nonatomic) double itemWidth; // @synthesize itemWidth=_itemWidth;
@property(nonatomic) _Bool autoPlay; // @synthesize autoPlay=_autoPlay;
@property(nonatomic) double interval; // @synthesize interval=_interval;
@property(nonatomic) long long scrollDirection; // @synthesize scrollDirection=_scrollDirection;
- (void).cxx_destruct;
- (void)setMFDelegate:(id)arg1;
- (void)bindAndLayoutWithData:(id)arg1 cssItem:(id)arg2 extendInfo:(id)arg3;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumInteritemSpacingForSectionAtIndex:(long long)arg3;
- (double)collectionView:(id)arg1 layout:(id)arg2 minimumLineSpacingForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 sizeForItemAtIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)autoScroll:(unsigned long long)arg1;
- (void)stopAutoPlayTimer;
- (void)startAutoPlayTimer;
- (void)configCollectionView;
- (void)setFrame:(struct CGRect)arg1;
- (id)accessibilityLabel;
- (id)accessibilityElements;
- (_Bool)isAccessibilityElement;
- (void)setBackgroundColor:(id)arg1;
- (id)init;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

