//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UITableViewHeaderFooterView.h>

#import "MFAttributedLabelDelegate-Protocol.h"
#import "MFCell-Protocol.h"
#import "MFLongAttributeLabelDelegate-Protocol.h"

@class MFVirtualNode, NSDictionary, NSIndexPath, NSString, UIImageView;
@protocol MFCellDelegate><MFEditStyleProtocol;

@interface MFHeadFooter : UITableViewHeaderFooterView <MFAttributedLabelDelegate, MFLongAttributeLabelDelegate, MFCell>
{
    NSString *_identifier;
    NSString *_tId;
    NSDictionary *_dataItem;
    id _originData;
    MFVirtualNode *_vNode;
    long long _section;
    long long _row;
    NSIndexPath *_indexPath;
    id <MFCellDelegate><MFEditStyleProtocol> _delegate;
}

@property(nonatomic) __weak id <MFCellDelegate><MFEditStyleProtocol> delegate; // @synthesize delegate=_delegate;
@property(copy, nonatomic) NSIndexPath *indexPath; // @synthesize indexPath=_indexPath;
@property(nonatomic) long long row; // @synthesize row=_row;
@property(nonatomic) long long section; // @synthesize section=_section;
@property(retain, nonatomic) MFVirtualNode *vNode; // @synthesize vNode=_vNode;
@property(retain, nonatomic) id originData; // @synthesize originData=_originData;
@property(retain, nonatomic) NSDictionary *dataItem; // @synthesize dataItem=_dataItem;
@property(copy, nonatomic) NSString *tId; // @synthesize tId=_tId;
@property(copy, nonatomic) NSString *identifier; // @synthesize identifier=_identifier;
- (void).cxx_destruct;
- (_Bool)handleNativeEvent:(id)arg1 target:(id)arg2;
- (void)bindData;
- (void)layout;
- (void)onClickMFLongAttributeLabel:(id)arg1 state:(int)arg2;
- (void)mfAttributedLabel:(id)arg1 longPressOnLink:(id)arg2 CGRect:(struct CGRect)arg3;
- (void)mfAttributedLabel:(id)arg1 clickedOnLink:(id)arg2;
- (void)widgetSpecialHandleing:(id)arg1;
- (void)specialHandling;
- (id)mfContentView;
- (void)setupUI;
- (id)initWithReuseIdentifier:(id)arg1;
- (void)dealloc;
- (void)handleEditStyle;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(retain, nonatomic) NSString *fakeShadowImageName;
@property(retain, nonatomic) UIImageView *fakeShadowImageView;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

