//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface mfinquotationprodIntradayPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *avgPrice; // @dynamic avgPrice;
@property(retain, nonatomic) NSString *currentAmount; // @dynamic currentAmount;
@property(retain, nonatomic) NSString *currentVolume; // @dynamic currentVolume;
@property(nonatomic) long long date; // @dynamic date;
@property(readonly) _Bool hasAvgPrice; // @dynamic hasAvgPrice;
@property(readonly) _Bool hasCurrentAmount; // @dynamic hasCurrentAmount;
@property(readonly) _Bool hasCurrentVolume; // @dynamic hasCurrentVolume;
@property(readonly) _Bool hasDate; // @dynamic hasDate;
@property(readonly) _Bool hasPrice; // @dynamic hasPrice;
@property(readonly) _Bool hasSymbol; // @dynamic hasSymbol;
@property(retain, nonatomic) NSString *price; // @dynamic price;
@property(retain, nonatomic) NSString *symbol; // @dynamic symbol;

@end

