//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface mfinquotationprodSecuInfoPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *currency; // @dynamic currency;
@property(nonatomic) long long date; // @dynamic date;
@property(retain, nonatomic) NSString *enName; // @dynamic enName;
@property(nonatomic) _Bool exDividend; // @dynamic exDividend;
@property(nonatomic) _Bool exRights; // @dynamic exRights;
@property(retain, nonatomic) NSString *fixedName; // @dynamic fixedName;
@property(retain, nonatomic) NSString *fullName; // @dynamic fullName;
@property(nonatomic) int hand; // @dynamic hand;
@property(readonly) _Bool hasCurrency; // @dynamic hasCurrency;
@property(readonly) _Bool hasDate; // @dynamic hasDate;
@property(readonly) _Bool hasEnName; // @dynamic hasEnName;
@property(readonly) _Bool hasExDividend; // @dynamic hasExDividend;
@property(readonly) _Bool hasExRights; // @dynamic hasExRights;
@property(readonly) _Bool hasFixedName; // @dynamic hasFixedName;
@property(readonly) _Bool hasFullName; // @dynamic hasFullName;
@property(readonly) _Bool hasHand; // @dynamic hasHand;
@property(readonly) _Bool hasListedFirstDate; // @dynamic hasListedFirstDate;
@property(readonly) _Bool hasListedStatus; // @dynamic hasListedStatus;
@property(readonly) _Bool hasMarket; // @dynamic hasMarket;
@property(readonly) _Bool hasName; // @dynamic hasName;
@property(readonly) _Bool hasStockSymbolId; // @dynamic hasStockSymbolId;
@property(readonly) _Bool hasSubType; // @dynamic hasSubType;
@property(readonly) _Bool hasSymbol; // @dynamic hasSymbol;
@property(readonly) _Bool hasType; // @dynamic hasType;
@property(nonatomic) long long listedFirstDate; // @dynamic listedFirstDate;
@property(retain, nonatomic) NSString *listedStatus; // @dynamic listedStatus;
@property(retain, nonatomic) NSString *market; // @dynamic market;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) NSString *stockSymbolId; // @dynamic stockSymbolId;
@property(retain, nonatomic) NSString *subType; // @dynamic subType;
@property(retain, nonatomic) NSString *symbol; // @dynamic symbol;
@property(retain, nonatomic) NSString *type; // @dynamic type;

@end

