//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface mmtcapiOcrReqPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *appId; // @dynamic appId;
@property(readonly) _Bool hasAppId; // @dynamic hasAppId;
@property(readonly) _Bool hasImageBase64; // @dynamic hasImageBase64;
@property(readonly) _Bool hasOcrType; // @dynamic hasOcrType;
@property(readonly) _Bool hasSide; // @dynamic hasSide;
@property(readonly) _Bool hasUrl; // @dynamic hasUrl;
@property(retain, nonatomic) NSString *imageBase64; // @dynamic imageBase64;
@property(retain, nonatomic) NSString *ocrType; // @dynamic ocrType;
@property(retain, nonatomic) NSString *side; // @dynamic side;
@property(retain, nonatomic) NSString *url; // @dynamic url;

@end

