//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface mobilelbsCountyRespPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *adCode; // @dynamic adCode;
@property(nonatomic) _Bool chineseMainLand; // @dynamic chineseMainLand;
@property(retain, nonatomic) NSString *countyType; // @dynamic countyType;
@property(retain, nonatomic) NSString *fullSpell; // @dynamic fullSpell;
@property(readonly) _Bool hasAdCode; // @dynamic hasAdCode;
@property(readonly) _Bool hasChineseMainLand; // @dynamic hasChineseMainLand;
@property(readonly) _Bool hasCountyType; // @dynamic hasCountyType;
@property(readonly) _Bool hasFullSpell; // @dynamic hasFullSpell;
@property(readonly) _Bool hasName; // @dynamic hasName;
@property(readonly) _Bool hasNameEng; // @dynamic hasNameEng;
@property(readonly) _Bool hasSimpleName; // @dynamic hasSimpleName;
@property(retain, nonatomic) NSString *name; // @dynamic name;
@property(retain, nonatomic) NSString *nameEng; // @dynamic nameEng;
@property(retain, nonatomic) NSString *simpleName; // @dynamic simpleName;

@end

