//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class PBMapStringString, mobilecodecLbsInfoPbPB, mobilecodecProductContextPbPB;

@interface mobilecodecLoaderCachePbReqPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) PBMapStringString *extData; // @dynamic extData;
@property(readonly) _Bool hasExtData; // @dynamic hasExtData;
@property(readonly) _Bool hasLbsInfoPb; // @dynamic hasLbsInfoPb;
@property(readonly) _Bool hasProductContextPb; // @dynamic hasProductContextPb;
@property(retain, nonatomic) mobilecodecLbsInfoPbPB *lbsInfoPb; // @dynamic lbsInfoPb;
@property(retain, nonatomic) mobilecodecProductContextPbPB *productContextPb; // @dynamic productContextPb;

@end

