//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSData, NSDate, NSString;

@interface mobilecodecEncodeRpcRequest : NSObject
{
    _Bool _isSavingMode;
    NSString *_token;
    NSString *_codeType;
    NSString *_userId;
    NSString *_bizLinkedId;
    NSString *_bizType;
    NSDate *_startDate;
    long long _timeout;
    NSString *_sourceId;
    NSString *_operator;
    NSString *_contextData;
    NSString *_memo;
    NSData *_logo;
    NSString *_logoName;
    NSString *_statData;
    NSString *_bizTag;
    NSString *_preContent;
    NSString *_endContent;
    NSString *_pageUrl;
}

@property(retain, nonatomic) NSString *pageUrl; // @synthesize pageUrl=_pageUrl;
@property(retain, nonatomic) NSString *endContent; // @synthesize endContent=_endContent;
@property(retain, nonatomic) NSString *preContent; // @synthesize preContent=_preContent;
@property(retain, nonatomic) NSString *bizTag; // @synthesize bizTag=_bizTag;
@property(retain, nonatomic) NSString *statData; // @synthesize statData=_statData;
@property(retain, nonatomic) NSString *logoName; // @synthesize logoName=_logoName;
@property(retain, nonatomic) NSData *logo; // @synthesize logo=_logo;
@property(nonatomic) _Bool isSavingMode; // @synthesize isSavingMode=_isSavingMode;
@property(retain, nonatomic) NSString *memo; // @synthesize memo=_memo;
@property(retain, nonatomic) NSString *contextData; // @synthesize contextData=_contextData;
@property(retain, nonatomic) NSString *operator; // @synthesize operator=_operator;
@property(retain, nonatomic) NSString *sourceId; // @synthesize sourceId=_sourceId;
@property(nonatomic) long long timeout; // @synthesize timeout=_timeout;
@property(retain, nonatomic) NSDate *startDate; // @synthesize startDate=_startDate;
@property(retain, nonatomic) NSString *bizType; // @synthesize bizType=_bizType;
@property(retain, nonatomic) NSString *bizLinkedId; // @synthesize bizLinkedId=_bizLinkedId;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
@property(retain, nonatomic) NSString *codeType; // @synthesize codeType=_codeType;
@property(retain, nonatomic) NSString *token; // @synthesize token=_token;
- (void).cxx_destruct;

@end

