//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface mobilecodecBatchChannelInfo : NSObject
{
    int _suggestUpdateNum;
    NSString *_channelIndex;
    NSArray *_batchDynamicCodes;
}

+ (Class)batchDynamicCodesElementClass;
@property(retain, nonatomic) NSArray *batchDynamicCodes; // @synthesize batchDynamicCodes=_batchDynamicCodes;
@property(nonatomic) int suggestUpdateNum; // @synthesize suggestUpdateNum=_suggestUpdateNum;
@property(retain, nonatomic) NSString *channelIndex; // @synthesize channelIndex=_channelIndex;
- (void).cxx_destruct;
- (void)setBatchDynamicCodesWithSort:(id)arg1;

@end

