//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface mobilechatRecentMerchantInfo : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(nonatomic) long long consumptionTime; // @dynamic consumptionTime;
@property(retain, nonatomic) NSString *contactScheme; // @dynamic contactScheme;
@property(readonly) _Bool hasConsumptionTime; // @dynamic hasConsumptionTime;
@property(readonly) _Bool hasContactScheme; // @dynamic hasContactScheme;
@property(readonly) _Bool hasItemVersion; // @dynamic hasItemVersion;
@property(readonly) _Bool hasMerchantIcon; // @dynamic hasMerchantIcon;
@property(readonly) _Bool hasMerchantId; // @dynamic hasMerchantId;
@property(readonly) _Bool hasMerchantName; // @dynamic hasMerchantName;
@property(readonly) _Bool hasMerchantScheme; // @dynamic hasMerchantScheme;
@property(readonly) _Bool hasVipInfo; // @dynamic hasVipInfo;
@property(nonatomic) long long itemVersion; // @dynamic itemVersion;
@property(retain, nonatomic) NSString *merchantIcon; // @dynamic merchantIcon;
@property(retain, nonatomic) NSString *merchantId; // @dynamic merchantId;
@property(retain, nonatomic) NSString *merchantName; // @dynamic merchantName;
@property(retain, nonatomic) NSString *merchantScheme; // @dynamic merchantScheme;
@property(retain, nonatomic) NSString *vipInfo; // @dynamic vipInfo;

@end

