//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface mobileappconfigAppBaseInfo : NSObject
{
    _Bool _alipayApp;
    _Bool _display;
    _Bool _recommand;
    _Bool _needAuthorize;
    _Bool _autoAuthorize;
    _Bool _autoStatus;
    _Bool _tinyApp;
    _Bool _historyShow;
    int _pkgSize;
    int _updateFrequency;
    NSString *_appId;
    NSString *_name;
    NSString *_iconUrl;
    NSString *_desc;
    NSString *_slogan;
    NSString *_version;
    NSString *_pkgUrl;
    NSString *_pkgUrlNew;
    NSString *_md5;
    NSString *_incrementPkgUrl;
    NSString *_h5AppCdnBaseUrl;
    NSString *_pkgType;
    NSString *_status;
    NSString *_appSource;
    NSString *_thirdPkgName;
    NSString *_schemaUri;
    NSString *_pageUrl;
    NSString *_extra;
    NSString *_downloadScene;
    NSString *_appTag;
    NSString *_appIcon;
    long long _lastTimestamp;
}

@property(nonatomic) long long lastTimestamp; // @synthesize lastTimestamp=_lastTimestamp;
@property(nonatomic) _Bool historyShow; // @synthesize historyShow=_historyShow;
@property(nonatomic) int updateFrequency; // @synthesize updateFrequency=_updateFrequency;
@property(nonatomic) _Bool tinyApp; // @synthesize tinyApp=_tinyApp;
@property(retain, nonatomic) NSString *appIcon; // @synthesize appIcon=_appIcon;
@property(retain, nonatomic) NSString *appTag; // @synthesize appTag=_appTag;
@property(retain, nonatomic) NSString *downloadScene; // @synthesize downloadScene=_downloadScene;
@property(nonatomic) _Bool autoStatus; // @synthesize autoStatus=_autoStatus;
@property(nonatomic) _Bool autoAuthorize; // @synthesize autoAuthorize=_autoAuthorize;
@property(nonatomic) _Bool needAuthorize; // @synthesize needAuthorize=_needAuthorize;
@property(nonatomic) _Bool recommand; // @synthesize recommand=_recommand;
@property(nonatomic) _Bool display; // @synthesize display=_display;
@property(retain, nonatomic) NSString *extra; // @synthesize extra=_extra;
@property(retain, nonatomic) NSString *pageUrl; // @synthesize pageUrl=_pageUrl;
@property(retain, nonatomic) NSString *schemaUri; // @synthesize schemaUri=_schemaUri;
@property(retain, nonatomic) NSString *thirdPkgName; // @synthesize thirdPkgName=_thirdPkgName;
@property(retain, nonatomic) NSString *appSource; // @synthesize appSource=_appSource;
@property(nonatomic) _Bool alipayApp; // @synthesize alipayApp=_alipayApp;
@property(retain, nonatomic) NSString *status; // @synthesize status=_status;
@property(retain, nonatomic) NSString *pkgType; // @synthesize pkgType=_pkgType;
@property(retain, nonatomic) NSString *h5AppCdnBaseUrl; // @synthesize h5AppCdnBaseUrl=_h5AppCdnBaseUrl;
@property(retain, nonatomic) NSString *incrementPkgUrl; // @synthesize incrementPkgUrl=_incrementPkgUrl;
@property(retain, nonatomic) NSString *md5; // @synthesize md5=_md5;
@property(nonatomic) int pkgSize; // @synthesize pkgSize=_pkgSize;
@property(retain, nonatomic) NSString *pkgUrlNew; // @synthesize pkgUrlNew=_pkgUrlNew;
@property(retain, nonatomic) NSString *pkgUrl; // @synthesize pkgUrl=_pkgUrl;
@property(retain, nonatomic) NSString *version; // @synthesize version=_version;
@property(retain, nonatomic) NSString *slogan; // @synthesize slogan=_slogan;
@property(retain, nonatomic) NSString *desc; // @synthesize desc=_desc;
@property(retain, nonatomic) NSString *iconUrl; // @synthesize iconUrl=_iconUrl;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
@property(retain, nonatomic) NSString *appId; // @synthesize appId=_appId;
- (void).cxx_destruct;

@end

