//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSArray, NSString;

@interface mobilebillEntrancePBModel : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(readonly) _Bool hasIconUrl; // @dynamic hasIconUrl;
@property(readonly) _Bool hasRedPoint; // @dynamic hasRedPoint;
@property(readonly) _Bool hasTitle; // @dynamic hasTitle;
@property(readonly) _Bool hasUrl; // @dynamic hasUrl;
@property(retain, nonatomic) NSString *iconUrl; // @dynamic iconUrl;
@property(nonatomic) _Bool redPoint; // @dynamic redPoint;
@property(retain, nonatomic) NSArray *subList; // @dynamic subList;
@property(retain, nonatomic) NSString *title; // @dynamic title;
@property(retain, nonatomic) NSString *url; // @dynamic url;

@end

