//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface MP4Manager : NSObject
{
}

+ (int)calcFPSWithVideoTrack:(id)arg1 compressLevel:(unsigned long long)arg2;
+ (int)calcBitRateWithVideoTrack:(id)arg1 compressLevel:(unsigned long long)arg2;
+ (struct CGSize)calcCompressSizeWithTrackDimension:(struct CGSize)arg1 compressLevel:(unsigned long long)arg2;
+ (id)infoFromPath:(id)arg1;
+ (_Bool)isVideoTypeWithPath:(id)arg1;
+ (long long)orientationForVideoTrack:(id)arg1;
+ (struct CGAffineTransform)calcTransformForVideoTrack:(id)arg1;
+ (void)compressVideo:(id)arg1 toPath:(id)arg2 fileSize:(long long)arg3 isShortVideo:(_Bool)arg4 timeRange:(CDStruct_e83c9415)arg5 compressLevel:(unsigned long long)arg6 progress:(CDUnknownBlockType)arg7 completion:(CDUnknownBlockType)arg8;
+ (struct CGSize)getDimensionFromTrack:(id)arg1;
+ (void)compressVideo:(id)arg1 key:(id)arg2 fileSize:(long long)arg3 isShortVideo:(_Bool)arg4 startPoint:(double)arg5 endPoint:(double)arg6 compressLevel:(unsigned long long)arg7 progress:(CDUnknownBlockType)arg8 completeHandler:(CDUnknownBlockType)arg9;
+ (void)compressVideo:(id)arg1 key:(id)arg2 fileSize:(long long)arg3 isShortVideo:(_Bool)arg4 timeRange:(CDStruct_e83c9415)arg5 compressLevel:(unsigned long long)arg6 progress:(CDUnknownBlockType)arg7 completeHandler:(CDUnknownBlockType)arg8;

@end

