//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MQPBNPlugin.h"

@class MQPCommonNativeContext, NSDictionary, UIView;
@protocol MQPEmbeddedViewProtocol;

@interface MQPCommonNative : MQPBNPlugin
{
    NSDictionary *_pluginInfo;
    UIView<MQPEmbeddedViewProtocol> *_pluginView;
    MQPCommonNativeContext *_context;
}

@property(retain, nonatomic) MQPCommonNativeContext *context; // @synthesize context=_context;
@property(retain, nonatomic) UIView<MQPEmbeddedViewProtocol> *pluginView; // @synthesize pluginView=_pluginView;
@property(retain, nonatomic) NSDictionary *pluginInfo; // @synthesize pluginInfo=_pluginInfo;
- (void).cxx_destruct;
- (void)updateAttr:(id)arg1 withValue:(id)arg2;
- (void)updateRect;
- (id)initWithNode:(struct fb_node *)arg1 withDocument:(id)arg2 withView:(id)arg3;

@end

