//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString, PBMapStringString;

@interface MSTerminalCheckRequestPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *apdid; // @dynamic apdid;
@property(retain, nonatomic) NSString *apdidToken; // @dynamic apdidToken;
@property(retain, nonatomic) NSString *appVersion; // @dynamic appVersion;
@property(retain, nonatomic) PBMapStringString *externParams; // @dynamic externParams;
@property(readonly) _Bool hasApdid; // @dynamic hasApdid;
@property(readonly) _Bool hasApdidToken; // @dynamic hasApdidToken;
@property(readonly) _Bool hasAppVersion; // @dynamic hasAppVersion;
@property(readonly) _Bool hasExternParams; // @dynamic hasExternParams;
@property(readonly) _Bool hasMobileBrand; // @dynamic hasMobileBrand;
@property(readonly) _Bool hasMobileModel; // @dynamic hasMobileModel;
@property(readonly) _Bool hasPlatform; // @dynamic hasPlatform;
@property(readonly) _Bool hasTid; // @dynamic hasTid;
@property(readonly) _Bool hasUtdid; // @dynamic hasUtdid;
@property(retain, nonatomic) NSString *mobileBrand; // @dynamic mobileBrand;
@property(retain, nonatomic) NSString *mobileModel; // @dynamic mobileModel;
@property(retain, nonatomic) NSString *platform; // @dynamic platform;
@property(retain, nonatomic) NSString *tid; // @dynamic tid;
@property(retain, nonatomic) NSString *utdid; // @dynamic utdid;

@end

