//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "MYPromotionView.h"

@class UIView;

@interface MYPromotionTrackingView : MYPromotionView
{
    UIView *_trackedView;
    UIView *_trackedRender;
    unsigned long long _trackingViewType;
}

@property(nonatomic) unsigned long long trackingViewType; // @synthesize trackingViewType=_trackingViewType;
@property(nonatomic) __weak UIView *trackedRender; // @synthesize trackedRender=_trackedRender;
@property(nonatomic) __weak UIView *trackedView; // @synthesize trackedView=_trackedView;
- (void).cxx_destruct;
- (_Bool)isTrackingToView:(id)arg1;
- (void)removeFromSuperview;
- (void)moveToSuperviewForRender;
- (void)moveToSuperviewForView;
- (void)moveToSuperview;
- (id)initWithTrackedRender:(id)arg1;
- (id)initWithTrackedView:(id)arg1;
- (id)initWithTrackedObject:(id)arg1;

@end

