//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NebulaAppResponseProtocol-Protocol.h"

@class NAMAppDataSource, NSData, NSDictionary, NSString;

@interface NAMAppResponse : NSObject <NebulaAppResponseProtocol>
{
    NSString *_absoluteUrlString;
    NSString *_mimeType;
    NSData *_contentData;
    NAMAppDataSource *_dataSource;
    NSDictionary *_headers;
}

@property(retain, nonatomic) NSDictionary *headers; // @synthesize headers=_headers;
@property(nonatomic) __weak NAMAppDataSource *dataSource; // @synthesize dataSource=_dataSource;
@property(retain, nonatomic) NSData *contentData; // @synthesize contentData=_contentData;
@property(copy, nonatomic) NSString *mimeType; // @synthesize mimeType=_mimeType;
@property(copy, nonatomic) NSString *absoluteUrlString; // @synthesize absoluteUrlString=_absoluteUrlString;
- (void).cxx_destruct;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

