//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "DTService-Protocol.h"
#import "NebulaResourceServiceProtocol-Protocol.h"

@class NSString, NXIRService, NebulaAppService;

@interface NebulaResourceService : NSObject <DTService, NebulaResourceServiceProtocol>
{
    NebulaAppService *_appService;
    NXIRService *_resourceService;
}

@property(retain, nonatomic) NXIRService *resourceService; // @synthesize resourceService=_resourceService;
@property(retain, nonatomic) NebulaAppService *appService; // @synthesize appService=_appService;
- (void).cxx_destruct;
- (id)createNebulaStartHandler;
- (void)registerHandler:(id)arg1;
- (_Bool)isNebulaHanlerProcessed:(id)arg1 params:(id)arg2;
- (_Bool)enableTinySwitchMode;
- (void)clearStorage:(_Bool)arg1;
- (void)addCommonApps:(id)arg1;
- (void)setDebugDelegate:(id)arg1;
- (int)appType:(id)arg1;
- (_Bool)enableNebulaHandler;
- (_Bool)isVersionValid:(id)arg1 opversion:(id)arg2 nbversion:(id)arg3;
- (_Bool)verifyApp:(id)arg1;
- (_Bool)isNebulaAppId:(id)arg1 nebulaVersion:(id *)arg2;
- (void)installApp:(id)arg1 process:(CDUnknownBlockType)arg2 finish:(CDUnknownBlockType)arg3;
- (void)requestApps:(id)arg1 param:(id)arg2 finish:(CDUnknownBlockType)arg3;
- (id)findApp:(id)arg1 withVersion:(id)arg2;
- (id)findApp:(id)arg1;
- (void)prepareWithAppId:(id)arg1;
- (id)curService;
- (void)willDestroy;
- (void)start;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

