//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NPLocation, NSMutableArray, PSDSession;

@interface NPPreRPC : NSObject
{
    NSMutableArray *_requestTaskQueue;
    PSDSession *_session;
    NPLocation *_location;
}

@property(retain, nonatomic) NPLocation *location; // @synthesize location=_location;
@property(nonatomic) __weak PSDSession *session; // @synthesize session=_session;
@property(retain, nonatomic) NSMutableArray *requestTaskQueue; // @synthesize requestTaskQueue=_requestTaskQueue;
- (void).cxx_destruct;
- (id)getLBSInfoFromString:(id)arg1;
- (id)getRequestParamsFromLbs:(id)arg1 url:(id)arg2;
- (id)getTaskWithRequestId:(id)arg1;
- (void)cacheTask:(id)arg1;
- (void)dispatchPreRpcRequestMessageWithRequestId:(id)arg1 data:(id)arg2;
- (void)removeTaskWithRequestId:(id)arg1;
- (id)getPreRPCRequestRequestWithRequestId:(id)arg1;
- (void)preRPCMonitorWithParams:(id)arg1 lbsSource:(int)arg2;
- (void)preRedEnvelopeRpcWithRequestId:(id)arg1 param:(id)arg2;
- (id)initWithSession:(id)arg1;

@end

