//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "NXRRequestProtocol-Protocol.h"
#import "OPCommonRequestHandleProtocol-Protocol.h"

@class APThreadPool, NSString;

@interface NXIRRequestManager : NSObject <OPCommonRequestHandleProtocol, NXRRequestProtocol>
{
    APThreadPool *_threadPool;
}

@property(retain, nonatomic) APThreadPool *threadPool; // @synthesize threadPool=_threadPool;
- (void).cxx_destruct;
- (void)logQueryAppInfoRpc:(id)arg1 resposne:(id)arg2;
- (_Bool)isPreOn;
- (id)convertReqModel:(id)arg1;
- (id)commonReqInfo;
- (id)convertResponse:(id)arg1;
- (void)handlePackInfoJsonResponse:(id)arg1 currentReq:(id)arg2;
- (id)bulidPackInfoReqWithAppIdList:(id)arg1;
- (_Bool)enableDefaultThreadPool;
- (id)convertBatchQueryResponse:(id)arg1;
- (id)convertResponse:(id)arg1 scene:(id)arg2;
- (void)logException:(id)arg1 params:(id)arg2;
- (id)stableFlag:(id)arg1;
- (id)reqmode:(id)arg1;
- (id)localApps:(id)arg1;
- (id)existedAppJson:(id)arg1;
- (id)queryJson:(id)arg1 params:(id)arg2;
- (id)executeReq:(id)arg1 header:(id)arg2 reqlist:(id)arg3 scene:(id)arg4;
- (void)getResourceWithUrl:(id)arg1 callback:(CDUnknownBlockType)arg2;
- (_Bool)enableAriverNebula:(id)arg1;
- (void)requestBatchApps:(id)arg1 params:(id)arg2 finish:(CDUnknownBlockType)arg3;
- (void)requestPlugin:(id)arg1 params:(id)arg2 finish:(CDUnknownBlockType)arg3;
- (void)requestApps:(id)arg1 params:(id)arg2 finish:(CDUnknownBlockType)arg3;
- (void)requestCreditlist:(id)arg1 finish:(CDUnknownBlockType)arg2;
- (void)registerRequestDelegate;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

