//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class O2OAlbumListTableView, O2OAlbumListTableViewCell;

@protocol O2OAlbumListDelegate <NSObject>

@optional
- (void)changeAlbumContents:(O2OAlbumListTableView *)arg1 withCell:(O2OAlbumListTableViewCell *)arg2;
@end

