//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "O2OListViewController.h"

#import "O2OCategorySegmentViewDelegate-Protocol.h"
#import "O2OCommonSchemeProtocol-Protocol.h"

@class AULoadingIndicatorView, AUNetErrorView, NSString, O2OAllCategoryModel, O2OCategoryDataSource, O2OCategoryDelegate, O2OCategorySegmentView;

@interface O2OAllCategoryViewController : O2OListViewController <O2OCommonSchemeProtocol, O2OCategorySegmentViewDelegate>
{
    O2OCategorySegmentView *_scrollView;
    AULoadingIndicatorView *_indicatorView;
    AUNetErrorView *_netAlertView;
    AUNetErrorView *_netErrorView;
    AUNetErrorView *_netLimitView;
    AUNetErrorView *_emptyErrorView;
    O2OAllCategoryModel *_categoryModel;
    O2OCategoryDataSource *_ds;
    O2OCategoryDelegate *_dl;
    double _startRender;
    double _startRpc;
    double _endRpc;
    double _endRender;
}

+ (id)intervalToString:(double)arg1;
+ (unsigned long long)canInitWithScheme:(id)arg1;
@property(nonatomic) double endRender; // @synthesize endRender=_endRender;
@property(nonatomic) double endRpc; // @synthesize endRpc=_endRpc;
@property(nonatomic) double startRpc; // @synthesize startRpc=_startRpc;
@property(nonatomic) double startRender; // @synthesize startRender=_startRender;
@property(retain, nonatomic) O2OCategoryDelegate *dl; // @synthesize dl=_dl;
@property(retain, nonatomic) O2OCategoryDataSource *ds; // @synthesize ds=_ds;
@property(retain, nonatomic) O2OAllCategoryModel *categoryModel; // @synthesize categoryModel=_categoryModel;
@property(retain, nonatomic) AUNetErrorView *emptyErrorView; // @synthesize emptyErrorView=_emptyErrorView;
@property(retain, nonatomic) AUNetErrorView *netLimitView; // @synthesize netLimitView=_netLimitView;
@property(retain, nonatomic) AUNetErrorView *netErrorView; // @synthesize netErrorView=_netErrorView;
@property(retain, nonatomic) AUNetErrorView *netAlertView; // @synthesize netAlertView=_netAlertView;
@property(retain, nonatomic) AULoadingIndicatorView *indicatorView; // @synthesize indicatorView=_indicatorView;
@property(retain, nonatomic) O2OCategorySegmentView *scrollView; // @synthesize scrollView=_scrollView;
- (void).cxx_destruct;
- (void)selectedItemAtIndex:(unsigned long long)arg1;
- (void)stopLoadingAnimation;
- (void)showError:(id)arg1 withModel:(id)arg2;
- (void)showEmpty:(id)arg1;
- (void)showLoading:(id)arg1;
- (void)logPagePerformance;
- (void)showModel:(id)arg1;
- (_Bool)canShowModel:(id)arg1;
- (void)dealloc;
- (void)viewSafeAreaInsetsDidChange;
- (void)viewDidLayoutSubviews;
- (void)viewDidLoad;
- (id)pageSpm;
- (id)initWithScheme:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

