//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class IconView, UIButton, UIImage;
@protocol O2OCameraToolViewDelegate;

@interface O2OCameraToolView : UIView
{
    id <O2OCameraToolViewDelegate> _delegate;
    IconView *_albumImageView;
    UIButton *_takePhotoBtn;
    IconView *_filterIconView;
    UIButton *_filterBtn;
    UIImage *_lastImage;
}

@property(retain, nonatomic) UIImage *lastImage; // @synthesize lastImage=_lastImage;
@property(retain, nonatomic) UIButton *filterBtn; // @synthesize filterBtn=_filterBtn;
@property(retain, nonatomic) IconView *filterIconView; // @synthesize filterIconView=_filterIconView;
@property(retain, nonatomic) UIButton *takePhotoBtn; // @synthesize takePhotoBtn=_takePhotoBtn;
@property(retain, nonatomic) IconView *albumImageView; // @synthesize albumImageView=_albumImageView;
@property(nonatomic) __weak id <O2OCameraToolViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)isTakeBtnEnabled:(_Bool)arg1;
- (void)clickFilterBtn;
- (void)clickTakePhotoBtn;
- (void)clickAlbumBtn;
- (void)updateLastImage;
- (void)getPreiOS8LastImage;
- (void)setUpWithFrame:(struct CGRect)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

