//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "O2OViewController.h"

#import "O2OCommentPublishViewControllerProtocol-Protocol.h"
#import "O2OCommonSchemeProtocol-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSString, O2OCommentInitContext, O2OCommentInitModel, O2OCommentProtocolHelper, O2OCommentPublicSuccessShareInfo, O2OCommentPublishModel, UIScrollView;
@protocol O2OCommentPublishViewRenderProtocol;

@interface O2OCommentPublishViewController : O2OViewController <O2OCommonSchemeProtocol, UIScrollViewDelegate, O2OCommentPublishViewControllerProtocol>
{
    O2OCommentInitContext *_context;
    O2OCommentInitModel *_infoModel;
    O2OCommentPublishModel *_publishModel;
    UIScrollView *_scrollView;
    unsigned long long _viewStyle;
    O2OCommentProtocolHelper *_protocolHelper;
    id <O2OCommentPublishViewRenderProtocol> _render;
    O2OCommentPublicSuccessShareInfo *_shareInfo;
}

+ (unsigned long long)canInitWithScheme:(id)arg1;
@property(retain, nonatomic) O2OCommentPublicSuccessShareInfo *shareInfo; // @synthesize shareInfo=_shareInfo;
@property(retain, nonatomic) id <O2OCommentPublishViewRenderProtocol> render; // @synthesize render=_render;
@property(retain, nonatomic) O2OCommentProtocolHelper *protocolHelper; // @synthesize protocolHelper=_protocolHelper;
@property(nonatomic) unsigned long long viewStyle; // @synthesize viewStyle=_viewStyle;
@property(readonly, nonatomic) O2OCommentInitContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
@property(readonly, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
- (void)showError:(id)arg1 withModel:(id)arg2;
- (void)showModel:(id)arg1;
- (void)showLoading:(id)arg1;
@property(readonly, nonatomic) O2OCommentPublishModel *publishModel; // @synthesize publishModel=_publishModel;
@property(readonly, nonatomic) O2OCommentInitModel *infoModel; // @synthesize infoModel=_infoModel;
- (void)showAnonymousAlert:(id)arg1;
- (void)handlePublishError:(id)arg1;
- (void)goCommentSuccess;
- (void)populateShareInfo;
- (void)populatePublishModel;
- (void)postComment;
- (_Bool)hasContent;
- (void)goRealNameAuthentication;
- (_Bool)isCommentScoreVaild;
- (void)back;
- (void)forceEndEditing;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (id)pageSpm;
- (id)initWithScheme:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

