//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class KBCOMMENTActivityRpcInfo, NSArray, NSString, NSTimer, UIImageView, UIScrollView, UIViewController;
@protocol O2OCommentInputAccesoryViewDelegate;

@interface O2OCommentInputAccesoryView : UIView
{
    NSArray *_items;
    KBCOMMENTActivityRpcInfo *_activity;
    NSTimer *_timer;
    id <O2OCommentInputAccesoryViewDelegate> _delegate;
    _Bool _isArrowShow;
    NSString *_shopId;
    UIViewController *_vc;
    UIScrollView *_scrollView;
    UIView *_arrowView;
    UIImageView *_toggleKeyboardImageView;
}

@property(retain, nonatomic) UIImageView *toggleKeyboardImageView; // @synthesize toggleKeyboardImageView=_toggleKeyboardImageView;
@property(nonatomic) _Bool isArrowShow; // @synthesize isArrowShow=_isArrowShow;
@property(retain, nonatomic) UIView *arrowView; // @synthesize arrowView=_arrowView;
@property(retain, nonatomic) UIScrollView *scrollView; // @synthesize scrollView=_scrollView;
@property(nonatomic) __weak UIViewController *vc; // @synthesize vc=_vc;
@property(retain, nonatomic) NSString *shopId; // @synthesize shopId=_shopId;
- (void).cxx_destruct;
- (void)toggleKeyBoard:(id)arg1;
- (void)dismissArrow;
- (void)buttonAction:(id)arg1;
- (id)initWithItems:(id)arg1 activity:(id)arg2 delegate:(id)arg3;

@end

