//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

@class NSArray;
@protocol O2OCategorySegmentViewDelegate;

@interface O2OCategorySegmentView : UIScrollView
{
    unsigned long long _selectIndex;
    NSArray *_data;
    id <O2OCategorySegmentViewDelegate> _selectDelegate;
}

@property(nonatomic) __weak id <O2OCategorySegmentViewDelegate> selectDelegate; // @synthesize selectDelegate=_selectDelegate;
@property(retain, nonatomic) NSArray *data; // @synthesize data=_data;
- (void).cxx_destruct;
- (void)changeViewState:(id)arg1;
- (void)selectItemAtIndex:(unsigned long long)arg1;
- (void)selectItem:(id)arg1;
- (id)getSegmentView:(unsigned long long)arg1;
- (void)setupViews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

