//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "O2OCommonCDPAdapter.h"

@class NSMutableDictionary, NSString, O2OAtmosphereProcesser, O2OCDPSyncObject, O2OChannelMaskProcesser, O2OHomePageScreenMaskProcesser;

@interface O2OCDPAdapter : O2OCommonCDPAdapter
{
    O2OCDPSyncObject *_currentDisplaySyncObject;
    O2OChannelMaskProcesser *_currentChannelMaskProcesser;
    O2OHomePageScreenMaskProcesser *_currentHomePageMaskProcesser;
    O2OAtmosphereProcesser *_currentAtmosphereProcesser;
    NSMutableDictionary *_merchantDetailPromotionObservers;
    NSString *_cacheCityCode;
}

+ (id)cdpExtInfo;
+ (void)indexMayaDidHide:(id)arg1;
+ (void)removeAvailableTabRedPointCDPObject;
+ (void)removeAvailableSyncObject;
+ (_Bool)checkAvailablePromotionWithChannelSpaceCode:(id)arg1;
+ (long long)availableTabPromotionPriority;
+ (id)availablePomotionObjectId;
+ (_Bool)hasMaskShowing;
+ (_Bool)hasCDPMaskImage;
+ (void)checkSpaceCodesForMaskTabSync;
+ (void)checkSpaceCodesWithCityInfo:(id)arg1;
+ (void)promotionShouldRefresh:(_Bool)arg1;
+ (void)addMerchantDetailObserver:(id)arg1 extInfo:(id)arg2 spaceCodes:(id)arg3;
+ (void)removePopEyeObserver:(id)arg1;
+ (void)addPopEyeObserver:(id)arg1 extInfo:(id)arg2;
+ (void)removeAddAppraiseObserver:(id)arg1;
+ (void)addAddAppraiseObserver:(id)arg1 cityCode:(id)arg2;
+ (void)removeAllMyCommentsObserver:(id)arg1;
+ (void)addAllMyCommentsObserver:(id)arg1 cityCode:(id)arg2;
+ (void)removeCommentSuccessObserver:(id)arg1;
+ (void)addCommentSuccessObserver:(id)arg1 spaceCode:(id)arg2;
+ (void)removeHomePageObserver:(id)arg1;
+ (void)addHomePageObserver:(id)arg1;
+ (void)unregisterTabSync;
+ (void)registerTabSync;
+ (id)sharedInstance;
@property(retain, nonatomic) NSString *cacheCityCode; // @synthesize cacheCityCode=_cacheCityCode;
@property(retain, nonatomic) NSMutableDictionary *merchantDetailPromotionObservers; // @synthesize merchantDetailPromotionObservers=_merchantDetailPromotionObservers;
- (void).cxx_destruct;
- (id)generateLocationExtInfo;
- (id)generatePromotionObserverId:(id)arg1;
- (void)handleO2OCDPMaskDataWithSpaceInfo:(id)arg1;
- (void)handleO2OCDPMaskDataWithSpaceObject:(id)arg1 spaceInfo:(id)arg2 spaceCode:(id)arg3;
- (void)handleAtmosphereMayaWithSpaceObject:(id)arg1 spaceInfo:(id)arg2 spaceCode:(id)arg3;
- (_Bool)isAtmosphereMaya:(id)arg1;
- (void)handleO2OCDPHomepageScreenDataWithSpaceInfo:(id)arg1;
- (void)handleO2OPublishMaskNoticeWithSpaceInfo:(id)arg1;
- (void)promotionDataDidFinishLoading:(id)arg1 spaceCode:(id)arg2;
- (_Bool)_checkAvailableHomeMaskView;
- (void)checkAvailabelAtmosphere;
- (void)getSpaceInfo:(id)arg1 observer:(id)arg2 extInfo:(id)arg3;
- (void)userDidLogin:(id)arg1;
- (void)dealloc;
- (id)init;

@end

