//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIButton.h>

@class NSArray, NSString, UIFont, UIImage, UIImageView, UILabel;

@interface O2OEmoticonRateButton : UIButton
{
    unsigned long long _emoticonOrientation;
    long long _commentLevel;
    UIImageView *_emoticonImageView;
    UIImageView *_emoticonAnimationView;
    UILabel *_emoticonTitleLabel;
    NSString *_emoticonTitle;
    UIFont *_emoticonTitleFont;
    UIImage *_lookFrontImage;
    UIImage *_lookLeftImage;
    UIImage *_lookRightImage;
    UIImage *_focusImage;
    UIImage *_maskImage;
    NSArray *_focusAnimationImage;
    NSArray *_frontToRightAnimationImage;
    NSArray *_rightToRightAnimationImage;
    NSArray *_leftToRightAnimationImage;
    NSArray *_frontToLeftAnimationImage;
    NSArray *_rightToLeftAnimationImage;
    NSArray *_leftToLeftAnimationImage;
    unsigned long long _index;
    CDUnknownBlockType _cancelAction;
}

+ (id)gifImageNamed:(id)arg1;
@property(copy, nonatomic) CDUnknownBlockType cancelAction; // @synthesize cancelAction=_cancelAction;
@property(nonatomic) unsigned long long index; // @synthesize index=_index;
@property(retain, nonatomic) NSArray *leftToLeftAnimationImage; // @synthesize leftToLeftAnimationImage=_leftToLeftAnimationImage;
@property(retain, nonatomic) NSArray *rightToLeftAnimationImage; // @synthesize rightToLeftAnimationImage=_rightToLeftAnimationImage;
@property(retain, nonatomic) NSArray *frontToLeftAnimationImage; // @synthesize frontToLeftAnimationImage=_frontToLeftAnimationImage;
@property(retain, nonatomic) NSArray *leftToRightAnimationImage; // @synthesize leftToRightAnimationImage=_leftToRightAnimationImage;
@property(retain, nonatomic) NSArray *rightToRightAnimationImage; // @synthesize rightToRightAnimationImage=_rightToRightAnimationImage;
@property(retain, nonatomic) NSArray *frontToRightAnimationImage; // @synthesize frontToRightAnimationImage=_frontToRightAnimationImage;
@property(retain, nonatomic) NSArray *focusAnimationImage; // @synthesize focusAnimationImage=_focusAnimationImage;
@property(retain, nonatomic) UIImage *maskImage; // @synthesize maskImage=_maskImage;
@property(retain, nonatomic) UIImage *focusImage; // @synthesize focusImage=_focusImage;
@property(retain, nonatomic) UIImage *lookRightImage; // @synthesize lookRightImage=_lookRightImage;
@property(retain, nonatomic) UIImage *lookLeftImage; // @synthesize lookLeftImage=_lookLeftImage;
@property(retain, nonatomic) UIImage *lookFrontImage; // @synthesize lookFrontImage=_lookFrontImage;
@property(retain, nonatomic) UIFont *emoticonTitleFont; // @synthesize emoticonTitleFont=_emoticonTitleFont;
@property(copy, nonatomic) NSString *emoticonTitle; // @synthesize emoticonTitle=_emoticonTitle;
@property(retain, nonatomic) UILabel *emoticonTitleLabel; // @synthesize emoticonTitleLabel=_emoticonTitleLabel;
@property(retain, nonatomic) UIImageView *emoticonAnimationView; // @synthesize emoticonAnimationView=_emoticonAnimationView;
@property(retain, nonatomic) UIImageView *emoticonImageView; // @synthesize emoticonImageView=_emoticonImageView;
@property(nonatomic) long long commentLevel; // @synthesize commentLevel=_commentLevel;
@property(nonatomic) unsigned long long emoticonOrientation; // @synthesize emoticonOrientation=_emoticonOrientation;
- (void).cxx_destruct;
- (void)stopAnimation;
- (void)reset;
- (void)setAnimationProgress:(double)arg1;
- (void)focus;
- (void)lookAt:(unsigned long long)arg1;
- (_Bool)isAnimating;
- (void)layoutSubviews;
- (void)setupUI;
- (id)initWithFrame:(struct CGRect)arg1 emojiName:(id)arg2 title:(id)arg3 titleFont:(id)arg4;

@end

