//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class NSString, O2OFilterTagsListView, UILabel;

@interface O2OHeaderAndTagsView : UIView
{
    UILabel *_textLabel;
    O2OFilterTagsListView *_tagListView;
    unsigned long long _idx;
    NSString *_groupCode;
    unsigned long long _type;
}

@property(nonatomic) unsigned long long type; // @synthesize type=_type;
@property(copy, nonatomic) NSString *groupCode; // @synthesize groupCode=_groupCode;
@property(nonatomic) unsigned long long idx; // @synthesize idx=_idx;
@property(retain, nonatomic) O2OFilterTagsListView *tagListView; // @synthesize tagListView=_tagListView;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
- (void).cxx_destruct;
- (void)resetStatus;
- (void)reloadData:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

