//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "O2OMistModel.h"

#import "O2OHTTPModelMTOPInterface-Protocol.h"
#import "O2OHTTPRequestProtocol-Protocol.h"

@class NSString;

@interface O2OMtopModel : O2OMistModel <O2OHTTPModelMTOPInterface, O2OHTTPRequestProtocol>
{
    NSString *_mtopTraceId;
}

@property(retain, nonatomic) NSString *mtopTraceId; // @synthesize mtopTraceId=_mtopTraceId;
- (void).cxx_destruct;
- (id)headerParams;
- (void)prepareRequest;
- (_Bool)shouldLoad;
- (id)createRequest;
- (_Bool)shouldCacheResponse:(id)arg1;
- (void)aftereSavingCache;
- (void)beforeSavingCache;
- (_Bool)cacheResponse:(id)arg1;
- (id)requestParameters;
- (id)apiVersion;
- (id)apiName;
- (_Bool)useMtop;
- (id)modelClassName;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

