//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface O2OPhotoTools : NSObject
{
}

+ (struct CGSize)sizeWithText:(id)arg1 constrainedSize:(struct CGSize)arg2 maxWidth:(double)arg3 font:(id)arg4;
+ (id)imageFromColor:(id)arg1 withSize:(struct CGRect)arg2;

@end

