//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class UIColor, UIImage;

@interface O2OProgressView : UIView
{
    UIView *_progressView;
    float _progress;
    _Bool _isTile;
    long long _progressViewStyle;
    UIColor *_progressTintColor;
    UIColor *_trackTintColor;
    UIImage *_progressImage;
    UIImage *_trackImage;
}

@property(retain, nonatomic) UIImage *trackImage; // @synthesize trackImage=_trackImage;
@property(retain, nonatomic) UIImage *progressImage; // @synthesize progressImage=_progressImage;
@property(retain, nonatomic) UIColor *trackTintColor; // @synthesize trackTintColor=_trackTintColor;
@property(retain, nonatomic) UIColor *progressTintColor; // @synthesize progressTintColor=_progressTintColor;
@property(nonatomic) _Bool isTile; // @synthesize isTile=_isTile;
@property(nonatomic) long long progressViewStyle; // @synthesize progressViewStyle=_progressViewStyle;
- (void).cxx_destruct;
- (id)stretchableWithImage:(id)arg1;
@property(nonatomic) float progress;
- (id)initWithFrame:(struct CGRect)arg1 progressViewStyle:(long long)arg2;
- (id)initWithFrame:(struct CGRect)arg1;

@end

