//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString;

@interface O2OSearchConfig : NSObject
{
    NSString *_cityCode;
    NSString *_businessAreaId;
    NSDictionary *_config;
    NSDictionary *_commonConfig;
}

+ (_Bool)laterBecomeActive;
+ (_Bool)homeSearchPushNoAnimation;
+ (_Bool)shouldAsyncLoadResultView;
+ (_Bool)shouldAdvanceLocating;
+ (_Bool)topicPageUseTinyApp;
+ (_Bool)shouldCategoryPOIShow;
+ (_Bool)hotwordStickyLimit;
+ (_Bool)forbidThroughToTop;
+ (_Bool)forbidCacheBounce;
+ (_Bool)searchResultPartialLoad;
+ (long long)cachePolicy;
+ (_Bool)blockCacheLoading;
+ (id)remoteCommonConfig;
+ (_Bool)remoteBoolConfigForKey:(id)arg1;
+ (id)remoteConfig;
+ (_Bool)isSearchResultTarget:(id)arg1;
+ (_Bool)isSearchTarget:(id)arg1;
+ (_Bool)isClassifyTarget:(id)arg1;
+ (_Bool)isSearchHome:(id)arg1;
+ (_Bool)mapSearchClassifyEntryOpen;
+ (_Bool)mapSearchEntryOpen;
+ (long long)voiceSearchConfig;
+ (double)latitude:(id)arg1;
+ (double)longitude:(id)arg1;
+ (id)selLocationLatitude:(id)arg1 andLongitude:(id)arg2 accuracy:(id)arg3;
+ (id)formatedQueryIndex;
+ (id)generateNewSessionId;
+ (id)generateNewTokenId;
+ (id)sessionId;
+ (void)renewSearchSession;
+ (id)sharedInstance;
@property(copy, nonatomic) NSDictionary *commonConfig; // @synthesize commonConfig=_commonConfig;
@property(copy, nonatomic) NSDictionary *config; // @synthesize config=_config;
@property(retain, nonatomic) NSString *businessAreaId; // @synthesize businessAreaId=_businessAreaId;
@property(retain, nonatomic) NSString *cityCode; // @synthesize cityCode=_cityCode;
- (void).cxx_destruct;

@end

