//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "DTViewController.h"

#import "MessageBoxProtocol-Protocol.h"

@class MBBaseMenuView, MessageBoxView, NSDictionary, NSString;

@interface PaymentAssistViewController : DTViewController <MessageBoxProtocol>
{
    NSDictionary *_param;
    MessageBoxView *_messageBoxView;
    MBBaseMenuView *_baseMenuView;
}

@property(readonly, nonatomic) MBBaseMenuView *baseMenuView; // @synthesize baseMenuView=_baseMenuView;
@property(retain, nonatomic) MessageBoxView *messageBoxView; // @synthesize messageBoxView=_messageBoxView;
@property(retain, nonatomic) NSDictionary *param; // @synthesize param=_param;
- (void).cxx_destruct;
- (void)menuInfoUpdate:(id)arg1;
- (void)reloadMenuView:(id)arg1;
- (id)getWKBuilder;
- (void)showMsgSettingPage;
- (void)addNavigatorRightBtn;
- (void)viewDidLoad;
- (id)initWithParam:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

