//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIControl.h>

@class RecommendItemPB, UILabel, UIView;

@interface PFRecommendView : UIControl
{
    UILabel *_iconLabel;
    UILabel *_titleLabel;
    UILabel *_textLabel;
    UIView *_arrowIcon;
    RecommendItemPB *_model;
}

+ (void)loadDataWithBlock:(CDUnknownBlockType)arg1;
+ (_Bool)shouldShow:(id)arg1;
@property(retain, nonatomic) RecommendItemPB *model; // @synthesize model=_model;
@property(retain, nonatomic) UIView *arrowIcon; // @synthesize arrowIcon=_arrowIcon;
@property(retain, nonatomic) UILabel *textLabel; // @synthesize textLabel=_textLabel;
@property(retain, nonatomic) UILabel *titleLabel; // @synthesize titleLabel=_titleLabel;
@property(retain, nonatomic) UILabel *iconLabel; // @synthesize iconLabel=_iconLabel;
- (void).cxx_destruct;
- (void)updateIconText:(id)arg1 title:(id)arg2 text:(id)arg3;
- (void)buttonAction;
- (void)showInView:(id)arg1;
- (id)init;

@end

