//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class MFAttributeLabel, NSDictionary, PKImageView, PKTranslaterNameView, UILongPressGestureRecognizer, UITapGestureRecognizer;
@protocol PKTranslateContentDelegate;

@interface PKTranslateContentView : UIView
{
    NSDictionary *_templateData;
    id <PKTranslateContentDelegate> _delegate;
    PKTranslaterNameView *_translateNameView;
    UIView *_seperatorLine;
    PKImageView *_backgroundImageView;
    MFAttributeLabel *_translateContentLabel;
    NSDictionary *_chatDataSource;
    UILongPressGestureRecognizer *_longPress;
    UILongPressGestureRecognizer *_voiceOverLongPress;
    UITapGestureRecognizer *_tapGesture;
    UITapGestureRecognizer *_doubleTabGesture;
    struct CGSize _componentSize;
}

+ (struct CGSize)sizeOfTranslateContentViewByCellID:(id)arg1 dataDict:(id)arg2 cellDict:(id)arg3;
@property(retain, nonatomic) UITapGestureRecognizer *doubleTabGesture; // @synthesize doubleTabGesture=_doubleTabGesture;
@property(retain, nonatomic) UITapGestureRecognizer *tapGesture; // @synthesize tapGesture=_tapGesture;
@property(retain, nonatomic) UILongPressGestureRecognizer *voiceOverLongPress; // @synthesize voiceOverLongPress=_voiceOverLongPress;
@property(retain, nonatomic) UILongPressGestureRecognizer *longPress; // @synthesize longPress=_longPress;
@property(retain, nonatomic) NSDictionary *chatDataSource; // @synthesize chatDataSource=_chatDataSource;
@property(retain, nonatomic) MFAttributeLabel *translateContentLabel; // @synthesize translateContentLabel=_translateContentLabel;
@property(retain, nonatomic) PKImageView *backgroundImageView; // @synthesize backgroundImageView=_backgroundImageView;
@property(retain, nonatomic) UIView *seperatorLine; // @synthesize seperatorLine=_seperatorLine;
@property(retain, nonatomic) PKTranslaterNameView *translateNameView; // @synthesize translateNameView=_translateNameView;
@property(nonatomic) __weak id <PKTranslateContentDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) struct CGSize componentSize; // @synthesize componentSize=_componentSize;
- (void).cxx_destruct;
- (void)translationCardDoubleTapped:(id)arg1;
- (void)translationCardTapped:(id)arg1;
- (void)longPress:(id)arg1;
- (id)linkForTouchPoint:(struct CGPoint)arg1;
- (id)accessibilityLabel;
- (_Bool)isAccessibilityElement;
- (void)bindDataWith:(id)arg1;
- (struct CGSize)calculateLabelSizeWithText:(id)arg1 font:(id)arg2 maxSize:(struct CGSize)arg3 numberOfLines:(long long)arg4 lineBreakMode:(unsigned char)arg5 detectHtmlEmotion:(int)arg6;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

