//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NBPluginBase.h"

@class NSString;
@protocol NBNavigationTitleViewProtocol;

@interface Plugin4TitleView : NBPluginBase
{
    _Bool _shouldShowTirdLoading;
    _Bool _shouldSetDefaultColor;
    NSString *_cachedTitle;
    id <NBNavigationTitleViewProtocol> _h5titleView;
}

@property(nonatomic) _Bool shouldSetDefaultColor; // @synthesize shouldSetDefaultColor=_shouldSetDefaultColor;
@property(nonatomic) __weak id <NBNavigationTitleViewProtocol> h5titleView; // @synthesize h5titleView=_h5titleView;
@property(nonatomic) _Bool shouldShowTirdLoading; // @synthesize shouldShowTirdLoading=_shouldShowTirdLoading;
@property(retain, nonatomic) NSString *cachedTitle; // @synthesize cachedTitle=_cachedTitle;
- (void).cxx_destruct;
- (void)onSubTitleClicked;
- (void)setTitle:(id)arg1 subTitle:(id)arg2 dropdownList:(id)arg3 dropdownInit:(int)arg4;
- (void)setTitle:(id)arg1 context:(id)arg2 responseCallback:(CDUnknownBlockType)arg3;
- (int)priority;
- (id)currentViewController;
- (id)createNavigationTitleView:(struct CGRect)arg1 vc:(id)arg2;
- (void)setSecurityTipViewIconWithVC:(id)arg1 titleView:(id)arg2 defaultSkin:(_Bool)arg3 url:(id)arg4;
- (void)handleEvent:(id)arg1;
- (void)addJSApis;
- (void)pluginDidLoad;

@end

