//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIView.h>

@class FBDocument, NSDictionary, NSString, WKEasyViewBuilder;

@interface PPDetailBirdView : UIView
{
    WKEasyViewBuilder *_easyViewBuilder;
    FBDocument *_doc;
    NSString *_action;
    NSDictionary *_bizMonitor;
    NSString *_contentId;
}

@property(copy, nonatomic) NSString *contentId; // @synthesize contentId=_contentId;
@property(retain, nonatomic) NSDictionary *bizMonitor; // @synthesize bizMonitor=_bizMonitor;
@property(retain, nonatomic) NSString *action; // @synthesize action=_action;
@property(retain, nonatomic) FBDocument *doc; // @synthesize doc=_doc;
@property(retain, nonatomic) WKEasyViewBuilder *easyViewBuilder; // @synthesize easyViewBuilder=_easyViewBuilder;
- (void).cxx_destruct;
- (void)tapGesture;
- (double)updateInfo:(id)arg1 templateId:(id)arg2 bizMonitor:(id)arg3;

@end

