//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface PPJsApiHomePageLifecyleHelper : NSObject
{
}

- (void)updateBox:(id)arg1 lastestModel:(id)arg2 publicId:(id)arg3 userId:(id)arg4;
- (void)updateServiceBox:(id)arg1 lastestModel:(id)arg2 publicId:(id)arg3 userId:(id)arg4;
- (void)updateFriendTab:(id)arg1 userId:(id)arg2;
- (void)updateBox:(id)arg1 userId:(id)arg2;
- (void)markAllMessagesRead:(id)arg1 userId:(id)arg2;
- (void)updateRecentVisit:(id)arg1 userId:(id)arg2;
- (void)updateLastOpertionTime:(id)arg1 userId:(id)arg2;
- (void)pageLeave:(id)arg1 userId:(id)arg2;
- (void)pageEnter:(id)arg1 userId:(id)arg2 sourceId:(id)arg3;

@end

