//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSArray, NSString, publictestTemplateVoPB;

@interface publictestTaskVoPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *appScheme; // @dynamic appScheme;
@property(retain, nonatomic) NSString *appid; // @dynamic appid;
@property(readonly) _Bool hasAppScheme; // @dynamic hasAppScheme;
@property(readonly) _Bool hasAppid; // @dynamic hasAppid;
@property(readonly) _Bool hasHomePageSchema; // @dynamic hasHomePageSchema;
@property(readonly) _Bool hasLevelScore; // @dynamic hasLevelScore;
@property(readonly) _Bool hasProgressStatus; // @dynamic hasProgressStatus;
@property(readonly) _Bool hasProjectDetailSchema; // @dynamic hasProjectDetailSchema;
@property(readonly) _Bool hasProjectId; // @dynamic hasProjectId;
@property(readonly) _Bool hasProjectType; // @dynamic hasProjectType;
@property(readonly) _Bool hasReviewResult; // @dynamic hasReviewResult;
@property(readonly) _Bool hasRewardScore; // @dynamic hasRewardScore;
@property(readonly) _Bool hasSubPageType; // @dynamic hasSubPageType;
@property(readonly) _Bool hasTaskExpect; // @dynamic hasTaskExpect;
@property(readonly) _Bool hasTaskGoal; // @dynamic hasTaskGoal;
@property(readonly) _Bool hasTaskId; // @dynamic hasTaskId;
@property(readonly) _Bool hasTaskName; // @dynamic hasTaskName;
@property(readonly) _Bool hasTemplateData; // @dynamic hasTemplateData;
@property(readonly) _Bool hasTemplateId; // @dynamic hasTemplateId;
@property(readonly) _Bool hasWaspProjectId; // @dynamic hasWaspProjectId;
@property(retain, nonatomic) NSString *homePageSchema; // @dynamic homePageSchema;
@property(nonatomic) double levelScore; // @dynamic levelScore;
@property(retain, nonatomic) NSString *progressStatus; // @dynamic progressStatus;
@property(retain, nonatomic) NSString *projectDetailSchema; // @dynamic projectDetailSchema;
@property(nonatomic) int projectId; // @dynamic projectId;
@property(nonatomic) int projectType; // @dynamic projectType;
@property(retain, nonatomic) NSString *reviewResult; // @dynamic reviewResult;
@property(nonatomic) double rewardScore; // @dynamic rewardScore;
@property(retain, nonatomic) NSString *subPageType; // @dynamic subPageType;
@property(retain, nonatomic) NSString *taskExpect; // @dynamic taskExpect;
@property(retain, nonatomic) NSString *taskGoal; // @dynamic taskGoal;
@property(nonatomic) int taskId; // @dynamic taskId;
@property(retain, nonatomic) NSString *taskName; // @dynamic taskName;
@property(retain, nonatomic) NSArray *taskStepList; // @dynamic taskStepList;
@property(retain, nonatomic) publictestTemplateVoPB *templateData; // @dynamic templateData;
@property(retain, nonatomic) NSString *templateId; // @dynamic templateId;
@property(nonatomic) int waspProjectId; // @dynamic waspProjectId;

@end

