//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSArray, NSString;

@interface publictestMoreMenuVoPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *enumId; // @dynamic enumId;
@property(retain, nonatomic) NSArray *enums; // @dynamic enums;
@property(readonly) _Bool hasEnumId; // @dynamic hasEnumId;
@property(readonly) _Bool hasTipsContent; // @dynamic hasTipsContent;
@property(readonly) _Bool hasTipsType; // @dynamic hasTipsType;
@property(retain, nonatomic) NSString *tipsContent; // @dynamic tipsContent;
@property(nonatomic) int tipsType; // @dynamic tipsType;

@end

