//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "QEngineBaseManager.h"

@interface QEngineInfoExManager : QEngineBaseManager
{
}

- (id)dataStore;
- (Class)dataAdapterClass;
- (Class)getBizClass;
- (void)onCompleteWithStocksList:(id)arg1 update:(int)arg2 rpcObservers:(id)arg3;
- (void)loadAndUpdateInfoExt:(id)arg1 needSync:(_Bool)arg2 withObserver:(id)arg3;
- (void)pullInfoExt:(id)arg1 needSync:(_Bool)arg2 observer:(id)arg3 finishBlock:(CDUnknownBlockType)arg4;
- (void)requestList:(id)arg1 strategy:(id)arg2 observer:(id)arg3;

@end

