//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSArray, NSString, QEngineBaseManager;

@protocol QEngineDataStoreProtocol <NSObject>
@property(retain, nonatomic) QEngineBaseManager *manager;
- (void)deleteWithKey:(NSString *)arg1 userPreferences:(_Bool)arg2;
- (NSString *)readWithKey:(NSString *)arg1 userPreferences:(_Bool)arg2;
- (void)saveWithKey:(NSString *)arg1 value:(NSString *)arg2 userPreferences:(_Bool)arg3;
- (void)deleteWithSymbol:(NSString *)arg1;
- (NSArray *)readDBWithSymbol:(NSString *)arg1;
- (void)saveWithBizData:(NSArray *)arg1;
@end

