//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface QEngineStockMinuteModel : NSObject
{
    _Bool _isIncrease;
    NSString *_symbol;
    NSString *_stockStatus;
    NSString *_lastClose;
    NSArray *_list;
}

@property(retain, nonatomic) NSArray *list; // @synthesize list=_list;
@property(retain, nonatomic) NSString *lastClose; // @synthesize lastClose=_lastClose;
@property(nonatomic) _Bool isIncrease; // @synthesize isIncrease=_isIncrease;
@property(retain, nonatomic) NSString *stockStatus; // @synthesize stockStatus=_stockStatus;
@property(retain, nonatomic) NSString *symbol; // @synthesize symbol=_symbol;
- (void).cxx_destruct;

@end

