//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "REAuthViewControllerDelegate-Protocol.h"
#import "REOPPhaseDelegate-Protocol.h"

@class NSString, REOPContext;

@interface REOpenPacketManager : NSObject <REOPPhaseDelegate, REAuthViewControllerDelegate>
{
    REOPContext *_context;
}

+ (id)shareInstance;
@property(retain, nonatomic) REOPContext *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (void)contextDidClean:(id)arg1;
- (void)handleWidthOptions:(id)arg1;
- (void)startAppNotification:(id)arg1;
- (void)exitRedEnvelopeAppNotification:(id)arg1;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

