//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RVKBridgeExtension.h"

#import "NXEvent4RVPBridgeExtension4TCP-Protocol.h"

@class NSString;

@interface RVPBridgeExtension4TCP : RVKBridgeExtension <NXEvent4RVPBridgeExtension4TCP>
{
}

+ (void)__RVK_export__closeTCPSocket854;
+ (void)__RVK_export__sendTCPMessage683;
+ (void)__RVK_export__connectTCPSocket442;
+ (void)__RVK_export__createTCPSocket171;
- (void)closeTCPSocket:(id)arg1 originParam:(id)arg2 page:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (void)sendTCPMessage:(id)arg1 isHex:(id)arg2 offset:(id)arg3 length:(id)arg4 originParam:(id)arg5 page:(id)arg6 callback:(CDUnknownBlockType)arg7;
- (void)connectTCPSocket:(id)arg1 address:(id)arg2 port:(id)arg3 timeout:(id)arg4 originParam:(id)arg5 page:(id)arg6 callback:(CDUnknownBlockType)arg7;
- (void)createTCPSocket:(id)arg1 multiple:(id)arg2 originParam:(id)arg3 page:(id)arg4 callback:(CDUnknownBlockType)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

