//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RVKBridgeExtension.h"

#import "NXEvent4RVPBridgeExtension4SystemInfo-Protocol.h"

@class NSMutableDictionary, NSString;

@interface RVPBridgeExtension4SystemInfo : RVKBridgeExtension <NXEvent4RVPBridgeExtension4SystemInfo>
{
    NSMutableDictionary *_cachedResult;
    double _cachedTime;
}

+ (void)__RVK_export__getSystemInfo270;
@property(nonatomic) double cachedTime; // @synthesize cachedTime=_cachedTime;
@property(retain, nonatomic) NSMutableDictionary *cachedResult; // @synthesize cachedResult=_cachedResult;
- (void).cxx_destruct;
- (id)appVersion;
- (id)customTitleBarHeightForScene:(id)arg1;
- (id)fontSize;
- (id)currentLanguage;
- (id)clientName;
- (id)deviceVersion;
- (_Bool)h5AutoTransparentWith:(id)arg1;
- (id)extendSystemInfo:(id)arg1;
- (double)diskOfAllSizeMBytes;
- (id)generateNoCacheDataWithScene:(id)arg1;
- (id)generateSystemInfoWithScene:(id)arg1;
- (_Bool)shouldUseCache;
- (void)orientationDidChange:(id)arg1;
- (void)dealloc;
- (void)getSystemInfo:(_Bool)arg1 originParam:(id)arg2 page:(id)arg3 callback:(CDUnknownBlockType)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

