//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RVKJSApiRequestBase.h"

@class NSString;

@interface RVPJSApiReqTradePay : RVKJSApiRequestBase
{
    NSString *_tradeNO;
    NSString *_bizType;
    NSString *_bizSubType;
    NSString *_bizContext;
    NSString *_orderStr;
}

@property(retain, nonatomic) NSString *orderStr; // @synthesize orderStr=_orderStr;
@property(retain, nonatomic) NSString *bizContext; // @synthesize bizContext=_bizContext;
@property(retain, nonatomic) NSString *bizSubType; // @synthesize bizSubType=_bizSubType;
@property(retain, nonatomic) NSString *bizType; // @synthesize bizType=_bizType;
@property(retain, nonatomic) NSString *tradeNO; // @synthesize tradeNO=_tradeNO;
- (void).cxx_destruct;

@end

