//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "RVKJSApiRequestBase.h"

@class NSString;

@interface RVPJSApiReqLocalStorageClear : RVKJSApiRequestBase
{
    NSString *_business;
}

@property(retain, nonatomic) NSString *business; // @synthesize business=_business;
- (void).cxx_destruct;

@end

