//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "APDPBGeneratedMessage.h"

@class NSString;

@interface safeboxSafeboxRecordListQueryResultPB : APDPBGeneratedMessage
{
}

+ (CDStruct_af61540b *)_fieldInfos;

// Remaining properties
@property(retain, nonatomic) NSString *encryptSafeboxOutrReocrdJson; // @dynamic encryptSafeboxOutrReocrdJson;
@property(retain, nonatomic) NSString *encryptSafeboxRecordListJson; // @dynamic encryptSafeboxRecordListJson;
@property(retain, nonatomic) NSString *encryptSafeboxTagJson; // @dynamic encryptSafeboxTagJson;
@property(readonly) _Bool hasEncryptSafeboxOutrReocrdJson; // @dynamic hasEncryptSafeboxOutrReocrdJson;
@property(readonly) _Bool hasEncryptSafeboxRecordListJson; // @dynamic hasEncryptSafeboxRecordListJson;
@property(readonly) _Bool hasEncryptSafeboxTagJson; // @dynamic hasEncryptSafeboxTagJson;
@property(readonly) _Bool hasMaxImageCount; // @dynamic hasMaxImageCount;
@property(readonly) _Bool hasMaxRecordCount; // @dynamic hasMaxRecordCount;
@property(readonly) _Bool hasPageIndex; // @dynamic hasPageIndex;
@property(readonly) _Bool hasPageSize; // @dynamic hasPageSize;
@property(readonly) _Bool hasPb_hasMore; // @dynamic hasPb_hasMore;
@property(readonly) _Bool hasRecordCount; // @dynamic hasRecordCount;
@property(readonly) _Bool hasResultCode; // @dynamic hasResultCode;
@property(readonly) _Bool hasResultDesc; // @dynamic hasResultDesc;
@property(readonly) _Bool hasSuccess; // @dynamic hasSuccess;
@property(nonatomic) int maxImageCount; // @dynamic maxImageCount;
@property(nonatomic) int maxRecordCount; // @dynamic maxRecordCount;
@property(nonatomic) int pageIndex; // @dynamic pageIndex;
@property(nonatomic) int pageSize; // @dynamic pageSize;
@property(nonatomic) _Bool pb_hasMore; // @dynamic pb_hasMore;
@property(nonatomic) int recordCount; // @dynamic recordCount;
@property(retain, nonatomic) NSString *resultCode; // @dynamic resultCode;
@property(retain, nonatomic) NSString *resultDesc; // @dynamic resultDesc;
@property(nonatomic) _Bool success; // @dynamic success;

@end

