//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AFCChartBaseDataModel.h"

@interface SDMinuteChartDataModel : AFCChartBaseDataModel
{
    CDStruct_12c6646e _breathLight;
}

@property(nonatomic) CDStruct_af61540b breathLight; // @synthesize breathLight=_breathLight;
- (void)dealloc;

@end

