//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SecVISECAUser : NSObject
{
    NSString *_commonName;
    NSString *_country;
    NSString *_locality;
    NSString *_province;
    NSString *_organization;
    NSString *_oU;
    NSString *_emailAddress;
}

@property(copy, nonatomic) NSString *emailAddress; // @synthesize emailAddress=_emailAddress;
@property(copy, nonatomic) NSString *oU; // @synthesize oU=_oU;
@property(copy, nonatomic) NSString *organization; // @synthesize organization=_organization;
@property(copy, nonatomic) NSString *province; // @synthesize province=_province;
@property(copy, nonatomic) NSString *locality; // @synthesize locality=_locality;
@property(copy, nonatomic) NSString *country; // @synthesize country=_country;
@property(copy, nonatomic) NSString *commonName; // @synthesize commonName=_commonName;
- (void).cxx_destruct;

@end

