//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "GWBaseResponse.h"

@class NSString;

@interface ShareResponse : GWBaseResponse
{
    NSString *_mockCard;
}

@property(retain, nonatomic) NSString *mockCard; // @synthesize mockCard=_mockCard;
- (void).cxx_destruct;

@end

