//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "SPMItem.h"

@class NSString;

@interface SPMOpenIdItem : SPMItem
{
    NSString *_openId;
}

@property(copy, nonatomic) NSString *openId; // @synthesize openId=_openId;
- (void).cxx_destruct;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithOpenId:(id)arg1;

@end

