//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface sportsprodCooperationDataSourceResult : NSObject
{
    _Bool _isSuccess;
    NSString *_resultCode;
    NSString *_resultDesc;
    NSString *_resultView;
    NSArray *_dataSourceVos;
}

+ (Class)dataSourceVosElementClass;
@property(retain, nonatomic) NSArray *dataSourceVos; // @synthesize dataSourceVos=_dataSourceVos;
@property(retain, nonatomic) NSString *resultView; // @synthesize resultView=_resultView;
@property(retain, nonatomic) NSString *resultDesc; // @synthesize resultDesc=_resultDesc;
@property(retain, nonatomic) NSString *resultCode; // @synthesize resultCode=_resultCode;
@property(nonatomic) _Bool isSuccess; // @synthesize isSuccess=_isSuccess;
- (void).cxx_destruct;

@end

