//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface SyncUpCallbackInfo : NSObject
{
    NSString *_biz;
    NSString *_msgID;
    NSString *_appName;
}

@property(retain, nonatomic) NSString *appName; // @synthesize appName=_appName;
@property(retain, nonatomic) NSString *msgID; // @synthesize msgID=_msgID;
@property(retain, nonatomic) NSString *biz; // @synthesize biz=_biz;
- (void).cxx_destruct;
- (id)init;

@end

