//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "PSDJsApiHandler.h"

@class H5WebViewController, NSMutableDictionary, NSString, UIImage;

@interface TAJsApiHandler4SaveImageToAlbum : PSDJsApiHandler
{
    H5WebViewController *_webViewController;
    CDUnknownBlockType _callback;
    NSString *_imageSrc;
    UIImage *_image;
    NSMutableDictionary *_imageCache;
}

@property(retain, nonatomic) NSMutableDictionary *imageCache; // @synthesize imageCache=_imageCache;
@property(retain, nonatomic) UIImage *image; // @synthesize image=_image;
@property(copy, nonatomic) NSString *imageSrc; // @synthesize imageSrc=_imageSrc;
@property(copy, nonatomic) CDUnknownBlockType callback; // @synthesize callback=_callback;
@property(nonatomic) __weak H5WebViewController *webViewController; // @synthesize webViewController=_webViewController;
- (void).cxx_destruct;
- (void)image:(id)arg1 didFinishSavingWithError:(id)arg2 contextInfo:(void *)arg3;
- (void)saveImage:(id)arg1 context:(id)arg2;
- (_Bool)checkIsGifImageWithImageSrc:(id)arg1;
- (void)getImageWithSrc:(id)arg1 context:(id)arg2 callback:(CDUnknownBlockType)arg3;
- (void)saveImageSrc:(id)arg1 context:(id)arg2;
- (void)savedImageWithError:(id)arg1 withImage:(id)arg2;
- (void)doHandler:(id)arg1 url:(id)arg2 context:(id)arg3 callback:(CDUnknownBlockType)arg4;
- (void)handler:(id)arg1 context:(id)arg2 callback:(CDUnknownBlockType)arg3;

@end

