//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TANavBarUtil : NSObject
{
}

+ (void)setStatusBarStyle:(long long)arg1 animated:(_Bool)arg2;
+ (_Bool)enableNaviBarShowFavorite:(id)arg1;
+ (_Bool)enabeNaviBarNewPopMenu:(id)arg1;
+ (void)resetNavigationBarBottomLineColor;

@end

