//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NBPluginBase.h"

#import "RVTraceDebugProtocol-Protocol.h"

@class NSMutableArray, NSString, RVTraceDataReporter, TAPerfDebugLaunchCost;

@interface TAPerfDebugPlugin : NBPluginBase <RVTraceDebugProtocol>
{
    _Bool _isTraceDebugging;
    TAPerfDebugLaunchCost *_launchCost;
    RVTraceDataReporter *_reporter;
    long long _prepareStartTimeUTC;
    long long _pageLoadedTimeUTC;
    NSString *_currentAppId;
    NSMutableArray *_jsApiRequestList;
}

@property(retain, nonatomic) NSMutableArray *jsApiRequestList; // @synthesize jsApiRequestList=_jsApiRequestList;
@property(nonatomic) _Bool isTraceDebugging; // @synthesize isTraceDebugging=_isTraceDebugging;
@property(retain, nonatomic) NSString *currentAppId; // @synthesize currentAppId=_currentAppId;
@property(nonatomic) long long pageLoadedTimeUTC; // @synthesize pageLoadedTimeUTC=_pageLoadedTimeUTC;
@property(nonatomic) long long prepareStartTimeUTC; // @synthesize prepareStartTimeUTC=_prepareStartTimeUTC;
@property(retain, nonatomic) RVTraceDataReporter *reporter; // @synthesize reporter=_reporter;
@property(retain, nonatomic) TAPerfDebugLaunchCost *launchCost; // @synthesize launchCost=_launchCost;
- (void).cxx_destruct;
- (void)gatherNetworkData:(id)arg1 isNebulaX:(_Bool)arg2;
- (void)gatherJSErrorData:(id)arg1 context:(id)arg2;
- (void)perfDebugHandler:(id)arg1;
- (void)traceDebugHandler:(id)arg1;
- (void)exitTinyAppWithSession:(id)arg1;
- (void)onStop;
- (_Bool)disableTraceDebug;
- (void)onStart:(id)arg1 session:(id)arg2;
- (long long)baseTime;
- (void)handleEvent:(id)arg1;
- (int)priority;
- (void)dealloc;
- (void)pluginDidLoad;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

