//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSSet;

@interface TAPluginWhiteTextManager : NSObject
{
    NSSet *_configSet;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSSet *configSet; // @synthesize configSet=_configSet;
- (void).cxx_destruct;
- (_Bool)hit:(id)arg1;
- (id)init;

@end

