//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TBHelper : NSObject
{
}

+ (_Bool)isShowTransferReminder;
+ (id)proccessShowInView:(id)arg1;
+ (struct CGSize)sizeForString:(id)arg1 font:(id)arg2 forWidth:(double)arg3;
+ (id)toAccountImageWithNamed:(id)arg1;

@end

