//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface TBRemoteLogger : NSObject
{
}

+ (void)writeSPMLogWithActionId:(id)arg1 extParams4:(id)arg2 spmId:(id)arg3 view:(id)arg4 logLevel:(id)arg5;
+ (void)logResultPageReminderClickInview:(id)arg1;
+ (void)writeEventLogWithResponseVO:(id)arg1 source:(id)arg2 methodName:(id)arg3;
+ (void)writeEventLogWithExtParams4:(id)arg1;

@end

