//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "TBSDKServer.h"

#import "MtopExtRequestDelegate-Protocol.h"

@class MTopPrefetch, MtopExtRequest, NSArray, NSDictionary, NSMutableDictionary, NSString, NSURL, TBSDKAsync4jInterceptor, UTDataSet;

@interface TBSDKMTOPServer : TBSDKServer <MtopExtRequestDelegate>
{
    _Bool _needEcodeSign;
    _Bool _isNeedWua;
    _Bool _isFromOffline;
    _Bool _isLoginCacnel;
    _Bool _priorityFlag;
    _Bool _isNeedAuth;
    float _xCoordinate;
    float _yCoordinate;
    int _mtopCachePolicy;
    long long _sessionExpiredOption;
    unsigned long long _wuaType;
    NSString *_openAppkey;
    NSString *_wuaPageName;
    NSString *_wuaCtrlName;
    NSString *_sid;
    NSString *_eCode;
    NSString *_bigPipeReuseIdentifier;
    NSString *_httpCacheKey;
    NSURL *_url;
    NSString *_customHost;
    NSArray *_customHostList;
    NSArray *_blackCacheKeyParam;
    NSString *_userID;
    NSString *_h5URL;
    unsigned long long _UnitStrategy;
    NSString *_pageName;
    NSString *_pageUrl;
    NSString *_accountInfo;
    MTopPrefetch *_prefetch;
    MtopExtRequest *_request;
    NSString *_objectId;
}

+ (id)requestWithMethod:(id)arg1;
@property(retain, nonatomic) NSString *objectId; // @synthesize objectId=_objectId;
@property(retain, nonatomic) MtopExtRequest *request; // @synthesize request=_request;
@property(retain, nonatomic) MTopPrefetch *prefetch; // @synthesize prefetch=_prefetch;
@property(copy, nonatomic) NSString *accountInfo; // @synthesize accountInfo=_accountInfo;
@property(copy, nonatomic) NSString *pageUrl; // @synthesize pageUrl=_pageUrl;
@property(copy, nonatomic) NSString *pageName; // @synthesize pageName=_pageName;
@property(nonatomic) _Bool isNeedAuth; // @synthesize isNeedAuth=_isNeedAuth;
@property(nonatomic) unsigned long long UnitStrategy; // @synthesize UnitStrategy=_UnitStrategy;
@property(nonatomic) _Bool priorityFlag; // @synthesize priorityFlag=_priorityFlag;
@property(retain, nonatomic) NSString *h5URL; // @synthesize h5URL=_h5URL;
@property(nonatomic) _Bool isLoginCacnel; // @synthesize isLoginCacnel=_isLoginCacnel;
@property(retain, nonatomic) NSString *userID; // @synthesize userID=_userID;
@property(nonatomic) _Bool isFromOffline; // @synthesize isFromOffline=_isFromOffline;
@property(retain, nonatomic) NSArray *blackCacheKeyParam; // @synthesize blackCacheKeyParam=_blackCacheKeyParam;
@property(retain, nonatomic) NSArray *customHostList; // @synthesize customHostList=_customHostList;
@property(retain, nonatomic) NSString *customHost; // @synthesize customHost=_customHost;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
@property(nonatomic) int mtopCachePolicy; // @synthesize mtopCachePolicy=_mtopCachePolicy;
@property(retain, nonatomic) NSString *httpCacheKey; // @synthesize httpCacheKey=_httpCacheKey;
@property(retain, nonatomic) NSString *bigPipeReuseIdentifier; // @synthesize bigPipeReuseIdentifier=_bigPipeReuseIdentifier;
@property(retain, nonatomic) NSString *eCode; // @synthesize eCode=_eCode;
@property(retain, nonatomic) NSString *sid; // @synthesize sid=_sid;
@property(nonatomic) float yCoordinate; // @synthesize yCoordinate=_yCoordinate;
@property(nonatomic) float xCoordinate; // @synthesize xCoordinate=_xCoordinate;
@property(retain, nonatomic) NSString *wuaCtrlName; // @synthesize wuaCtrlName=_wuaCtrlName;
@property(retain, nonatomic) NSString *wuaPageName; // @synthesize wuaPageName=_wuaPageName;
@property(retain, nonatomic) NSString *openAppkey; // @synthesize openAppkey=_openAppkey;
@property(nonatomic) unsigned long long wuaType; // @synthesize wuaType=_wuaType;
@property(nonatomic) _Bool isNeedWua; // @synthesize isNeedWua=_isNeedWua;
@property(nonatomic) _Bool needEcodeSign; // @synthesize needEcodeSign=_needEcodeSign;
@property(nonatomic) long long sessionExpiredOption; // @synthesize sessionExpiredOption=_sessionExpiredOption;
- (void).cxx_destruct;
- (void)failed_internal_callback:(id)arg1;
- (void)failed_internal:(id)arg1;
- (void)succeed_internal_callback:(id)arg1;
- (void)succeed_internal:(id)arg1;
- (void)cached_internal_callback:(id)arg1;
- (void)cached_internal:(id)arg1;
- (void)started_internal_callback:(id)arg1;
- (void)started_internal:(id)arg1;
- (void)succeed:(id)arg1;
- (void)failed:(id)arg1;
- (void)started:(id)arg1;
@property(readonly, nonatomic) UTDataSet *mtopUT;
@property(readonly, nonatomic) NSDictionary *mtopPreDataDict;
@property(readonly, nonatomic) NSMutableDictionary *dataDict;
- (void)cacheResponseString;
- (void)fillWithMtopResponse:(id)arg1;
- (void)setLocation:(double)arg1 latitude:(double)arg2;
- (void)useMainThreadCallback;
- (void)notUseMainThreadCallback;
- (void)disableResponseValidate;
- (void)enableResponseValidate;
- (void)setMtopRequestHeaderExt:(id)arg1;
- (void)setTtid:(id)arg1;
- (void)setNeedAuth:(id)arg1 andAuthParam:(id)arg2;
- (void)setup;
- (_Bool)isNeedEcode;
- (void)addData:(id)arg1 withFileName:(id)arg2 forKey:(id)arg3;
- (void)clearData;
- (void)clearDelegatesAndCancel;
- (id)getResponseStringFromCacheByCacheKey:(id)arg1 timeout:(double)arg2;
- (void)startAsynchronousByCacheKey:(id)arg1 cacheTimeout:(double)arg2;
- (void)startSynchronousByCacheKey:(id)arg1 cacheTimeout:(double)arg2;
- (void)startAsynchronous;
- (void)startSynchronous;
- (void)addCustomHeader:(id)arg1 value:(id)arg2;
- (void)addRequestHeader:(id)arg1 value:(id)arg2;
- (id)getOfflineCacheKey;
- (void)addPriorityData:(id)arg1 forKey:(id)arg2;
- (void)removeDataParam:(id)arg1;
- (void)addDataParam:(id)arg1 forKey:(id)arg2;
- (void)removeParam:(id)arg1;
- (void)addParam:(id)arg1 forKey:(id)arg2;
- (id)apiVersion;
- (id)apiMethod;
- (void)dealloc;
- (id)initWithMethod:(id)arg1;
@property(retain, nonatomic) TBSDKAsync4jInterceptor *interceptor;
- (void)cancelAsync4jRequest;
- (void)startAsync4jRequest;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

