//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class APMLock;

@interface TEXFramebuffer : NSObject
{
    unsigned int _framebuffer;
    struct __CVBuffer *_pixelbufferRef;
    struct __CVBuffer *_textureRef;
    _Bool _onlyTexture;
    _Bool _externalTexture;
    APMLock *_lock;
    unsigned int _texture;
    struct CGSize _size;
    struct CGRect _roi;
}

@property(nonatomic) struct CGRect roi; // @synthesize roi=_roi;
@property(nonatomic) struct CGSize size; // @synthesize size=_size;
@property(nonatomic) unsigned int texture; // @synthesize texture=_texture;
- (void).cxx_destruct;
- (void)use;
- (void)destroyFramebufferInContext:(id)arg1;
- (void)destroyFramebuffer;
- (void)generateFramebufferInContext:(id)arg1;
- (void)generateFramebuffer;
- (_Bool)tryLock;
- (_Bool)unlock;
- (_Bool)lock;
- (void)generateTexture;
- (void)dealloc;
- (id)initWithSize:(struct CGSize)arg1 texture:(unsigned int)arg2;
- (id)initWithSize:(struct CGSize)arg1 onlyTexture:(_Bool)arg2;
- (id)initWithSize:(struct CGSize)arg1;

@end

