//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface TFAccountPayToolModel : NSObject
{
    NSString *_actionType;
    NSString *_text;
    NSString *_link;
    NSString *_params;
}

+ (id)createTFAccountPayToolModel:(id)arg1;
@property(copy, nonatomic) NSString *params; // @synthesize params=_params;
@property(copy, nonatomic) NSString *link; // @synthesize link=_link;
@property(copy, nonatomic) NSString *text; // @synthesize text=_text;
@property(copy, nonatomic) NSString *actionType; // @synthesize actionType=_actionType;
- (void).cxx_destruct;

@end

