//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableArray;

@interface TFRExpoHandler : NSObject
{
    CDUnknownBlockType _addExpoStruct;
    NSMutableArray *_iExpoStructList;
}

@property(retain, nonatomic) NSMutableArray *iExpoStructList; // @synthesize iExpoStructList=_iExpoStructList;
@property(copy, nonatomic) CDUnknownBlockType addExpoStruct; // @synthesize addExpoStruct=_addExpoStruct;
- (void).cxx_destruct;
- (void)checkExpoWithFrame:(struct CGRect)arg1;
- (void)cleanExpo;

@end

