//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIScrollView.h>

#import "UIGestureRecognizerDelegate-Protocol.h"
#import "UIScrollViewDelegate-Protocol.h"

@class NSString, TFRBaseCell;

@interface TFRTabPagingView : UIScrollView <UIScrollViewDelegate, UIGestureRecognizerDelegate>
{
    _Bool _isPageScrolling;
    long long _selectedIndex;
    long long _pageCount;
    CDUnknownBlockType _selectedIndexDidChangedCallback;
    TFRBaseCell *_currentCell;
}

@property(retain, nonatomic) TFRBaseCell *currentCell; // @synthesize currentCell=_currentCell;
@property(copy, nonatomic) CDUnknownBlockType selectedIndexDidChangedCallback; // @synthesize selectedIndexDidChangedCallback=_selectedIndexDidChangedCallback;
@property(nonatomic) long long pageCount; // @synthesize pageCount=_pageCount;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) _Bool isPageScrolling; // @synthesize isPageScrolling=_isPageScrolling;
- (void).cxx_destruct;
- (void)showCurrentCell:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRequireFailureOfGestureRecognizer:(id)arg2;
- (void)layoutSubviews;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

