//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSArray, NSString;

@interface TianYanConfig : NSObject
{
    _Bool _IsCPUCheck;
    _Bool _IsMemLeakCheckVCs;
    _Bool _IsPerformanceCheck;
    int _StorageCheckInterval;
    NSString *_ClientVersion;
    double _MonitorPeriod;
    NSArray *_MemLeakCheckFilterVCs;
    NSArray *_StorageCheckMultiMediaPaths;
    NSString *_productionVersion;
    NSString *_currentUserId;
    unsigned long long _lagMonitorTenPercent;
    unsigned long long _fpsMonitorTenPercent;
}

@property(nonatomic) unsigned long long fpsMonitorTenPercent; // @synthesize fpsMonitorTenPercent=_fpsMonitorTenPercent;
@property(nonatomic) unsigned long long lagMonitorTenPercent; // @synthesize lagMonitorTenPercent=_lagMonitorTenPercent;
@property(retain, nonatomic) NSString *currentUserId; // @synthesize currentUserId=_currentUserId;
@property(retain, nonatomic) NSString *productionVersion; // @synthesize productionVersion=_productionVersion;
@property(nonatomic) _Bool IsPerformanceCheck; // @synthesize IsPerformanceCheck=_IsPerformanceCheck;
@property(retain, nonatomic) NSArray *StorageCheckMultiMediaPaths; // @synthesize StorageCheckMultiMediaPaths=_StorageCheckMultiMediaPaths;
@property(nonatomic) int StorageCheckInterval; // @synthesize StorageCheckInterval=_StorageCheckInterval;
@property(retain, nonatomic) NSArray *MemLeakCheckFilterVCs; // @synthesize MemLeakCheckFilterVCs=_MemLeakCheckFilterVCs;
@property(nonatomic) _Bool IsMemLeakCheckVCs; // @synthesize IsMemLeakCheckVCs=_IsMemLeakCheckVCs;
@property(nonatomic) _Bool IsCPUCheck; // @synthesize IsCPUCheck=_IsCPUCheck;
@property(nonatomic) double MonitorPeriod; // @synthesize MonitorPeriod=_MonitorPeriod;
@property(retain, nonatomic) NSString *ClientVersion; // @synthesize ClientVersion=_ClientVersion;
- (void).cxx_destruct;
- (id)init;

@end

