//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSDictionary, NSString, PSDSession;

@interface TinyappJsPermissionManager : NSObject
{
    NSDictionary *_config;
    NSString *_appId;
    PSDSession *_session;
}

@property(nonatomic) __weak PSDSession *session; // @synthesize session=_session;
@property(copy, nonatomic) NSString *appId; // @synthesize appId=_appId;
@property(retain, nonatomic) NSDictionary *config; // @synthesize config=_config;
- (void).cxx_destruct;
- (id)trimWhiteSpaceForDomains:(id)arg1;
- (id)permissonUrlSchemeWhiteList;
- (_Bool)isDebugMode;
- (_Bool)ignoreWebViewRequestDomainCheck;
- (_Bool)ignoreJsApiRequestDomainCheck;
- (id)componentPermissionConfig;
- (_Bool)hasPermissionWithjsapiName:(id)arg1 data:(id)arg2 url:(id)arg3;
- (_Bool)haspermissionWithWebviewWithJsapi:(id)arg1 appId:(id)arg2;
- (_Bool)hasPermissionWithEventName:(id)arg1 data:(id)arg2 url:(id)arg3;
- (_Bool)shouldForceSSL;
- (_Bool)shouldGoWithSPDY;
- (_Bool)hasPermissionWithResponse:(id)arg1;
- (_Bool)hasPermissionWithUrl:(id)arg1 appId:(id)arg2;
- (_Bool)hasPermissionWithUrl:(id)arg1;
- (_Bool)hasPermissionWithWebviewUrl:(id)arg1;
- (_Bool)isDomainValid:(id)arg1 domain:(id)arg2;
- (_Bool)shouldGOSPDYWithHttps:(id)arg1;
- (_Bool)shouldGOSPDYWithRequestExtention:(id)arg1;
- (_Bool)shouldDoPermissonJudge;
- (id)initWithConfig:(id)arg1 appId:(id)arg2 session:(id)arg3;
- (id)initWithConfig:(id)arg1 appId:(id)arg2;
- (id)initWithConfig:(id)arg1;

@end

