//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSMutableDictionary;

@interface TinyLocalStorageManager : NSObject
{
    NSMutableDictionary *_storageDictionary;
}

+ (id)getCustomStorageWithAppId:(id)arg1;
+ (id)defaultManager;
@property(retain, nonatomic) NSMutableDictionary *storageDictionary; // @synthesize storageDictionary=_storageDictionary;
- (void).cxx_destruct;

@end

