//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <UIKit/UIDevice.h>

@class NSString;

@interface UIDevice (HLP)
@property(readonly, nonatomic) NSString *hlp_mac;
@property(readonly, nonatomic) NSString *hlp_clientIp;
@property(readonly, nonatomic) NSString *hlp_network;
@property(readonly, nonatomic) NSString *hlp_brand;
@property(readonly, nonatomic) NSString *hlp_osVer;
@property(readonly, nonatomic) NSString *hlp_appVer;
@end

