//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VIViewController.h"

@class NSDictionary;

@interface VIModuleGuideViewController : VIViewController
{
    CDUnknownBlockType _handler;
    NSDictionary *_params;
}

@property(retain, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(copy, nonatomic) CDUnknownBlockType handler; // @synthesize handler=_handler;
- (void).cxx_destruct;
- (void)back;
- (void)submitHandler;
- (void)initSubviews;
- (void)viewDidLoad;
- (id)initWithParams:(id)arg1;

@end

