//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VIViewController.h"

#import "VIPasswdVerifyDelegate-Protocol.h"
#import "VIPasswdViewDelegate-Protocol.h"

@class NSString, VIPasswdModule, VIPasswdPopupView, VIPasswdVerifyService, VIPasswdViewData, VIPasswdViewStyle;

@interface VIPasswdViewController : VIViewController <VIPasswdViewDelegate, VIPasswdVerifyDelegate>
{
    VIPasswdPopupView *_popupView;
    VIPasswdViewStyle *_style;
    VIPasswdViewData *_data;
    VIPasswdModule *_module;
    _Bool _hideTip;
    VIPasswdVerifyService *_verifyService;
}

- (void).cxx_destruct;
- (void)logForCode:(id)arg1 btnIndex:(long long)arg2;
- (id)data;
- (id)style;
- (id)popupView;
- (void)monitorSubmit;
- (void)passwdViewDidSubmit:(id)arg1 withData:(id)arg2;
- (void)passwdViewOnProtocolClick:(id)arg1 WithProtocolUrl:(id)arg2;
- (void)passwdViewOnTryOthersClicked:(id)arg1;
- (void)passwdViewOnForgetPasswdClicked:(id)arg1;
- (void)passwdViewDidCancel:(id)arg1;
- (void)back;
- (void)passwdViewDidSubmit:(id)arg1 withInputView:(id)arg2;
- (void)handleOnResponse:(id)arg1 status:(unsigned long long)arg2 verifyStatus:(unsigned long long)arg3 userAction:(unsigned long long)arg4;
- (void)endVerify;
- (void)startVerify;
- (void)viewDidLoad;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

