//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@interface VIVoiceUtils : NSObject
{
    _Bool _isNoisy;
    _Bool _lastRecordTimeout;
    double _power;
    CDUnknownBlockType _stopRecordCompletion;
    CDUnknownBlockType _cancelRecordCompletion;
}

+ (id)sharedInstance;
@property(copy, nonatomic) CDUnknownBlockType cancelRecordCompletion; // @synthesize cancelRecordCompletion=_cancelRecordCompletion;
@property(copy, nonatomic) CDUnknownBlockType stopRecordCompletion; // @synthesize stopRecordCompletion=_stopRecordCompletion;
@property _Bool lastRecordTimeout; // @synthesize lastRecordTimeout=_lastRecordTimeout;
@property _Bool isNoisy; // @synthesize isNoisy=_isNoisy;
@property(nonatomic) double power; // @synthesize power=_power;
- (void).cxx_destruct;
- (void)logForStopUploadWithDuration:(id)arg1 result:(id)arg2;
- (void)logForStartUpload;
- (void)logForStopRecordWithResult:(id)arg1;
- (void)logForStartRecord;
- (void)logForStopNoiseWithValue:(id)arg1 result:(id)arg2;
- (void)logForStartCheckNoise;
- (void)logForUnauthorized;
- (void)cancelRecordWithParams:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)stopRecordWithParams:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)startRecordWithParams:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)checkNoiseWithParams:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)startVoiceWithParams:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;

@end

