//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "VIModule.h"

@class NSString;

@interface VIZOLOZFaceModule : VIModule
{
    unsigned long long _alifaceStartTime;
    NSString *_userId;
    NSString *_desensName;
    NSString *_zimId;
    NSString *_popupErrMsg;
}

+ (id)preData;
+ (id)keyMapper;
@property(retain, nonatomic) NSString *popupErrMsg; // @synthesize popupErrMsg=_popupErrMsg;
@property(copy, nonatomic) NSString *zimId; // @synthesize zimId=_zimId;
- (void).cxx_destruct;
- (void)monitorBIOAuthResponse:(id)arg1;
- (void)monitorClosePage;
- (void)closePageWithResponse:(id)arg1;
- (void)selectOtherVerifyMethod;
- (void)handleRPCCallbackWithResponse:(id)arg1;
- (void)callRPC:(id)arg1 withResponse:(id)arg2;
- (void)handleResponse:(id)arg1;
- (id)faceExtInfo;
- (void)start;
- (void)onLogout;
- (void)closePageWithCallback:(CDUnknownBlockType)arg1;
- (void)invalidate;

@end

