//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString, VZMistTemplateAction, VZTExpressionContext;
@protocol VZMistItem;

@interface VZMistTemplateEvent : NSObject
{
    id <VZMistItem> _item;
    NSString *_eventId;
    VZMistTemplateAction *_action;
    VZMistTemplateAction *_onceAction;
    VZTExpressionContext *_expressionContext;
}

+ (id)eventWithName:(id)arg1 dict:(id)arg2 expressionContext:(id)arg3 item:(id)arg4;
- (void).cxx_destruct;
- (id)description;
- (void)invokeWithSender:(id)arg1 eventParams:(id)arg2;
- (void)invokeWithSender:(id)arg1;
- (id)initWithItem:(id)arg1 eventId:(id)arg2 action:(id)arg3 onceAction:(id)arg4 expressionContext:(id)arg5;

@end

