//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

@class NSDictionary;

@protocol WADetectorClient
@property(nonatomic) __weak id webview;
- (void)sendInitResultToPage:(int)arg1;
- (void)sendResultToPage:(NSDictionary *)arg1 forceEvent:(_Bool)arg2;
- (void)sendResultToPage:(NSDictionary *)arg1;
@end

