//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSError, UIButton, WBSDKWebView, WKNavigationAction;

@protocol WBSDKWebViewDelegate <NSObject>

@optional
- (void)wbsdk_webView:(WBSDKWebView *)arg1 didPressErrorViewReloadButton:(UIButton *)arg2;
- (void)wbsdk_webView:(WBSDKWebView *)arg1 didFailLoadWithError:(NSError *)arg2;
- (void)wbsdk_webViewDidFinishLoad:(WBSDKWebView *)arg1;
- (void)wbsdk_webViewDidStartLoad:(WBSDKWebView *)arg1;
- (void)wbsdk_webView:(WBSDKWebView *)arg1 decidePolicyForNavigationAction:(WKNavigationAction *)arg2 decisionHandler:(void (^)(long long))arg3;
@end

