//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WHCardModel.h"

@class ACAppCategory, NSArray, NSMutableArray, WHAssetsHeaderModel;

@interface WHAssetsCardModel : WHCardModel
{
    _Bool _isSmallSubtitle;
    ACAppCategory *_appCategory;
    WHAssetsHeaderModel *_headerModel;
    NSArray *_appModelList;
    NSMutableArray *_itemIds;
}

+ (id)defaultModelCardWithCardId:(id)arg1;
@property(nonatomic) _Bool isSmallSubtitle; // @synthesize isSmallSubtitle=_isSmallSubtitle;
@property(retain, nonatomic) NSMutableArray *itemIds; // @synthesize itemIds=_itemIds;
@property(retain, nonatomic) NSArray *appModelList; // @synthesize appModelList=_appModelList;
@property(retain, nonatomic) WHAssetsHeaderModel *headerModel; // @synthesize headerModel=_headerModel;
@property(retain, nonatomic) ACAppCategory *appCategory; // @synthesize appCategory=_appCategory;
- (void).cxx_destruct;
- (_Bool)isEqual:(id)arg1;
- (_Bool)parseToModelWithDictionary:(id)arg1;
- (id)marketingIds;

@end

