//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "AUKView.h"

@class AULabel, MFAttributeLabel, UIImageView, WHAssetsHeaderHideControl, WHAssetsHeaderModel, WHExposureControl;

@interface WHAssetHeaderView : AUKView
{
    AULabel *_titileLabel;
    WHAssetsHeaderHideControl *_eyeHideControl;
    MFAttributeLabel *_titleDescLabel;
    WHExposureControl *_titleDescBgControl;
    WHExposureControl *_leftControl;
    AULabel *_assetLabel;
    AULabel *_assetNumLabel;
    UIImageView *_arrowLeftImgv;
    WHExposureControl *_rightControl;
    AULabel *_balanceLabel;
    AULabel *_balanceNumLabel;
    UIImageView *_arrowRightImgv;
    WHAssetsHeaderModel *_model;
}

+ (double)estimateHeight;
@property(retain, nonatomic) WHAssetsHeaderModel *model; // @synthesize model=_model;
@property(retain, nonatomic) UIImageView *arrowRightImgv; // @synthesize arrowRightImgv=_arrowRightImgv;
@property(retain, nonatomic) AULabel *balanceNumLabel; // @synthesize balanceNumLabel=_balanceNumLabel;
@property(retain, nonatomic) AULabel *balanceLabel; // @synthesize balanceLabel=_balanceLabel;
@property(retain, nonatomic) WHExposureControl *rightControl; // @synthesize rightControl=_rightControl;
@property(retain, nonatomic) UIImageView *arrowLeftImgv; // @synthesize arrowLeftImgv=_arrowLeftImgv;
@property(retain, nonatomic) AULabel *assetNumLabel; // @synthesize assetNumLabel=_assetNumLabel;
@property(retain, nonatomic) AULabel *assetLabel; // @synthesize assetLabel=_assetLabel;
@property(retain, nonatomic) WHExposureControl *leftControl; // @synthesize leftControl=_leftControl;
@property(retain, nonatomic) WHExposureControl *titleDescBgControl; // @synthesize titleDescBgControl=_titleDescBgControl;
@property(retain, nonatomic) MFAttributeLabel *titleDescLabel; // @synthesize titleDescLabel=_titleDescLabel;
@property(retain, nonatomic) WHAssetsHeaderHideControl *eyeHideControl; // @synthesize eyeHideControl=_eyeHideControl;
@property(retain, nonatomic) AULabel *titileLabel; // @synthesize titileLabel=_titileLabel;
- (void).cxx_destruct;
- (void)didClickHideControl:(id)arg1;
- (void)didClick:(int)arg1;
- (void)didClickBalance:(id)arg1;
- (void)didClickTotalAssets:(id)arg1;
- (void)didClickTitleDescLabel:(id)arg1;
- (void)layoutSubviews;
- (void)updateByModel:(id)arg1;
- (id)initWithFrame:(struct CGRect)arg1;

@end

