//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class AUV2PopTipView, UITableView;

@interface WHCardGuidance : NSObject
{
    UITableView *_tableView;
    AUV2PopTipView *_popTipViewOfBankCard;
}

+ (id)cardGuidance;
@property(retain, nonatomic) AUV2PopTipView *popTipViewOfBankCard; // @synthesize popTipViewOfBankCard=_popTipViewOfBankCard;
- (void).cxx_destruct;
- (void)refresh;
- (void)dismissAllTips;
- (void)showBankCardTipFromView:(id)arg1 fromPoint:(struct CGPoint)arg2;
- (void)setTableView:(id)arg1;

@end

