//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "WHCardModel.h"

@class NSArray, NSMutableArray, WHAppModel, WHAssetsItem;

@interface WHMerchantCardModel : WHCardModel
{
    NSMutableArray *_itemIds;
    WHAppModel *_mainInfo;
    WHAssetsItem *_incomeAsset;
    WHAssetsItem *_allAsset;
    NSArray *_serviceList;
}

+ (id)instanceForCard:(id)arg1;
@property(retain, nonatomic) NSArray *serviceList; // @synthesize serviceList=_serviceList;
@property(retain, nonatomic) WHAssetsItem *allAsset; // @synthesize allAsset=_allAsset;
@property(retain, nonatomic) WHAssetsItem *incomeAsset; // @synthesize incomeAsset=_incomeAsset;
@property(retain, nonatomic) WHAppModel *mainInfo; // @synthesize mainInfo=_mainInfo;
- (void).cxx_destruct;
- (id)marketingIds;
- (_Bool)parseToModelWithDictionary:(id)arg1;

@end

