//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@protocol WHNotifyAppLifeCycle;

@interface WHNotificationDelegate : NSObject
{
    id <WHNotifyAppLifeCycle> _appLife;
}

- (void).cxx_destruct;
- (void)fontLevelDidChanged:(id)arg1;
- (void)regionDidChanged:(id)arg1;
- (void)languageDidChanged:(id)arg1;
- (void)appCenterUpdate:(id)arg1;
- (void)pipeLineStart:(id)arg1;
- (void)loginDidFinished:(id)arg1;
- (void)applicationDidEnterBackgroundNotification:(id)arg1;
- (void)applicationDidBecomeActiveNotification:(id)arg1;
- (void)enterForeground:(id)arg1;
- (void)bootUpObserver;
- (void)setAppLifeCycle:(id)arg1;
- (void)dealloc;

@end

