//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "XMediaBaseFunctorDelegate-Protocol.h"

@class NSString, XMediaCVFunctor, XMediaClassifyDetectFunctor;
@protocol XMBDamageDetectDelegate;

@interface XMBCarDamageDetector : NSObject <XMediaBaseFunctorDelegate>
{
    char *_lastFrameBuffer;
    _Bool _shouldDegrade;
    int _carVerity;
    id <XMBDamageDetectDelegate> _delegate;
    NSString *_businessId;
    NSString *_modelFileId;
    unsigned long long _curMode;
    XMediaClassifyDetectFunctor *_multiTaskEngine;
    XMediaClassifyDetectFunctor *_partsDetectEngine;
    XMediaClassifyDetectFunctor *_damageDetectEngine;
    XMediaCVFunctor *_cvEngine;
    double _lastFrameTime;
    double _procTimeInterval;
    NSString *_modelId;
    double _initTime;
    double _procTime;
    NSString *_totalCostTime;
    long long _stateCode;
}

@property(nonatomic) long long stateCode; // @synthesize stateCode=_stateCode;
@property(retain, nonatomic) NSString *totalCostTime; // @synthesize totalCostTime=_totalCostTime;
@property(nonatomic) double procTime; // @synthesize procTime=_procTime;
@property(nonatomic) double initTime; // @synthesize initTime=_initTime;
@property(retain, nonatomic) NSString *modelId; // @synthesize modelId=_modelId;
@property(nonatomic) double procTimeInterval; // @synthesize procTimeInterval=_procTimeInterval;
@property(nonatomic) double lastFrameTime; // @synthesize lastFrameTime=_lastFrameTime;
@property(nonatomic) int carVerity; // @synthesize carVerity=_carVerity;
@property(nonatomic) _Bool shouldDegrade; // @synthesize shouldDegrade=_shouldDegrade;
@property(retain, nonatomic) XMediaCVFunctor *cvEngine; // @synthesize cvEngine=_cvEngine;
@property(retain, nonatomic) XMediaClassifyDetectFunctor *damageDetectEngine; // @synthesize damageDetectEngine=_damageDetectEngine;
@property(retain, nonatomic) XMediaClassifyDetectFunctor *partsDetectEngine; // @synthesize partsDetectEngine=_partsDetectEngine;
@property(retain, nonatomic) XMediaClassifyDetectFunctor *multiTaskEngine; // @synthesize multiTaskEngine=_multiTaskEngine;
@property(nonatomic) unsigned long long curMode; // @synthesize curMode=_curMode;
@property(retain, nonatomic) NSString *modelFileId; // @synthesize modelFileId=_modelFileId;
@property(retain, nonatomic) NSString *businessId; // @synthesize businessId=_businessId;
@property(nonatomic) __weak id <XMBDamageDetectDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)remoteErrorLog;
- (void)remoteLog;
- (id)roiArrayFromImageToView:(id)arg1;
- (id)processWithFrameData:(char *)arg1 width:(int)arg2 height:(int)arg3;
- (id)carDamageProcessOnImage:(id)arg1;
- (id)carDamageProcessOnFrame:(struct __CVBuffer *)arg1;
- (id)initWithBusinessId:(id)arg1 modelFileId:(id)arg2 modelPathArray:(id)arg3 options:(id)arg4;
- (void)dealloc;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

