//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "XMediaCoreBaseProcessor.h"

@class NSObject, XMediaZFaceFunctor;
@protocol OS_dispatch_queue;

@interface XMBZFaceDetectProcessor : XMediaCoreBaseProcessor
{
    NSObject<OS_dispatch_queue> *_algorithmQueue;
    XMediaZFaceFunctor *_zFaceFunctor;
}

@property(retain, nonatomic) XMediaZFaceFunctor *zFaceFunctor; // @synthesize zFaceFunctor=_zFaceFunctor;
- (void).cxx_destruct;
- (id)synProcessWithSource:(id)arg1 options:(id)arg2;
- (id)createZFaceFunctor;
- (void)updateStateWithFunctorCreate;
- (id)initWithConfig:(id)arg1 resultBlock:(CDUnknownBlockType)arg2;
- (void)dealloc;

@end

