//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class YTCoreSoftwarePlayerUnitQueue;

@interface YTCoreSoftwarePlayerUnitPool : NSObject
{
    YTCoreSoftwarePlayerUnitQueue *_unitQueue;
}

+ (id)unitPool;
@property(retain, nonatomic) YTCoreSoftwarePlayerUnitQueue *unitQueue; // @synthesize unitQueue=_unitQueue;
- (void).cxx_destruct;
- (void)controlUnitForDestory:(id)arg1;
- (void)controlUnitForScreenShotFramesEnd:(id)arg1 out_fmt:(int)arg2 endType:(int)arg3 startTime:(double)arg4 endTime:(double)arg5 cropLeft:(int)arg6 cropTop:(int)arg7 cropWidth:(int)arg8 cropHeight:(int)arg9 logo_path:(const char *)arg10 logo_width:(int)arg11 logo_height:(int)arg12 logo_left:(int)arg13 logo_top:(int)arg14;
- (void)controlUnitForScreenShotOneFrame:(id)arg1 out_path:(const char *)arg2 out_width:(int)arg3 out_height:(int)arg4 out_fmt:(int)arg5 logo_path:(const char *)arg6 logo_width:(int)arg7 logo_height:(int)arg8 logo_left:(int)arg9 logo_top:(int)arg10;
- (void)controlUnitForScreenShotMultiFramesBegin:(id)arg1 out_path:(const char *)arg2 out_width:(int)arg3 out_height:(int)arg4 out_fmt:(int)arg5 startTime:(double)arg6 endTime:(double)arg7;
- (void)fetchUnit:(id)arg1 getDuration:(long long *)arg2;
- (void)fetchUnit:(id)arg1 getCurrentPosition:(long long *)arg2;
- (id)fetchUnitForHlsQualityList:(id)arg1;
- (double)fetchUnitForAvgKeyFrameSize:(id)arg1;
- (double)fetchUnitForVideoFrameRate:(id)arg1;
- (double)fetchUnitForAvgVideoBitrate:(id)arg1;
- (double)fetchUnitForVideoHeight:(id)arg1;
- (double)fetchUnitForVideoWidth:(id)arg1;
- (_Bool)fetchUnitForIsPlaying:(id)arg1;
- (void)controlUnit:(id)arg1 setHlsQuality:(id)arg2;
- (void)controlUnit:(id)arg1 setProperty:(int)arg2 value:(id)arg3;
- (void)controlUnit:(id)arg1 setTimeout:(int)arg2 value:(int)arg3;
- (int)controlUnit:(id)arg1 setVideoRendCutMode:(int)arg2 xOffset:(float)arg3 yOffset:(float)arg4;
- (void)controlUnit:(id)arg1 setLooping:(_Bool)arg2;
- (void)controlUnit:(id)arg1 setPlaybackSpeed:(double)arg2;
- (void)controlUnit:(id)arg1 setAudioVolume:(float)arg2;
- (void)controlUnit:(id)arg1 setAudioEnhanceEnable:(_Bool)arg2;
- (void)controlUnit:(id)arg1 setVideoEnhanceEnable:(_Bool)arg2 linePos:(float)arg3 weight:(float)arg4;
- (void)controlUnit:(id)arg1 setVideoRenderMode:(int)arg2 VRType:(int)arg3;
- (void)controlUnit:(id)arg1 setInterfaceOrientation:(long long)arg2;
- (void)controlUnit:(id)arg1 setDisplayView:(id)arg2;
- (void)controlUnitForCancelSelectDataSource:(id)arg1;
- (void)controlUnit:(id)arg1 selectDataSource:(id)arg2;
- (void)controlUnit:(id)arg1 playBackupAd:(id)arg2 duration:(long long)arg3;
- (void)controlUnit:(id)arg1 foregroundSeekToPosition:(long long)arg2;
- (void)controlUnit:(id)arg1 seekToPosition:(long long)arg2;
- (void)controlUnitForPauseVideoRender:(id)arg1;
- (void)controlUnitForResumeVideoRender:(id)arg1;
- (void)controlUnitForStop:(id)arg1;
- (void)controlUnitForPause:(id)arg1;
- (void)controlUnitForPlay:(id)arg1;
- (void)controlUnitForPrepareAsync:(id)arg1;
- (long long)controlUnit:(id)arg1 preAddDataSource:(id)arg2;
- (id)unitWithUnitContext:(id)arg1;
- (void)resetUnitWithUnitContext:(id)arg1 delegate:(id)arg2 contentURL:(id)arg3 userInfo:(id)arg4;
- (id)preCreateUnitError:(id *)arg1;
- (id)createUnitWithDelegate:(id)arg1 contentURL:(id)arg2 userInfo:(id)arg3 error:(id *)arg4;
- (id)init;

@end

