//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import "NSObject-Protocol.h"

@class NSDictionary, NSString, YTEnginePlayerInternal;

@protocol YTEnginePlayerDelegateInternal <NSObject>
- (void)enginePlayerVideoLoopEnd:(YTEnginePlayerInternal *)arg1;
- (void)enginePlayer:(YTEnginePlayerInternal *)arg1 updateLiveStreamSeiInfo:(NSString *)arg2;
- (void)enginePlayer:(YTEnginePlayerInternal *)arg1 renderSnapshotImageNameUpload:(NSString *)arg2;
- (void)enginePlayerRenderSnapshotImageEnd:(YTEnginePlayerInternal *)arg1;
- (void)enginePlayer:(YTEnginePlayerInternal *)arg1 renderSnapshotVideoError:(int)arg2;
- (void)enginePlayer:(YTEnginePlayerInternal *)arg1 renderSnapshotVideoProgress:(int)arg2;
- (void)enginePlayerRenderSnapshotVideoEnd:(YTEnginePlayerInternal *)arg1;
- (void)enginePlayer:(YTEnginePlayerInternal *)arg1 currentTime:(double)arg2 loadedTime:(double)arg3;
- (void)enginePlayer:(YTEnginePlayerInternal *)arg1 videoFrameSwitchTo:(struct CGRect)arg2 from:(struct CGRect)arg3;
- (void)enginePlayer:(YTEnginePlayerInternal *)arg1 adPlayErrorWithType:(long long)arg2 errorInfo:(NSDictionary *)arg3;
- (void)enginePlayer:(YTEnginePlayerInternal *)arg1 endPlayWithType:(long long)arg2 atIndex:(long long)arg3 userInfo:(NSDictionary *)arg4;
- (void)enginePlayer:(YTEnginePlayerInternal *)arg1 startPlayWithType:(long long)arg2 atIndex:(long long)arg3 userInfo:(NSDictionary *)arg4;
- (void)enginePlayer:(YTEnginePlayerInternal *)arg1 playbackStateSwitchTo:(NSString *)arg2 from:(NSString *)arg3 userInfo:(NSDictionary *)arg4;
- (void)enginePlayer:(YTEnginePlayerInternal *)arg1 playerStateSwitchTo:(NSString *)arg2 from:(NSString *)arg3 userInfo:(NSDictionary *)arg4;
@end

