//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

#import "YTEngineModuleController-Protocol.h"
#import "YTEngineModuleViewsManagerDelegate-Protocol.h"
#import "YTEnginePlayerDelegateInternal-Protocol.h"

@class NSArray, NSString, YTEngineConfiguration, YTEngineControllerView, YTEngineModuleViewsManager, YTEnginePlayerInternal, YTEngineScreenMode;
@protocol YTEnginePlayerDelegate, YTEnginePlayerFeature;

@interface YTEngineController : NSObject <YTEnginePlayerDelegateInternal, YTEngineModuleViewsManagerDelegate, YTEngineModuleController>
{
    YTEnginePlayerInternal *mPlayer;
    YTEngineModuleViewsManager *mModuleViewsManager;
    _Bool _nextScrrenModeNeedAnimated;
    _Bool _modeIsChanging;
    YTEngineConfiguration *_configuration;
    id <YTEnginePlayerDelegate> _playerDelegate;
    id _parentPlayer;
    YTEngineControllerView *_view;
    long long _panelState;
    NSArray *_modulesArray;
    YTEngineScreenMode *_currentScreenMode;
    YTEngineScreenMode *_nextScreenMode;
}

@property _Bool modeIsChanging; // @synthesize modeIsChanging=_modeIsChanging;
@property(nonatomic) _Bool nextScrrenModeNeedAnimated; // @synthesize nextScrrenModeNeedAnimated=_nextScrrenModeNeedAnimated;
@property(copy, nonatomic) YTEngineScreenMode *nextScreenMode; // @synthesize nextScreenMode=_nextScreenMode;
@property(copy, nonatomic) YTEngineScreenMode *currentScreenMode; // @synthesize currentScreenMode=_currentScreenMode;
@property(retain, nonatomic) NSArray *modulesArray; // @synthesize modulesArray=_modulesArray;
@property(nonatomic) long long panelState; // @synthesize panelState=_panelState;
@property(retain, nonatomic) YTEngineControllerView *view; // @synthesize view=_view;
@property(nonatomic) __weak id parentPlayer; // @synthesize parentPlayer=_parentPlayer;
@property(nonatomic) __weak id <YTEnginePlayerDelegate> playerDelegate; // @synthesize playerDelegate=_playerDelegate;
@property(retain, nonatomic) YTEngineConfiguration *configuration; // @synthesize configuration=_configuration;
@property(readonly, nonatomic) id <YTEnginePlayerFeature> player; // @synthesize player=mPlayer;
- (void).cxx_destruct;
- (void)setQuiet:(_Bool)arg1 fromObject:(id)arg2;
- (_Bool)isQuiet;
- (void)resume:(id)arg1;
- (void)interrupt:(id)arg1;
- (_Bool)seekToTime:(double)arg1 fromObject:(id)arg2;
- (_Bool)stop:(id)arg1;
- (_Bool)pause:(id)arg1;
- (_Bool)play:(id)arg1;
- (_Bool)switchScreenModeTo:(id)arg1 animated:(_Bool)arg2 fromObject:(id)arg3;
- (_Bool)isFullScreen;
- (void)sendAction:(SEL)arg1 object1:(id)arg2 object2:(id)arg3 object3:(id)arg4 object4:(id)arg5 object5:(id)arg6;
- (void)deinit;
- (id)moduleWithClassName:(id)arg1;
- (void)deRegisterModule:(id)arg1;
- (void)registerModule:(id)arg1;
- (void)registerModuleWithClassNames:(id)arg1;
- (void)uninstallModules;
- (void)setupConfiguration;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)uninstallEventsObservers;
- (void)installEventsObservers;
- (id)initWithConfiguration:(id)arg1;
- (void)dealloc;
- (long long)sourceType;
- (void)makeScreenToMode:(id)arg1;
- (_Bool)switchScreenModeTo:(id)arg1 animated:(_Bool)arg2;
- (void)setInitialScreenMode:(id)arg1;
- (void)enginePlayerVideoLoopEnd:(id)arg1;
- (void)enginePlayer:(id)arg1 updateLiveStreamSeiInfo:(id)arg2;
- (void)enginePlayer:(id)arg1 renderSnapshotImageNameUpload:(id)arg2;
- (void)enginePlayerRenderSnapshotImageEnd:(id)arg1;
- (void)enginePlayer:(id)arg1 renderSnapshotVideoError:(int)arg2;
- (void)enginePlayer:(id)arg1 renderSnapshotVideoProgress:(int)arg2;
- (void)enginePlayerRenderSnapshotVideoEnd:(id)arg1;
- (void)enginePlayer:(id)arg1 videoFrameSwitchTo:(struct CGRect)arg2 from:(struct CGRect)arg3;
- (void)enginePlayer:(id)arg1 currentTime:(double)arg2 loadedTime:(double)arg3;
- (void)enginePlayer:(id)arg1 adPlayErrorWithType:(long long)arg2 errorInfo:(id)arg3;
- (void)enginePlayer:(id)arg1 endPlayWithType:(long long)arg2 atIndex:(long long)arg3 userInfo:(id)arg4;
- (void)enginePlayer:(id)arg1 startPlayWithType:(long long)arg2 atIndex:(long long)arg3 userInfo:(id)arg4;
- (void)enginePlayer:(id)arg1 playbackStateSwitchTo:(id)arg2 from:(id)arg3 userInfo:(id)arg4;
- (void)enginePlayer:(id)arg1 playerStateSwitchTo:(id)arg2 from:(id)arg3 userInfo:(id)arg4;
- (void)moduleViewsManager:(id)arg1 removeGoalView:(id)arg2;
- (void)moduleViewsManager:(id)arg1 addGoalView:(id)arg2;
- (void)moduleViewsManager:(id)arg1 sendAction:(SEL)arg2 object1:(id)arg3 object2:(id)arg4 object3:(id)arg5 object4:(id)arg6 object5:(id)arg7;
- (struct CGRect)playerViewRect;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

