//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface zfcertifycenterOcrPapersBehavTask : NSObject
{
    int _dur;
    int _quality;
    NSString *_name;
    NSString *_idx;
    NSString *_extInfo;
}

@property(retain, nonatomic) NSString *extInfo; // @synthesize extInfo=_extInfo;
@property(nonatomic) int quality; // @synthesize quality=_quality;
@property(nonatomic) int dur; // @synthesize dur=_dur;
@property(retain, nonatomic) NSString *idx; // @synthesize idx=_idx;
@property(retain, nonatomic) NSString *name; // @synthesize name=_name;
- (void).cxx_destruct;

@end

