//
//     Generated by class-dump 3.5 (64 bit) (Debug version compiled Sep 17 2017 16:24:48).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2015 by Steve Nygard.
//

#import <objc/NSObject.h>

@class NSString;

@interface ZolozMonitorCommonData : NSObject
{
    NSString *_token;
    long long _index;
    NSString *_serviceLevel;
}

+ (id)getInstance;
@property(retain, nonatomic) NSString *serviceLevel; // @synthesize serviceLevel=_serviceLevel;
- (void).cxx_destruct;
- (long long)getIndex;
- (id)getCommonMonitorData;
- (id)getBase64CommonMonitorData;
- (id)getToken;
- (void)resetValue;
- (id)init;

@end

